### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by Zaid-maker** [louislam/uptime-kuma#4528] opened 2024-02-25 20:12 UTC
### 📑 I have found these related issues/pull requests

....

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I know I know its off topic, but there is no other way I could say this.

From a very long time I want to see a Discrod Community for Uptime Kuma and I think it's time to make one before 2.0.0 release as it will allow maintainers to be more effecient and Louis can interact with people.

People want to be more active in Discord rather than Discord.

Hope it will get accepted 🙏 

### ✔️ Solution

Just make a Discrod Server

**Comment by CommanderStorm** [comment] 2024-02-25 23:36
> People want to be more active in Discord rather than Discord

XD

**Comment by CommanderStorm** [comment] 2024-02-25 23:41
Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/3770 and I don't think anything has changed since September.
TLDR: Discord is non-publicly-indexable, meaning that we can't use the positive network effects of helping out in the open and being indexable by Google/GitHub search.

Please also see https://www.reddit.com/r/UptimeKuma/

**Closed by CommanderStorm** 2024-02-25 23:41 UTC
Labels: feature-request
