### ISSUE TITLE
RingCentral Webhook as Seperate Webhook

### ISSUE THREAD

**Issue by lordmofisto** [louislam/uptime-kuma#3084] opened 2023-04-18 17:09 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

I have worked out how to post to a RingCentral Incoming Webhook. 

### ✔️ Solution 

<details><summary>I have modified the <code>server/notification-providers/webhook.js</code> to the following which allows posting to the RingCentral webhook</summary>
<p>

```js
const NotificationProvider = require("./notification-provider");
const axios = require("axios");
const FormData = require("form-data");

class Webhook extends NotificationProvider {
  name = "webhook";

  async send(notification, msg, monitorJSON = null, heartbeatJSON = null) {
    const okMsg = "Sent Successfully.";
    const { webhookContentType, webhookURL } = notification;
    const payload = {
        "activity": "Uptime-Kuma Monitoring Alert",
        "attachments": [{
          "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
          "type": "AdaptiveCard",
          "version": "1.3",
          "body": [
            
          ]
        }]
      };
    
    const config = {
      headers: {
        "Content-Type": webhookContentType === "form-data" ? "multipart/form-data" : "application/json"
      }
    };

    // Add additional headers to the payload if available
if (notification.webhookAdditionalHeaders) {
    try {
      const additionalHeaders = JSON.parse(notification.webhookAdditionalHeaders);
      payload.attachments[0].body[0].facts.push({
        title: "Payload",
        value: JSON.stringify(additionalHeaders)
      });
    } catch (err) {
      throw new Error("Additional Headers is not a valid JSON");
    }
  }

    const axiosPost = webhookContentType === "form-data" ?
      axios.post(webhookURL, formData, config) :
      axios.post(webhookURL, payload, config);

    try {
      if (webhookContentType === "form-data") {
        const formData = new FormData();
        formData.append("data", JSON.stringify(payload));
        await axiosPost;
      } else {
        await axiosPost;
      }

      return okMsg;
    } catch (error) {
      this.throwGeneralAxiosError(error);
    }
  }
  throwGeneralAxiosError = (error) => {
    const errorMessage = `Error sending webhook: ${error.message}`;
    const errorData = error.response?.data;
    const errorDetails = errorData ? `Response data: ${JSON.stringify(errorData)}` : '';
    const fullErrorMessage = `${errorMessage}\n${errorDetails}`;
    throw new Error(fullErrorMessage);
  }
}

module.exports = Webhook;
```

</p>
</details> 

### ❓ Alternatives

There is likely a lot of code that can be fixed or changed to make it better, this was the result of trial and error and a lot of error log reviewing to get it to this point. 

As of right now, it's working in my environment

**Comment by CommanderStorm** [comment] 2023-05-18 21:10
What have you modified?
The formatting of the current issue makes this basically unreviewable without extensive digging.

Could you:
- Reformat this issue with a [code diff](https://gist.github.com/salmedina/ad8bea4f46de97ea132f71b0bca73663#file-markdowndiffexample-md)
- Add a link to the file you modified

Is this a duplicate of #2967? (if no, please clarify the difference)

**Comment by lordmofisto** [comment] 2023-05-19 14:59
> 

Not necessarily a duplicate, more of an extension of it. 

In that one I was requesting a feature to be added, but the response wasn't encouraging so I decided to try to tackle it myself. 

That's where this thread comes in. 

I was able to get it working for my purposes using a RingCentral Incoming Webhook and formatting it in the Adaptive Card v1.3 or less format that they support. 

My method is very crude, but I am getting the alerts.

**Comment by CommanderStorm** [comment] 2023-05-19 18:24
What is the difference between this issue and #2967? What is the extension?

If you are proposing this as a new notification provider, please follow the pathway layed out here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
See #2980 for a successfull example of the required Pull Request.
Just posting (unformatted) code in an issue has a very low chance of getting into the codebase, as this does not scale from a workflow perspective for maintainers. Sorry

**Comment by CommanderStorm** [comment] 2023-12-09 22:10
Closing as a duplicate as @lordmofisto did not answer the questions about what the claimed enhancement is.
Will link the code in the other issue

**Closed by CommanderStorm** 2023-12-09 22:10 UTC
Labels: feature-request, area:notifications
