### ISSUE TITLE
[Help]: change the notify timezone

### ISSUE THREAD

**Issue by ccmaou** [louislam/uptime-kuma#839] opened 2021-10-30 13:09 UTC
### 📝 Describe your problem

how can i change the notify timezone,i modify the dashboard setting's timezone ，but it was no come into force，i also change the docker images timezone ,it also no come into force .how can i fix it?

### 🐻 Uptime-Kuma version

1.9.1

### 💻 Operating System

CentOS 7.9

### 🌐 Browser

Microsoft Edge

### 🐋 Docker

20.10.9

### 🏷️ Docker Image Tag

1.9.1

### 👀 Have you spent some time to check if this question has been raised before?

- [X] I checked and didn't find similar question

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by gaby** [comment] 2021-10-30 14:53
Duplicate of #40

Main issue is being handle at #646

**Closed** 2021-10-30 15:12 UTC
Labels: help
