### ISSUE TITLE
Notification when the status changes to waiting

### ISSUE THREAD

**Issue by sashkomel6** [louislam/uptime-kuma#4420] opened 2024-01-24 11:42 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

when I turn on TCP Port monitoring, when the state changes from allowed to waiting, no notification comes, it would be good if there was a function to turn on the notification when the status changes to waiting, not only unavailable

### ✔️ Solution

add the ability to enable notifications when a feature changes to standby, not just when unavailable

**Comment by CommanderStorm** [comment] 2024-01-24 11:49
I am assuming that allowed=`UP` and waiting=`PENDING`.

`PENDING` means you are currently retrying to send. You can disable this by setting the retry option to never retry.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/ebe7c026-c946-45e0-bd5e-4da6cffcf72f)
=> closing as resolved

Also I think this can be considered a duplicate of https://github.com/louislam/uptime-kuma/issues/508

**Closed by CommanderStorm** 2024-01-24 11:49 UTC
Labels: feature-request, area:notifications

**Comment by sashkomel6** [comment] 2024-01-24 12:00
I have these settings, but notifications come only when the status changes to unavailable or available, when the status becomes waiting, notifications do not come
![uptime kuma](https://github.com/louislam/uptime-kuma/assets/45562029/e1df3531-3b5d-4ba8-817e-62aec8d26a17)

**Comment by sashkomel6** [comment] 2024-01-24 12:02
![image](https://github.com/louislam/uptime-kuma/assets/45562029/7519760c-4a00-45c7-9c8d-16e3ed55871f)
it's about Expectation

**Comment by sashkomel6** [comment] 2024-01-24 12:30
I understood, thank you, I use Ukrainian and switched to English through the automatic translator to show you. Sorry for bothering you
