### ISSUE TITLE
Notification for maintenance 

### ISSUE THREAD

**Issue by Louis1505** [louislam/uptime-kuma#4513] opened 2024-02-21 16:36 UTC
### 📑 I have found these related issues/pull requests

-

### 🏷️ Feature Request Type

Maintenance

### 🔖 Feature description

Notification can be triggered when a maintenance starts, ends or is scheduled so that customers can get a message when a service is in maintenance 

### ✔️ Solution

Field to choose if the maintenance should send notifications and which notification type and for which triggers (starts, ends, is scheduled)

**Comment by CommanderStorm** [comment] 2024-02-21 16:45
Duplicate of https://github.com/louislam/uptime-kuma/issues/2462
Implementing this does likely require https://github.com/louislam/uptime-kuma/issues/508 first though.

=> closing as a duplicate

**Closed by CommanderStorm** 2024-02-21 16:45 UTC
Labels: feature-request, area:notifications, area:maintenance
