### ISSUE TITLE
Setting the status of the push-monitor status to `DOWN`/`UP`/...

### ISSUE THREAD

**Issue by mluecke1** [louislam/uptime-kuma#1386] opened 2022-03-18 16:04 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

It would be useful to set the current status for a push monitor manually via the API endpoint. It may be particularly useful in addition with #1359.

### ✔️ Solution

The following patch allows to set the status with:
- `?status=0` for `DOWN`
- `?status=1` for `UP`
- `?status=2` for `PENDING`

```diff
--- api-router.js.orig	2022-03-18 13:49:35.146412530 +0100
+++ api-router.js	2022-03-18 13:49:51.782064541 +0100
@@ -23,6 +23,7 @@
         let pushToken = request.params.pushToken;
         let msg = request.query.msg || "OK";
         let ping = request.query.ping || null;
+        let status = parseInt(request.query.status || UP,10);
 
         let monitor = await R.findOne("monitor", " push_token = ? AND active = 1 ", [
             pushToken
@@ -34,7 +35,7 @@
 
         const previousHeartbeat = await Monitor.getPreviousHeartbeat(monitor.id);
 
-        let status = UP;
+        //let status = UP;
         if (monitor.isUpsideDown()) {
             status = flipStatus(status);
         }
```

**Comment by koen20** [comment] 2022-03-18 18:45
Duplicate of #118

**Comment by CommanderStorm** [comment] 2024-01-31 20:06
Closing as implemented.
Setting `?status=down` makes the monitor go down.

Relevant code:

https://github.com/louislam/uptime-kuma/blob/3cea7d4eb23eb69140a79f2eb58d1d45a98dc88e/server/routers/api-router.js#L53-L54

**Closed by CommanderStorm** 2024-01-31 20:06 UTC
Labels: feature-request, area:monitor, type:enhance-existing
