### ISSUE TITLE
Bot Discord JS or PY

### ISSUE THREAD

**Issue by Dium-Corp** [louislam/uptime-kuma#3785] opened 2023-09-22 11:39 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

Create a source code with the API for a discord js or py bot and make it display the status of the pages you choose in /config and create the site for your previous site

### ✔️ Solution

Create a source code with the API for a discord js or py bot and make it display the status of the pages you choose in /config and create the site for your previous site

### ❓ Alternatives

Create a source code with the API for a discord js or py bot and make it display the status of the pages you choose in /config and create the site for your previous site

### 📝 Additional Context

Create a source code with the API for a discord js or py bot and make it display the status of the pages you choose in /config and create the site for your previous site

**Comment by CommanderStorm** [comment] 2023-09-22 11:58
You are quite unclear in what you are requesting.
Repeating that multiple times does not make this more clearer.

- We already have a discord notification provider.
- We currently don't have an api, see #118 for further details
- I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3508
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-09-22 22:26 UTC
Labels: feature-request
