### ISSUE TITLE
Open-ID Connect

### ISSUE THREAD

**Issue by 00ihsan** [louislam/uptime-kuma#3047] opened 2023-04-07 16:20 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

You should add Open-ID Connect for Single Sing-On and Two-Factor authentication with for example Authilia. 

### ✔️ Solution

I want to login with Authilia to my uptime kuma portal. 

### ❓ Alternatives

Now i need to save the password to somewhere and i do not have 2fa

### 📝 Additional Context

Check out Authelia’s GitHub.

**Comment by CommanderStorm** [comment] 2023-05-19 10:38
Duplicate of #553 If you agree, please feel free to close this issue

**Closed** 2023-05-19 10:44 UTC
Labels: feature-request
