### ISSUE TITLE
password protected status pages

### ISSUE THREAD

**Issue by nabz-polo** [louislam/uptime-kuma#5372] opened 2024-11-23 22:43 UTC
### 📑 I have found these related issues/pull requests

password protected status pages

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

password protected status pages

### ✔️ Solution

password protected status pages

### ❓ Alternatives

password protected status pages

### 📝 Additional Context

password protected status pages

**Comment by CommanderStorm** [comment] 2024-11-23 23:32
Duplicate of https://github.com/louislam/uptime-kuma/issues/1050

**Closed by CommanderStorm** 2024-11-23 23:32 UTC
Labels: feature-request, area:status-page
