### ISSUE TITLE
[Feature]: Option to edit the text "Powered by Uptime Kuma"

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [louislam/uptime-kuma#837] opened 2021-10-30 08:45 UTC
### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

On the status page, there is a credit/advertisement at the bottom of the page reading "Powered by Uptime Kuma". I think this text should have a customization option.

### ✔️ Solution

Implement an option to replace the "Powered by Uptime Kuma" text with custom text.

### ❓ Alternatives

Implement an option to add additional text above the "Powered by Uptime Kuma" text. This way, the credit/advertisement is preserved alongside user text for the benefit of the software author.

### 📝 Additional Context

An image of the text for context: https://i.ibb.co/9sLQ8zK/img.png

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar feature request

**Comment by gaby** [comment] 2021-10-30 11:13
Duplicate of #607 and #712 You clearly didn't use the search tool.

**Closed** 2021-10-30 12:13 UTC
Labels: enhancement

**Comment by louislam** [comment] 2021-10-30 13:14
> Duplicate of #607 and #712 You clearly didn't use the search tool.

I start to feel annoyed by duplicated questions/requests everyday. Really hope there is a bot that could do this job.

**Comment by gaby** [comment] 2021-10-30 15:13
@louislam Agree, I will do some research to see if there's a way to mitigate the duplicates.

**Comment by Stage4000** [comment] 2021-11-04 19:17
> > Duplicate of #607 and #712 You clearly didn't use the search tool.
> 
> I start to feel annoyed by duplicated questions/requests everyday. Really hope there is a bot that could do this job.

Turn on discussions for the repo and use that for feature requests instead of issues, this will help you in letting you close all issues that arent issues which will catch a lot of the morons that dont read stuff and create duplicate feature requests.

**Comment by deefdragon** [comment] 2021-11-05 02:19
> > > Duplicate of #607 and #712 You clearly didn't use the search tool.
> > 
> > 
> > I start to feel annoyed by duplicated questions/requests everyday. Really hope there is a bot that could do this job.
> 
> Turn on discussions for the repo and use that for feature requests instead of issues, this will help you in letting you close all issues that aren't issues which will catch a lot of the morons that don't read stuff and create duplicate feature requests.

While I do think that discussions should be turned on as they are very good for working out how to tackle changes, or what potential changes to make etc, I still think that feature requests belong under issues. At its core, feature requests are UK not doing what the user needs of it.

> I start to feel annoyed by duplicated questions/requests everyday. Really hope there is a bot that could do this job.

Its an unfortunate side effect of such a popular tool. While it won't deal with people asking the same questions over and over again, it might help take care of them faster if you grant [triage or potentially write](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role) permissions to some of the contributors.

As for the bot, There are a few that appear to exist, but none of them have activity for the last few years. It may be possible to build one in an _on-new-issue_ github action.

**Comment by Stage4000** [comment] 2021-11-05 18:33
There isnt a good way for a bot to kill duplicates without the use of AI which can become quite expensive to host. Without AI youre basically limited to textual search alone which wont really do crap to stop duplicates. I disagree with your argument that feature suggestions are issues because they are not cases of the programs existing features malfunctioning and instead is a request to expand upon it. Further moving feature requests out of issues will allow for contributors to better see what issues are actually occuring with the existing code instead of being burried in begging requests.
