### ISSUE TITLE
Add "Docker Socket" as a monitor type

### ISSUE THREAD

**Issue by SoulEater45** [louislam/uptime-kuma#1797] opened 2022-06-20 17:26 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

When adding a new monitor, we could have in the `Monitor Type` list an option for monitoring docker containers using the `/var/run/docker.socket` socket.

### ✔️ Solution

Choose `Docker` from the list and supply the container name to be monitored. Every `X` seconds it will scan all containers and see if our container is among the currently active ones. There should be a library for accessing the docker API in each major language, for example [node](https://agustincb.github.io/docker-api/) or [python](https://docker-py.readthedocs.io/en/stable/).

**Bonus**: maybe apply labels and automatically monitor containers with the `kuma.monitor=true` label.

### ❓ Alternatives

An alternative for this would be to create a network, let's say `kuma`, and add all containers to this network. Then we can make a ping to `container_name.network_name`. This is how I am doing it currently for containers exposed with traefik. A downside to this approach is managing containers to be present in one more network and maybe we do not want to have some containers talking to each others.

### 📝 Additional Context

Enabling this feature would mean `kuma` needs access to the `/var/run/docker.socket` socket. By just mounting it in a read-only state, external breaches can not cause the creation of wild containers. I am not sure if containers could be accessed, i.e., a `docker exec` can be executed, but that should not be such a problem to mitigate.

**Comment by louislam** [comment] 2022-06-21 07:25
Duplicate of #1020

**Closed by louislam** 2022-06-21 07:25 UTC
Labels: feature-request
