### ISSUE TITLE
monitor server load and cpu/ram/disk usage 

### ISSUE THREAD

**Issue by tcpzix** [louislam/uptime-kuma#2921] opened 2023-03-12 09:54 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

it will be amazing if we can monitor server load and resource with kuma! :)

### ✔️ Solution

monitor disk cpu ram server load

**Comment by cal97g** [comment] 2023-04-07 22:12
This would be great.

**Comment by Prajwal433** [comment] 2023-05-07 07:16
please do it requesting

**Comment by kokofixcomputers** [comment] 2023-05-07 16:26
That would be great.

**Comment by jondycz** [comment] 2023-05-10 06:01
This is the only reason I haven't switched yet

**Comment by kokofixcomputers** [comment] 2023-05-23 23:37
> This is the only reason I haven't switched yet

What is the reason?

**Comment by CommanderStorm** [comment] 2023-05-24 00:36
@tcpzix 
Is this a duplicate of #819?

**Comment by tcpzix** [comment] 2023-05-29 10:47
yes you right this is a duplicate of #819 and i'm sorry about that
thanks

**Comment by CommanderStorm** [comment] 2023-05-29 11:53
@tcpzix could you close this issue then? ^^

**Comment by tcpzix** [comment] 2023-05-29 14:53
Yes, it's done.

**Closed** 2023-05-29 14:53 UTC
Labels: feature-request
