### ISSUE TITLE
A kind of filter template SEO or SEO Monitor

### ISSUE THREAD

**Issue by syberx** [louislam/uptime-kuma#3897] opened 2023-10-15 08:58 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be great if there was a way to assign templates or group templates. Here you could set keywords such as "nofollow," "noindex," etc. So, monitoring the page for SEO parameters/metas. It's cumbersome when you have to set everything individually. Often, there are multiple options per URL.

### ✔️ Solution

I can create a keyword template for a group. All pages assigned to the group will be automatically searched for the group's keywords. Alternatively, an SEO monitor with the option to select various SEO parameters, such as nofollow, noindex, and more.

**Comment by CommanderStorm** [comment] 2023-10-16 00:06
I think this is a duplicate of either bulk actions (see https://github.com/louislam/uptime-kuma/issues/2934) or config templates (see https://github.com/louislam/uptime-kuma/issues/1323)
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-05 11:10
@syberx 
@
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/2934 and https://github.com/louislam/uptime-kuma/issues/1323 as there is no difference
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-05 11:10 UTC
Labels: feature-request, area:monitor
