### ISSUE TITLE
Docker unhealthy after setting https

### ISSUE THREAD

**Issue by xorguy** [louislam/uptime-kuma#343] opened 2021-09-06 21:29 UTC
After enabling HTTPS via environment variables with the certificate and private key, docker appears as unhealthy.

1. Enable HTTPS support in Docker setting environment variables to valid certificate and private key.
2. Run docker or docker-compose
3. Docker is shown as unhealthy in Portainer

**Expected behavior**
Docker should appear as healthy whenever using HTTPS or plain HTTP.

**Info**
- Uptime Kuma Version: 1.5.3
- Using Docker?: Yes
- OS: Raspbian

**Comment by chakflying** [comment] 2021-09-07 03:11
confirmed, `healthcheck.js` doesn't support HTTPS. I tried adding a HTTPS check, but it also fails if the cert is invalid, which may not be the desired behavior.

**Comment by louislam** [comment] 2021-09-07 04:35
I just realized that there are several problems in the healthcheck.js, the port and hostname is also having similar problem. I will fix it.

**Comment by louislam** [comment] 2021-09-07 08:11
Fixed in https://github.com/louislam/uptime-kuma/commit/ec8c1cad31483ba26c51d90e99e9981c1bbef7f9

**Comment by gaby** [comment] 2021-09-08 01:27
I was confused because the TLS env variables are not documented. Using NGINX was a better solution for me, specially since I wanted uptime-kuma running on port 443.

**Closed** 2021-09-08 12:02 UTC
Labels: bug
