### ISSUE TITLE
Configurable number of packets send for tests

### ISSUE THREAD

**Issue by moucho** [louislam/uptime-kuma#2618] opened 2023-01-16 12:52 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

After the change in #2223 , the number of packets sent changed from 10 to 1, which in some cases could lead to false alerts.

### ✔️ Solution

It could be interesting to have a setting for the number of packets sent for tests, the same as retries for example.

If not, I think it may be better to set it back to 10 as it was.

**Comment by Computroniks** [comment] 2023-01-16 15:08
Yeah, I am looking into this

**Comment by louislam** [comment] 2023-01-16 16:12
Duplicate of #1891

**Comment by louislam** [comment] 2023-01-16 17:05
Oh I messed up with `the number of packets sent` and `packet size`. Reopen.

**Comment by louislam** [comment] 2023-01-16 17:18
OK, I messed up with `deadline` (-w) and `timeout` (-W)...

**Closed** 2023-01-16 17:21 UTC
Labels: feature-request

**Comment by chakflying** [comment] 2023-01-19 22:20
@louislam looks like running the ping monitor on Windows triggers the error message "There is no deadline option on windows"
![image](https://user-images.githubusercontent.com/3271800/213575261-9b47f456-e9ff-4040-848d-81cba21c9857.png)
