### ISSUE TITLE
Coming from Uptime Robot I have a couple suggestions

### ISSUE THREAD

**Issue by cien-fuegos** [louislam/uptime-kuma#739] opened 2021-10-18 12:36 UTC
**Is it a duplicate question?**
I searched but didn't find anything

**Is your feature request related to a problem? Please describe.**
More like quality of life than a problem.

First: I noticed today that whenever I see a monitor it doesn't show me the total time it has been up/down. It tells me the ping lost and then comes up some time later. I'm just used to Uptime Robot that shows the total time it has been up or the total down time.

Second: Whenever an email comes in notifying me of downtime, it shows the UTC and doesn't change for time zone. For example my monitor went down at 01:51 on Uptime Kuma and the email says 06:51. I just know from experience if a customer or client gets that email (we often send emails to them and to our ticketing system) and the time is different, they'll be confused.

Third: This is the most quality of life change I'd like to see...it's just to display the number of down monitors in the tab of the browser. 

Fourth: I'd like there to be an option to turn off the email when it comes Up. Since I will be sending emails to a ticketing system...if I get an email whenever it goes down and when it comes up this would create 2 tickets for me instead of just 1.

**Describe the solution you'd like**
First: I'd like the total downtime or uptime to be added to each event. If a monitor went down for 49 minutes...I'd like that displayed. If it has been up for 12 days 10 hours and 19 minutes I'd like that displayed as well next to the uptime events.

Second: Adjust email time to timezone in the monitors.

Third: I'd like there to be a number displayed in the tab of the browser that shows any down (not paused) monitors that updates every so often (probably every few minutes or every minute?)

Fourth: Radio button or switch to opt in to getting emails for Up events

**Describe alternatives you've considered**
None

**Additional context**
![kuma](https://user-images.githubusercontent.com/92477134/137731612-e69aabd6-5e59-43a9-ba70-ad8e703802ce.png)

![Uptime Robot](https://user-images.githubusercontent.com/92477134/137731632-a91e7b61-6abb-4e11-ad9b-74e9c0073515.png)

**Comment by louislam** [comment] 2021-10-20 03:19
First: Duplicate of #177
Second: Duplicate of #40
Third: Duplicate of #728
Fourth: Duplicate of #508

**Closed by louislam** 2021-10-20 03:19 UTC
Labels: enhancement
