### ISSUE TITLE
A notification should be sent when a maintenance is started/ended with the list of affected monitors

### ISSUE THREAD

**Issue by Lanhild** [louislam/uptime-kuma#2722] opened 2023-02-06 00:38 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

When adding a maintenance, affected monitors should send a notification that they are in maintenance.

### ✔️ Solution

When adding a maintenance, affected monitors should send a notification that they are in maintenance.

**Comment by louislam** [comment] 2023-02-06 07:08
What is your use case of maintenance mode? 

It is because maintenance mode is designed for muting notifications.

**Comment by Lanhild** [comment] 2023-02-09 20:02
I want to monitors to send a notification to alert that they're in maintenance mode. Basically, I want something that can notify you when a monitor is in maintenance mode without going to the Uptime Kuma interface

**Comment by Lanhild** [comment] 2023-02-25 16:29
@louislam any news? Tell me if you need a more detailed explanation of what I'd like to have.

**Comment by Schwoby** [comment] 2023-03-13 07:45
how would Uptime Kuma know the system/monitor is in maintenance mode vs an actual outage without it being told? the ping, or however you have the monitor configured, only knows that its not getting the result it is supposed to get.

or are you saying you want the maintenance mode itself to alert for the start/end of the maintenance period?

**Comment by Lanhild** [comment] 2023-03-13 18:16
>or are you saying you want the maintenance mode itself to alert for the start/end of the maintenance period?

This is exactly what I want

**Comment by Lanhild** [comment] 2023-03-16 00:55
That'll be useful because other than going on a status page or the dashboard, there is no way to know that there is a maintenance started/ended

**Comment by Lanhild** [comment] 2023-03-24 19:45
@louislam Do you have any plans on implementing something like this?

**Comment by CommanderStorm** [comment] 2023-05-25 10:42
@Lanhild 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by CommanderStorm** [comment] 2023-06-10 23:06
@Lanhild I think this is a duplicate of #2462

Given that the other issue has
- less spam and
- more upvotes
I think closing this issue and continuing over there would be a good thing to get this back to a productive state.
Duplicates only make issue management harder.

(Only you or Louis can close this issue, this is why I am tagging you)

**Comment by Lanhild** [comment] 2023-06-11 06:50
Thanks for the heads up! Closing as duplicate

**Closed** 2023-06-11 06:50 UTC
Labels: feature-request

**Comment by CommanderStorm** [comment] 2023-06-11 10:17
Thanks ❤️
