### ISSUE TITLE
Support IaC  as optional (define services from config file)

### ISSUE THREAD

**Issue by Planxnx** [louislam/uptime-kuma#2225] opened 2022-10-14 17:32 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

The monitoring service should be able to define services from config files (yaml or json) as an additional option.

We currently have over a hundred services to monitor and use too much effort to maintain this.
We use gitops for IaC and need to deploy new services while adding new services to monitoring services.

Same as #270

### ✔️ Solution

- allow adding/editing/removing services from config file like yml or json (should be optional)
- similar to importing backup but it should be automatic loading.

**Comment by louislam** [comment] 2022-10-15 13:31
Duplicate of https://github.com/louislam/uptime-kuma/issues/270

**Closed by louislam** 2022-10-15 13:31 UTC
Labels: feature-request

**Comment by Planxnx** [comment] 2022-10-15 13:47
> Duplicate of https://github.com/louislam/uptime-kuma/issues/270

#279 is closed and not been solved. Why is it closed too?

This request feature is add an option to import config file and not required option. 
It's similar to #279 but isn't the same thing(or duplicate).
