### ISSUE TITLE
Notifications support using Proxies

### ISSUE THREAD

**Issue by BingYanchi** [louislam/uptime-kuma#4206] opened 2023-12-10 17:17 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Applicable scenario: In mainland China, Discord Notifications cannot be used because Discord cannot be accessed.

It is hoped that the Proxies option can be added to Notifications to allow the use of Proxy in Proxies.

### ✔️ Solution

Add the option to select proxy on the Add page of Notification, just like selecting proxy for monitoring items.

**Comment by CommanderStorm** [comment] 2023-12-10 18:11
Duplicate of #616

**Closed by CommanderStorm** 2023-12-10 18:11 UTC
Labels: feature-request, area:notifications
