### ISSUE TITLE
The sizes of these beats look different

### ISSUE THREAD

**Issue by Eronana** [louislam/uptime-kuma#358] opened 2021-09-08 11:22 UTC
**Describe the bug**
The sizes of these beats look different, it's so weird.
![image](https://user-images.githubusercontent.com/9164153/132500451-d7c68085-f6f0-4102-875d-95255b118dc7.png)

**Expected behavior**
They should have the same size.

**Info**
- Uptime Kuma Version: latest
- Using Docker?: Yes
- OS: MacOS
- Browser: Chrome and Safari

**Comment by louislam** [comment] 2021-09-08 11:46
Duplicate of #326

**Closed by louislam** 2021-09-08 11:46 UTC
Labels: bug
