### ISSUE TITLE
Total Time for outage

### ISSUE THREAD

**Issue by thekayman** [louislam/uptime-kuma#3301] opened 2023-06-22 03:02 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

Hi, is it possible to add into the notification  and UI how long a monitor was down for.

### ✔️ Solution

It would be great if within the notification and UI when a monitor goes down and comes back up it shows how long the outage was for.

i.e. ([Monitor Name] [✅ Up] 200 - OK Time (UTC): 2023-06-22 02:42:48.611 **(Down for 2 mins 10 seconds)**
and in the UI something similar.

**Comment by CommanderStorm** [comment] 2023-07-09 14:56
> Should I work on this feature?

PRs welcome, as always.

If you do decide to work on this, please break this into multiple parts for easier reviewability:
- one PR for adding such a value to the JSON passed to the notification provider
- one PR per notification provider you would like to fix (remember to include screenshots) ^^

**Comment by CommanderStorm** [comment] 2023-12-14 00:46
Duplicate of #177 => closing and continuing to track there

**Closed by CommanderStorm** 2023-12-14 00:46 UTC
Labels: feature-request, area:monitor, area:notifications
