### ISSUE TITLE
Links in status page services

### ISSUE THREAD

**Issue by hiagodotme** [louislam/uptime-kuma#4294] opened 2023-12-27 23:34 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be interesting if I could direct users to other URLs when clicking on a service link on a monitor.

I have many services, so I grouped them and created a status page for each link. Something that I found very interesting was being able to create a monitor making groups available as services. So I could look at a macro panel and understand if everything is OK.

### ✔️ Solution

What I need is that when I click on an item in the group, I open a status page where the services of that group will be detailed. Basically, if I can put links in the services for anyone who accesses to click, that would already meet the need.

**Comment by CommanderStorm** [comment] 2023-12-28 05:14
Duplicate of #2507

**Closed by CommanderStorm** 2023-12-28 05:14 UTC
Labels: feature-request, area:status-page
