### ISSUE TITLE
Edit notifications / add extra options to the notifications that are sent

### ISSUE THREAD

**Issue by Panja0** [louislam/uptime-kuma#428] opened 2021-09-17 09:45 UTC
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like a way to edit the notifications or add extra options to the notifications that are sent 
For instance it would be great when a server/service is back online, that in the notification it is stated how long (xx minutes/hours) the server or service was down. E.g. :

```
[blablabla.com] [✔] Up] 200 - OK
Downtime: 3 min
```

Maybe add a timestamp for the server/service down/up notification as well. E.g.:
```
[blablabla.com] [✔] Up] 200 - OK
Downtime: 3 min
Noticed at: 2021-09-17 11:44:24 (CEST)
```

**Comment by srgvg** [comment] 2021-10-06 09:23
I'd like to suggest to also put the short updated parts of the notification (like here, `200 - OK`) between `[]` brackets, and not the part that tells which monitor the mail is about. REason is, some mail programs only look at the part not between brackets, to group threads (like GMail..) 
See #172 for more details.

**Comment by sebastienPoussard** [comment] 2022-05-08 19:44
would love this feature as well !

**Comment by syafiyullah** [comment] 2023-05-14 12:54
I'm looking forward to have this great feature. Thanks for your effort!

**Comment by CommanderStorm** [comment] 2023-07-25 14:16
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/177
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-17 21:11
Clsing as a duplicate:
- templating is tracked in https://github.com/louislam/uptime-kuma/issues/646
- Downtime length is tracked in #177

**Closed by CommanderStorm** 2023-12-17 21:11 UTC
Labels: feature-request, area:notifications
