### ISSUE TITLE
Request - "Test Now"

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#3800] opened 2023-09-25 11:05 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Please could we get a "Test Now" or "Check Now" feature for monitors.

When a monitor reports a failure, one fixes the root-cause of the issue. It can then take some time for the monitor to re-run and detect that the problem has been resolved.

It would be great to have a way to check straight away that the problem has been resolved.

### ✔️ Solution

We could have a "Test" button, maybe next to the Pause button, to kick the monitor check into life straight away, rather than waiting for the next run, which could be some minutes away.

**Comment by rezzorix** [comment] 2023-09-25 13:04
Pause and restart has the same effect…?
So when you restart a monitor it will be automatically checked. No “check now” button required.

**Comment by louislam** [comment] 2023-09-26 20:48
Duplicate of #2725. And some discussions also here: #2834

**Closed by louislam** 2023-09-26 20:48 UTC
Labels: feature-request
