### ISSUE TITLE
daily status check instead of every time that the user set

### ISSUE THREAD

**Issue by antonioraminhos** [louislam/uptime-kuma#4404] opened 2024-01-20 16:55 UTC
![image](https://github.com/louislam/uptime-kuma/assets/156920116/f103b90f-1530-49fc-9b91-2060bdd2182e)

uptime robot example:
![image](https://github.com/louislam/uptime-kuma/assets/156920116/73845f75-fb38-41af-82ea-e56bfe3d387e)

**Comment by antonioraminhos** [comment] 2024-01-20 16:57
instead of displaying every ping check on the web ui, just display the daily health of the monitor like this:

![image](https://github.com/louislam/uptime-kuma/assets/156920116/dbbde719-e1c8-481e-9a2c-c7d13f55294a)

**Comment by chakflying** [comment] 2024-01-20 17:44
Duplicate of #1888

**Closed by chakflying** 2024-01-20 17:44 UTC
Labels: feature-request, invalid
