### ISSUE TITLE
Multiple monitoring for a singles Monitor

### ISSUE THREAD

**Issue by juniorsaldanha** [louislam/uptime-kuma#731] opened 2021-10-17 07:08 UTC
I was wondering if it makes sense to have more than one type of 'monitor' on a monitor, for example I have an mqtt server that uses port 1883 and 9001, I want to monitor both ports on the same monitor (service).

**Comment by deefdragon** [comment] 2021-10-17 09:06
Duplicate of several other issues. Specifically #497.

**Closed** 2021-10-17 13:34 UTC
Labels: enhancement
