### ISSUE TITLE
Notification Sound on System

### ISSUE THREAD

**Issue by RansomeBell** [louislam/uptime-kuma#4737] opened 2024-05-03 21:58 UTC
### 📑 I have found these related issues/pull requests

I have not found any related requests. I'm sure this wouldn't be hard to add.

### 🏷️ Feature Request Type

New notification-provider

### 🔖 Feature description

Could you add a notification sound for when a service goes down? The monitoring software we use right now is end of life. The software we have right now alerts us visually and sounds an alert to let us know that something is down. Your software checks all of our boxes, except for the sound notification part. We don't want care to get an alert on our phones or teams etc. We have a TV that we have our current monitoring software on that sounds an alert when one of our services goes down. 

### ✔️ Solution

We would like to be alerted with a sound when a service goes down. Also add a sound alert for when you do add SNMP.

**Comment by CommanderStorm** [comment] 2024-05-03 23:24
Duplicate of https://github.com/louislam/uptime-kuma/issues/3091

**Closed by CommanderStorm** 2024-05-03 23:24 UTC
Labels: feature-request

**Comment by RansomeBell** [comment] 2024-05-06 18:06
All of the notification types that existing are throw text message or some kind of messenger. It would be nice to have an option just for notification sounds straight from the program, and not having to reply on a 3rd party service. The duplicate request that you marked this under actually as nothing to do with that at all.

**Comment by CommanderStorm** [comment] 2024-05-06 23:11
https://github.com/louislam/uptime-kuma/issues/3091 wants

> detect a malfunction [..] notification is accompanied by a sound prompted on the web

You want

> would like to be alerted with a sound when a service goes down

=> both this issue and #3091 want to be notified via a sound once a service is `DOWN`.

Am I missing somethign here?

**Comment by RansomeBell** [comment] 2024-05-09 01:32
I was requesting to add sound without having to go through a 3rd party service. I would have this up on a TV and would like the program to have its own sound for when something goes down. In easy terms, add sound wihtout going through a 3rd party app.

**Comment by RansomeBell** [comment] 2024-05-09 01:33
I don't know how to explain it any easier than that.

**Comment by CommanderStorm** [comment] 2024-05-09 10:16
But that is exactly the feature that #3091 is requesting? Don't get what I am missing if anything.
