### ISSUE TITLE
Adding new monitors (automation)

### ISSUE THREAD

**Issue by wojcikm** [louislam/uptime-kuma#1940] opened 2022-07-25 13:00 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hence there is ongoing [discussion](https://github.com/louislam/uptime-kuma/issues/118) about adding API & terraform modules later on - is it possible right now to somehow automate adding new monitors? I have over 1k domains to monitor.

### ✔️ Solution

Scipt, interface or actually anything which will make adding multiple monitors at the same time possible.

**Comment by d-delaey** [comment] 2022-07-26 14:24
@wojcikm i think there is no way to fully automate it. I recently migrated around 300 Domains via the Backup functionality (from Uptime Robot). But a API would be really great and usefull.

**Comment by danijelst** [comment] 2022-08-04 12:57
@wojcikm you can do so via the sqlite database and insert new domains into the *monitor* table.

**Comment by wojcikm** [comment] 2022-09-30 14:33
I have bypassed this limitation by creating backup file and parsing escipt. Then I just import bigger json. The next issue though is that the large file fails during upload, so next step is to split them into two smaller ones. But it works 👍

**Comment by agenceKanvas** [comment] 2023-01-12 11:16
What's the file limit ? I have more than 700 domains to import, I will try the backup solution

**Comment by CommanderStorm** [comment] 2023-08-15 22:42
@wojcikm 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/118 https://github.com/louislam/uptime-kuma/issues/763 https://github.com/louislam/uptime-kuma/issues/210
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-05 00:38
@wojcikm 

We are consolidating duplicate issues a bit to make issue management easier.

I am going to close this as a duplicate of https://github.com/louislam/uptime-kuma/issues/118 https://github.com/louislam/uptime-kuma/issues/763 https://github.com/louislam/uptime-kuma/issues/210

**Closed by CommanderStorm** 2023-12-05 00:38 UTC
Labels: feature-request
