### ISSUE TITLE
Use of relative paths to enable usage with different reverse proxy locations

### ISSUE THREAD

**Issue by raihei** [louislam/uptime-kuma#4303] opened 2023-12-31 15:53 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be nice to use relative paths in the html files (for the assets, etc.)
It would make it possible, to use uptime kuma with reverse proxy locations other than "/"

E.g. proxy via nginx from https://someserver/uptime to http://uptimekumaip:3001

With the absolute paths used, uptime kuma will try to load the assets from https://someserver/assets/ instead of https://someserver/uptime/assets

### ✔️ Solution

Change html (and other required files) to use relative instead of absolute paths for assets and links.

**Comment by CommanderStorm** [comment] 2023-12-31 20:35
Duplicate of https://github.com/louislam/uptime-kuma/issues/147

**Closed by CommanderStorm** 2023-12-31 20:35 UTC
Labels: feature-request

**Comment by CommanderStorm** [comment] 2023-12-31 20:38
See #1092 for the challenges in verifying that this works
