### ISSUE TITLE
Multiple statuspages

### ISSUE THREAD

**Issue by codeagencybe** [louislam/uptime-kuma#1195] opened 2022-01-17 09:30 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, UI Feature, Other

### 🔖 Feature description

I would like to see a feature to create multiple status pages. 
This could be for internal/public usage but also maybe a statuspage per customer or per project whatever the use case may be. 

This idea comes from https://updown.io and offer this solution. 
It allows me to create seperate statuspages per customer where they can keep track of their own monitors. 

<img width="824" alt="image" src="https://user-images.githubusercontent.com/7568546/149743118-629b6d1f-99fd-4efb-9d7b-4fcc47816185.png">

<img width="874" alt="image" src="https://user-images.githubusercontent.com/7568546/149743294-0689eee6-e698-4cc0-b942-b08b0e180045.png">

### ✔️ Solution

- option to create multiple status pages
- show monitors and select which ones to add to status page (possible to add same monitor to multiple different status pages)
- option to set custom (sub)domain per status page

### ❓ Alternatives

https://updown.io

**Comment by koen20** [comment] 2022-01-18 13:01
Duplicate of #530

**Closed** 2022-01-20 04:43 UTC
Labels: feature-request
