### ISSUE TITLE
Even Log Export Option.

### ISSUE THREAD

**Issue by Gururaj08** [louislam/uptime-kuma#3790] opened 2023-09-23 07:37 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Can we add the Export Log option, With a Selective time frame of 1 Day, 1 Week, 1 Month, 3 Month? 
This option can help us to export the event logs in cvs format. 

![Option](https://github.com/louislam/uptime-kuma/assets/41589151/cc45243c-f9e7-42c5-b33f-01592654b44d)

### ✔️ Solution

Can we add the Export Log option, With a Selective time frame of 1 Day, 1 Week, 1 Month, 3 Month? 
This option can help us to export the event logs in cvs format. 

### ❓ Alternatives

Can we add the Export Log option, With a Selective time frame of 1 Day, 1 Week, 1 Month, 3 Month? 
This option can help us to export the event logs in cvs format. 

### 📝 Additional Context

Can we add the Export Log option, With a Selective time frame of 1 Day, 1 Week, 1 Month, 3 Month? 
This option can help us to export the event logs in cvs format.

**Comment by CommanderStorm** [comment] 2023-09-23 15:36
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2733
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-09-23 15:42
Given that until now, you have created 3 issues for the exact same feature, please stop doing that:
This won't make the feature you want to happen sooner, rather this behaviour might lead to the opposite effect.

What you're forgetting is that you're not talking to some faceless gigacorp here.
Instead, this is an organisation run by human beings who have decided to donate their time working on something for free to the world.

**Comment by CommanderStorm** [comment] 2023-12-03 14:56
Closing as a duplicate of (your own previous issue!) #2733 or #1101

**Closed by CommanderStorm** 2023-12-03 14:56 UTC
Labels: feature-request
