### ISSUE TITLE
SNMP Monitor of generic SNMP OIDs for Routers/Printers/Switches/Servers

### ISSUE THREAD

**Issue by NEBELWAENDE** [louislam/uptime-kuma#3765] opened 2023-09-19 06:23 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

To be able to check if a certain SNMP OID has a given String/Value and reached a certain Threshold

### ✔️ Solution

I have several SNMP Devices like Router / Printer / Switches and Servers and i want to Check Toner / Harddisk consumtion / CPU Utilisation via SNMP Host Ressources MIB oder Printer MIB

### ❓ Alternatives

Check the Values manualy via SNMPWALK / SNMPGET Unix/Linux CLI

### 📝 Additional Context

..

**Comment by CommanderStorm** [comment] 2023-09-19 18:47
@NEBELWAENDE 
I think this is a duplicate of #1675 and its dulicates like #3366, https://github.com/louislam/uptime-kuma/issues/1779, https://github.com/louislam/uptime-kuma/issues/420 
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by NEBELWAENDE** [comment] 2023-09-20 03:32
I appologize - yes you are right. This is one of several duplicates on the needed SNMP availability in uptime kuma. I have seen in the syslog that the ping Implementation fires up ping commands periodicaly. An similar implementation of SNMP could be easy to use snmpget / snmpwalk CLI in the background. But anyway - ill close this one to keep the others alive the next couple of days. Warm regards, Gregor

**Comment by NEBELWAENDE** [comment] 2023-09-20 03:49
On Ubuntu/Debian/Rasbian you can install [Net-SNMP](http://www.net-snmp.org/) tools with one simple command: “apt-get install snmp“, or if you have CentOS/RHEL/Oracle Linux/Fedora you can use “yum install net-snmp net-snmp-utils“

$ snmpget -v 2c 127.0.0.1 -c public .1.3.6.1.2.1.1.5.0
SNMPv2-MIB::sysName.0 = STRING: centos7

$ snmpget -v 2c 127.0.0.1 -c public sysName.0
SNMPv2-MIB::sysName.0 = STRING: centos7

https://jfearn.fedorapeople.org/fdocs/en-US/Fedora_Draft_Documentation/0.1/html/System_Administrators_Guide/sect-System_Monitoring_Tools-Net-SNMP-Retrieving.html

**Comment by NEBELWAENDE** [comment] 2023-09-20 03:50
Tank you.

**Comment by NEBELWAENDE** [comment] 2023-09-20 03:51
.

**Closed** 2023-09-20 03:53 UTC
Labels: feature-request
