### ISSUE TITLE
Setting the time period shown on status pages

### ISSUE THREAD

**Issue by A-H99** [louislam/uptime-kuma#5350] opened 2024-11-17 10:44 UTC
### 📑 I have found these related issues/pull requests

well I've been researching how to do this for 2 or 3 weeks now and there no option built in kuma for this issue unless i change the source code and this road usually ends with more problems for me. 

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

So I have made a list of servers and added them to a status page and I added the URL of the said page on my site for the customers, so they can see the uptime of the servers we are selling them, but little did i know that the time period is 40 mins and there is no built in option for me to change the time period shown in status page e.g. 365 days. 

### ✔️ Solution

I don't know much but I think there should be a built in option to set the time period that is shown in status pages.

### ❓ Alternatives

Or a shorter way would be a way to export the uptimes shown to me to a URL witch I can use on my site. I think it would be easier.

**Comment by CommanderStorm** [comment] 2024-11-17 13:11
Duplicate of
- https://github.com/louislam/uptime-kuma/issues/986

> change the source code and this road usually ends with more problems for me

=> Please discuss your approach (what you tried, what did not work) in said issue

Closing as a duplicate

**Closed by CommanderStorm** 2024-11-17 13:11 UTC
Labels: feature-request, area:status-page
