### ISSUE TITLE
Changing the time period of the beats 

### ISSUE THREAD

**Issue by duylong** [louislam/uptime-kuma#1167] opened 2022-01-11 21:28 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Hello,

It would be nice to be able to change the time period of beats. By default, it seems to me that we only display the last 30 minutes. 

As the time period is 24 hours by default in the availability rate, having a 24 hour period of beats would be consistent. 

### ✔️ Solution

We could add the possibility in the options.

Add an option to choose the time period (the number of beats is deducted). For example:

```
30 minutes => 30 beats, 1 minute per beat
60 minutes => 30 beats, 2 minutes per beat
5 hours => 30 beats, 30 minutes per beat
24h => 24 beats, 1 hour per beat
```

**Comment by stephen304** [comment] 2022-01-15 02:17
I would like to be able to go all the way to 1 day per beat - so that more stable monitors don't just show fully green all the time.

Here is a 90-day 1 beat per day from my statping:
![image](https://user-images.githubusercontent.com/981915/149605205-d9d87f6a-72be-4d7b-8e4e-899ad4cc9fb6.png)

**Comment by hhslepicka** [comment] 2024-01-16 01:54
This would be a great feature to have. @louislam @CommanderStorm, is this something for v2, or do you foresee it becoming available in v1.x?

**Comment by CommanderStorm** [comment] 2024-01-16 09:59
@hhslepicka without the accounting/performance improvements of V2 this would be impossible.
Furthermore this is a feature=> won't be included in V1 as we only include bugfixes.

PRs appreciated

**Comment by StillLearnin** [comment] 2024-09-07 12:42
I believe this is a duplicate of #1888 and could be closed.

**Comment by CommanderStorm** [comment] 2024-09-08 09:48
True, closing as a duplicate

**Closed** 2024-09-08 09:48 UTC
Labels: feature-request, area:status-page, area:dashboard
