### ISSUE TITLE
Store settings outside the statisctis DB so we can git ignore statistics and keep settings on Git

### ISSUE THREAD

**Issue by carlos-algms** [louislam/uptime-kuma#4319] opened 2024-01-04 08:33 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Save settings, dashboards, and monitors config, in a different place other than a single `.DB` file. 
So we can include those files on Git and have historical data and visual diffs of what was changed individually per section.

### ✔️ Solution

It would be great to have settings stored under `/app/data/settings/` as `JSON` or `YAML`.

### ❓ Alternatives

I'm currently adding `kuma.db` to Git, but it keeps changing every 1 minute or so, and it is most likely including data that is not crucial to restore an instance in case of an issue.

### 📝 Additional Context

It could help with the UI backups as well, as we could just zip the `/settings` folder and restore and override everything inside of it. 
Or instead of replacing, we could "merge" existing settings with the ones being imported.

**Comment by CommanderStorm** [comment] 2024-01-04 17:01
> I'm currently adding kuma.db to Git

Git is not designed for backuping binary blobs
I would not recomend using it this way.

The rest is a duplicate of these two issues (closing as duplicate):
- config files: https://github.com/louislam/uptime-kuma/issues/956
- splitting the db: https://github.com/louislam/uptime-kuma/issues/2496

**Closed by CommanderStorm** 2024-01-04 17:01 UTC
Labels: feature-request, area:core
