### ISSUE TITLE
How can I change the  message template  of  DingDing 

### ISSUE THREAD

**Issue by hlf2016** [louislam/uptime-kuma#1377] opened 2022-03-16 03:30 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

How can I change the  message template  of  DingDing , such as @ someone by DingDing bot or  change the massage type

### ✔️ Solution

How can I change the  message template  of  DingDing , such as @ someone by DingDing bot or  change the massage type

**Comment by koen20** [comment] 2022-03-16 19:28
Duplicate of #975 and #646

**Comment by CommanderStorm** [comment] 2024-05-28 00:16
User notification was merged in https://github.com/louislam/uptime-kuma/pull/4718
The rest (templating) a duplicate of https://github.com/louislam/uptime-kuma/issues/646

this issue is resolved if I subtract the duplicate
=> closing as resolved

**Closed by CommanderStorm** 2024-05-28 00:16 UTC
Labels: feature-request, area:notifications
