### ISSUE TITLE
notification alert by voip call from the system to any social media like whatsapp, telegram, signal,...etc

### ISSUE THREAD

**Issue by karfer** [louislam/uptime-kuma#3812] opened 2023-09-28 19:17 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Problem
Some critical alerts need to be notified by voip call through a system to the client by doing any integration.

please consider it as high feature which you will be a different and best from others like zabbix...

please note that critical systems need to be notified when there is an issue immediately by such feature because email or any other notification not effective on such occasions.

### ✔️ Solution

we need the kuma server to do voip call to the client when a particular server or application goes down or not responding or latency,...

it a critical alert notification because all monitoring tools didn't introducing it, and the NOC engineers need to be notified on time.

thanks in advance

**Comment by CommanderStorm** [comment] 2023-09-29 21:41
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3295
If you agree, please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage.
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that bot's normally cannot call users:
- Telegram: https://stackoverflow.com/q/70438115
- Whatsapp/Signal does not officially support bots or sending messages programatically as far as I can tell from their docs

To prevent misscomunication: we are open to such notifiation providers, here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by CommanderStorm** [comment] 2023-12-02 00:29
As this issue is covered by https://github.com/louislam/uptime-kuma/issues/3295 and thus a duplicate I am going to close this issue in favor of the other one.

**Closed by CommanderStorm** 2023-12-02 00:29 UTC
Labels: feature-request
