### ISSUE TITLE
Configurable periods on public status page

### ISSUE THREAD

**Issue by iamtakingiteasy** [louislam/uptime-kuma#1234] opened 2022-01-29 21:13 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Currently only 24h uptime period is shown on public status page.

It is nice for immediate service availability, but does not allow to assess how stable service is being overall.

### ✔️ Solution

Add option to select which periods to display on public status page.

At least a 30-day option (same as available on dashboard) would be nice.

**Comment by koen20** [comment] 2022-02-02 14:41
Duplicate of #986

**Closed** 2023-12-03 19:12 UTC
Labels: feature-request
