### ISSUE TITLE
I need to add a timeout for when the alert generated by uptime kuma is ''DOWN" it disappears after 20 seconds

### ISSUE THREAD

**Issue by aroldo2** [louislam/uptime-kuma#3227] opened 2023-06-07 14:16 UTC
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I need the pop up when the server is "DOWN" to close automatically, would there be any simple way to make this happen????

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

ubuntu 22.04

### 🌐 Browser

firefox

**Comment by chakflying** [comment] 2023-06-07 14:27
Duplicate of #2116 and #1178, solution PR open in #2555.

When you open an issue, you should add a title describing concisely what problem your are facing.

**Comment by aroldo2** [comment] 2023-06-07 14:46
Done

**Closed** 2023-06-07 17:12 UTC
Labels: help
