### ISSUE TITLE
Auto-Pause Monitor

### ISSUE THREAD

**Issue by teyhouse** [louislam/uptime-kuma#383] opened 2021-09-11 21:22 UTC
Would it be possible to implement an option in order to pause a Monitor for a certain timespan during the day?  
For example: My Router does a Daily-Reconnect at 5am, which causes "false-alerts" on a daily basis. I would like to define something like "don't run this monitor during 05:00-05:15 am".

Thanks!

**Is it a duplicate question?**
Yes

**Info**
Uptime Kuma Version: latest
Using Docker?: Yes
OS: Ubuntu 20.04 LTS
Browser: Firefox

**Comment by chakflying** [comment] 2021-09-11 21:43
Duplicate of #191 and #204.

**Closed** 2021-09-12 03:14 UTC
Labels: enhancement
