### ISSUE TITLE
Downtime Duration in the Notification

### ISSUE THREAD

**Issue by sanjue007** [louislam/uptime-kuma#1215] opened 2022-01-24 08:09 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Please add Downtime duration in the Notification body

(Name) is now UP
**Downtime: 2 min**
Target: (IP address)[ping]
Noticed at: 2022-01-24 07:53:37 (UTC+00:00)

### ✔️ Solution

Please add Downtime duration in the Notification body

**Comment by koen20** [comment] 2022-01-24 15:38
Duplicate of #177

**Comment by CommanderStorm** [comment] 2023-07-25 14:17
@sanjue007 
I think this is a duplicate of #177 (which has #428 as a duplicate)
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-14 00:45
Duplicate of #177

**Closed by CommanderStorm** 2023-12-14 00:45 UTC
Labels: feature-request, area:monitor, area:notifications
