### ISSUE TITLE
settings option to change monitorint web-page title 

### ISSUE THREAD

**Issue by cypa** [louislam/uptime-kuma#4197] opened 2023-12-09 11:25 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

we have 2 different Uptime Kuma installations but both shows same web-page title "Uptime Kuma" but I'd like to distinguish which monitoring is alerting

### ✔️ Solution

add settings option to change web-page title

**Comment by CommanderStorm** [comment] 2023-12-09 11:40
Duplicate of #3827

**Closed by CommanderStorm** 2023-12-09 11:40 UTC
Labels: feature-request, area:core
