### ISSUE TITLE
Test for HTTP response header

### ISSUE THREAD

**Issue by kingfisher77** [louislam/uptime-kuma#4312] opened 2024-01-03 08:20 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, New Monitor, UI Feature

### 🔖 Feature description

We want to test for the presence of an HTTP response header.

### ✔️ Solution

In the user interface, we should be able to add entries for HTTP response headers that are tested for presence and/or a specific value.

For example: X-Robots tag = "noindex, nofollow"

### 📝 Additional Context

We are willing to donate to the project.

**Comment by CommanderStorm** [comment] 2024-01-03 16:35
Duplicate of https://github.com/louislam/uptime-kuma/issues/3568

=> TLDR: I think implementing this should be slotted after https://github.com/louislam/uptime-kuma/pull/3919 to save on needed effort

**Closed by CommanderStorm** 2024-01-03 16:35 UTC
Labels: feature-request
