### ISSUE TITLE
Add possibility to indicate service name and version

### ISSUE THREAD

**Issue by meaz** [louislam/uptime-kuma#4825] opened 2024-06-05 05:56 UTC
### 📑 I have found these related issues/pull requests

I'm unable to find any related issues

### 🏷️ Feature Request Type

Dashboard, Status-page

### 🔖 Feature description

I would like to be able to indicate to users that check by status page the services' name and version behind each monitoring.

### ✔️ Solution

For example, that would be nice to have that possibility to mouse over the monitoring, named let's say "Cloud" and see "Nextcloud v.21.2"

**Comment by CommanderStorm** [comment] 2024-06-05 11:33
How would we know the version information ABOUT thrid party systems? Third party systems don't follow a set standard on this one.
=> I think this part is kind of impossible unless I am missing something.

**Comment by CommanderStorm** [comment] 2024-06-05 11:36
Also a duplicate of https://github.com/louislam/uptime-kuma/issues/892

**Closed by CommanderStorm** 2024-06-05 11:36 UTC
Labels: help, area:monitor, area:status-page, type:enhance-existing

**Comment by meaz** [comment] 2024-06-05 19:04
Sorry, I wasn't clear enough: I wasn't thinking about something automatic, but something that could be manually added. At first I thought the "Description" box would be that option, but it is not being shown to visitors.

**Comment by CommanderStorm** [comment] 2024-06-05 23:39
Having a separate public description field is already tracked in another issue => am not going to reopen. Hope you understand ^^
