### ISSUE TITLE
icon with link

### ISSUE THREAD

**Issue by contramundi** [louislam/uptime-kuma#3990] opened 2023-11-07 06:21 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I would love to see an icon of the monitored service which includes a faster way to access the actual service instead of having to go into the detailed info page and click the link on the top.

it would also help with visually identifying the different services at a glance. 

### ✔️ Solution

Somewhat similar to the monitorr app where you have icons of the service to quickly tell what service it is and clicking it takes you to the actual service. 

the line itsel with the percentage and service name would show you the detail page in the dashboard.

**Comment by CommanderStorm** [comment] 2023-11-07 10:01
@contramundi 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/443
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Closed** 2023-11-07 13:09 UTC
Labels: feature-request
