### ISSUE TITLE
Show paused state in status pages

### ISSUE THREAD

**Issue by sevmonster** [louislam/uptime-kuma#4245] opened 2023-12-16 12:16 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Currently paused monitors do not display this state change in status pages. This change should be represented in status pages like it is in the dashboard UI. Either fade it out like in the dashboard, or hide the monitor completely.

### ✔️ Solution

Fade or hide paused monitors on status pages.

### ❓ Alternatives

Use maintenance windows, but that adds blue maintenance ticks to the monitor histogram and expresses a different intent ("the service is down for maintenance" vs "the service is not currently being monitored on purpose").

### 📝 Additional Context

#4247 would resolve this FR, but in a different way.

**Comment by CommanderStorm** [comment] 2023-12-16 13:19
I have integrated some of your alternatives into https://github.com/louislam/uptime-kuma/issues/2287
Otherwise this is a duplicate of said issue => closing as duplicate

**Closed by CommanderStorm** 2023-12-16 13:19 UTC
Labels: feature-request, area:status-page

**Comment by sevmonster** [comment] 2023-12-16 13:27
Sorry, I did not see that issue.
