### ISSUE TITLE
Notification time zone I would like to refer to the general settings.

### ISSUE THREAD

**Issue by Vampire-V** [louislam/uptime-kuma#1539] opened 2022-04-22 09:23 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Notification time zone I would like to refer to the general settings.

![image](https://user-images.githubusercontent.com/25393048/164677208-e5bb4e84-a882-4ced-a52b-8f517ecfc5b5.png)

![image](https://user-images.githubusercontent.com/25393048/164677303-aff45905-a869-47c8-a142-58f35d47716e.png)

### ✔️ Solution

Notification time zone I would like to refer to the general settings.

**Comment by Computroniks** [comment] 2022-04-22 14:28
This seems more of a bug than a feature. Or at least an issue with the way that the notification system handles time. However, this might be quite lengthy to fix as it seems most notification providers directly use `Date.now()` for their time instead of using the setting.

**Comment by iamwak** [comment] 2022-05-07 02:25
I also found this problem. Whether it is setting the container time zone or the time zone in the Uptime Kuma settings, the time zone in the alarm is still the default. I hope the developer can solve this problem as soon as possible.

**Comment by louislam** [comment] 2022-05-09 04:52
Duplicate of #40

**Closed by louislam** 2022-05-09 04:52 UTC
Labels: feature-request
