### ISSUE TITLE
Monitor "Domain valid until"

### ISSUE THREAD

**Issue by theme1256** [louislam/uptime-kuma#3644] opened 2023-08-25 12:26 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, Other

### 🔖 Feature description

Just as the monitor ads information about when a SSL-cert is going to expire, ad one that monitors when the base domain is going to expire.
It should be possible to do on most domains using whois.

### ✔️ Solution

Add an option on https monitors to monitor to domain too.

**Comment by CommanderStorm** [comment] 2023-08-25 14:41
This is a duplicate of https://github.com/louislam/uptime-kuma/issues/944 and why this is not a simple task
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-08-25 19:16 UTC
Labels: feature-request
