### ISSUE TITLE
Alternative to issue history

### ISSUE THREAD

**Issue by Appoxo** [louislam/uptime-kuma#2943] opened 2023-03-18 12:28 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Ability to change the view of historical issues. Currently there is only a list of
```
Service Down Date #\1
Service Up Date #\1
Service Down Date #\2
Service Up Date #\2
Service Down Date #\3
Service Up Date #\3
```

### ✔️ Solution

A github like activity overview for daily/weekly/monthly/yearly for downtime (the grey dark/light green grid).
A live example for example for Reddit: https://www.redditstatus.com/uptime
![image](https://user-images.githubusercontent.com/17850993/226106070-a482663b-7b63-4e97-80ad-1492812b4726.png)
This would make it more readable and create a better understanding how often a service was not responsive

**Comment by CommanderStorm** [comment] 2023-05-25 10:31
@Appoxo is this a duplicate of #1984?
If not, please make this issue less similar by editing your issue.

**Comment by Appoxo** [comment] 2023-05-25 10:43
> @Appoxo is this a duplicate of #1984?
> If not, please make this issue less similar by editing your issue.

Can be considered a duplicate. Thank you :)

**Comment by CommanderStorm** [comment] 2023-05-25 10:59
> Can be considered a duplicate. Thank you :)

Could you then please close this issue? ^^

**Closed** 2023-06-11 17:17 UTC
Labels: feature-request

**Comment by CommanderStorm** [comment] 2023-06-11 20:12
Thanks ❤️
