### ISSUE TITLE
Ping intervals more faster

### ISSUE THREAD

**Issue by louloudem** [louislam/uptime-kuma#5057] opened 2024-08-27 09:44 UTC
### 📑 I have found these related issues/pull requests

I'm currently monitoring several virtual reality headsets, 12 to be exact, and I'm opening 12 Dos command windows to “ping -t” each ip. But I love your interface, except that 20 seconds between each ping is far too long for my purposes. Unless you know of another program that can do it? 

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

Is it possible to have a faster ping analysis? I'd like to have the same functionality as the Dos ping command in Windows, i.e. the “ping -t” command, which analyzes every second of a network, but on several computers at the same time.

### ✔️ Solution

I'm currently monitoring several virtual reality headsets, 12 to be exact, and I'm opening 12 Dos command windows to “ping -t” each ip. But I love your interface, except that 20 seconds between each ping is far too long for my purposes. Unless you know of another program that can do it?

**Comment by CommanderStorm** [comment] 2024-08-28 03:20
What are you really trying to monitor.
If its uptime, why is 20s not enough?

The reason why this is a limit is that we currently (v1.x) have severe performance limits and allowing 20x the heartbeats fills the perf-budget way too fast.
v2.0 switches to aggregated tables and should resolve the limits. See #4500 what is left to do and how to get involved.

To merge https://github.com/louislam/uptime-kuma/pull/1740, somebody needs to rebase said PR and then test if the performance issues have been resolved.

I am going to close this as a duplicate of https://github.com/louislam/uptime-kuma/issues/1645
You can find alternatives and further rationale in that thread ^^

**Closed by CommanderStorm** 2024-08-28 03:20 UTC
Labels: help
