### ISSUE TITLE
Custom notification content

### ISSUE THREAD

**Issue by yunsimple** [louislam/uptime-kuma#4242] opened 2023-12-15 12:19 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

If it is a public notification, is it possible to hide key information such as ip address, port.

The notification content can be set as the name of the notification content, or you can customize a notification content.

### ✔️ Solution

The content of the notification can be customized.

**Comment by CommanderStorm** [comment] 2023-12-15 12:28
Duplicate of #1793

**Closed by CommanderStorm** 2023-12-15 12:28 UTC
Labels: feature-request, area:monitor, area:notifications

**Comment by CommanderStorm** [comment] 2023-12-15 12:30
Note that templating is tracked in #646
