### ISSUE TITLE
Suggestion：It's even better if the list monitored on the left has a grouping function and buttons

### ISSUE THREAD

**Issue by zbin-x** [louislam/uptime-kuma#3358] opened 2023-07-05 02:28 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It's even better if the list monitored on the left has a grouping function and buttons
Although there is Status Pages, it is a second-level menu without the convenience of a first-level tag group

### ✔️ Solution

Add group labels to monitoring items and add label groups to the list. It has the filtering function and can add unlimited label groups

**Comment by justinkruit** [comment] 2023-07-05 08:41
And also the ability to filter based on status, so you can easily see all the websites with errors or the ones in maintenance.

**Comment by CommanderStorm** [comment] 2023-07-05 09:14
@zbin-x
Is this a duplicate of Fixes https://github.com/louislam/uptime-kuma/issues/1134 or https://github.com/louislam/uptime-kuma/issues/1585, which has the associated PR https://github.com/louislam/uptime-kuma/pull/3312
If yes, please close this issue (duplicates only create imortal zombies and are really hard to issue manage).
If no, what makes this issue distinct enough from the other issues to require another issue?

**Comment by CommanderStorm** [comment] 2023-07-16 14:03
@louislam https://github.com/louislam/uptime-kuma/pull/3312 has been merged 
⇒ Could you close this issue too? ^^

(We forgot to add `Resolves #3358` to said PR 😅)

**Closed** 2023-07-16 14:11 UTC
Labels: feature-request
