### ISSUE TITLE
Uptime Agent

### ISSUE THREAD

**Issue by Surgical17** [louislam/uptime-kuma#3030] opened 2023-04-05 11:24 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Create a Agent version of Uptime Khuma. It can be installed and look the same to be accessed locally but the monitor data it gathers can be sent to a Uptime instance outside of the local network. This instance will then either sync the local monitors or accept data from them and from their notifications can be sent out.

Use case is for setups where there is VM's on the local network, the local network can access the internet, but you are unable to do any port forwarding to connect externally to that local instance. So the local network will stay secure and you will still be able to manage the monitors externally. (Like Portainer Agent, or a RMM agent)

### ✔️ Solution

Create a Uptime agent that can be installed on a local network, able to access this instance UI via the local network but the data it gathers gets sent via internet to an external Uptime instance that can then manage the monitors etc.

**Comment by FrankSanabria** [comment] 2023-04-08 21:08
Maybe using push request? https://github.com/louislam/uptime-kuma/issues/528

**Comment by zimbres** [comment] 2023-07-06 15:29
Take a look: https://github.com/zimbres/UptimeKumaRemoteProbe

**Comment by louislam** [comment] 2023-09-19 10:11
Duplicate of #528

**Closed by louislam** 2023-09-19 10:11 UTC
Labels: feature-request
