### ISSUE TITLE
Blank screen when accessing Uptime Kuma through FortiGate SSL VPN.

### ISSUE THREAD

**Issue by tompjep** [louislam/uptime-kuma#727] opened 2021-10-16 19:12 UTC
Tried to access Uptime Kuma through Fortigate SSL VPN but only get blank screen. Page title and favicon is only thing working

**Comment by tompjep** [comment] 2021-10-16 19:14
Tried to access Uptime Kuma via Apache reverse proxy and directly via ip and port. Both blank screen.

**Comment by louislam** [comment] 2021-10-17 02:07
Duplicate of #632

**Closed by louislam** 2021-10-17 02:07 UTC
Labels: help
