### ISSUE TITLE
Decrease minimum seconds

### ISSUE THREAD

**Issue by m-primo** [louislam/uptime-kuma#2894] opened 2023-03-08 00:41 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Decrease minimum seconds in **Heartbeat Interval** & **Retries** into like 5 seconds instead of 20.

[https://imgur.com/a/oFt4mla](Check this image)

Please note that it's working on the **backend**, meaning you can do **inspect elements** and decrease the seconds into any number and it'll work, so the edit is only in the `min` attribute in HTML.

### ✔️ Solution

> so the edit is only in the `min` attribute in HTML.

**Comment by louislam** [comment] 2023-03-08 05:11
Duplicate of #2049

**Closed by louislam** 2023-03-08 05:11 UTC
Labels: feature-request
