### ISSUE TITLE
3.4 is no longer maintained and not recommended for usage due to the number of issues

### ISSUE THREAD

**Issue by only4freedom** [louislam/uptime-kuma#1533] opened 2022-04-21 06:10 UTC
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

3.4 is no longer maintained and not recommended for usage due to the number of issues

### 🐻 Uptime-Kuma Version

1.14.1

### 💻 Operating System and Arch

ubuntu 20

### 🌐 Browser

google chrome

**Comment by louislam** [comment] 2022-04-21 06:26
Is it a warning during npm install? Just ignore those warnings.

**Comment by mathiskir** [comment] 2022-04-23 17:49
> 3.4 is no longer maintained and not recommended for usage due to the number of issues

In future issues please provide more informations than just a simple error message without any context.
Otherwise we need to guess what the problem is.
If your problem is resolved, you can also close this issue.

**Closed** 2022-04-24 14:59 UTC
Labels: help
