### ISSUE TITLE
Permit Father-son check chain

### ISSUE THREAD

**Issue by pabloalcantara** [louislam/uptime-kuma#2114] opened 2022-09-22 01:28 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

Some time you monitor more than one service in the same server. But if the server is down, all services comes down too, and many notifications happens.

### ✔️ Solution

So if I declare that Service A and Service B is on the Server Y, and the Server Y is Down, it only sends the notifications for The Server Y.

**Comment by danmed** [comment] 2022-09-23 20:15
To further expand this.. rather than limiting it to just a server containing services.. if i'm monitoring my router (from a remote source) and it's down.. then i'd like to be able to not get notifications for everything else too..

**Comment by CommanderStorm** [comment] 2023-12-07 14:31
Closing as duplicate of https://github.com/louislam/uptime-kuma/issues/1089

**Closed by CommanderStorm** 2023-12-07 14:31 UTC
Labels: feature-request
