### ISSUE TITLE
Automatic update of Status Pages

### ISSUE THREAD

**Issue by mrwee** [louislam/uptime-kuma#2441] opened 2022-12-20 09:27 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Right now, status of monitored devices, is only automatically updated on the Dashboard. If I configure a status page with same monitored devices, this page is not updated unless I press F5.

Status page:
![image](https://user-images.githubusercontent.com/6720774/208633179-f109c36b-f0cb-4617-836f-e58b77f58b8e.png)

Dashboard:
![image](https://user-images.githubusercontent.com/6720774/208633345-20b3cfc8-1cd6-41af-b022-4c3f1f13005c.png)

### ✔️ Solution

Uptime Kuma should also update all monitored devices on the status pages, so the view reflects up/down status in realtime.

### ❓ Alternatives

Right now I can only use the Dashboard to view realtime status, but the status page is more clean for quick glance.

### 📝 Additional Context

Tested on Firefox 108.0.1 and Edge 108.0.1462.54

**Comment by AndreKotze** [comment] 2022-12-20 09:57
If you're using Chrome then you can download the "Easy Auto Refresh" extension - I use it for all my auto-refresh needs.

![image](https://user-images.githubusercontent.com/4725308/208638508-949e0d2b-0c58-4192-973e-b27c31b03269.png)

**Comment by mrwee** [comment] 2022-12-20 10:03
@AndreKotze Thanks for the suggestion, however I'm a Firefox user :). 
Also, since Uptime Kuma auto-refreshes the dashboard, I also think it should do the same with status pages.

**Comment by louislam** [comment] 2022-12-22 06:59
Duplicate of https://github.com/louislam/uptime-kuma/issues/978

**Closed by louislam** 2022-12-22 06:59 UTC
Labels: feature-request
