### ISSUE TITLE
Certificate-based Mutual TLS Authentication

### ISSUE THREAD

**Issue by caotangdaiduong** [louislam/uptime-kuma#1113] opened 2022-01-02 01:46 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Mutual TLS, or mTLS for short, is a method for mutual authentication. mTLS ensures that the parties at each end of a network connection are who they claim to be by verifying that they both have the correct private key. The information within their respective TLS certificates provides additional verification.

### ✔️ Solution

Client Certificate use data with cert and private key and prekey

**Comment by chakflying** [comment] 2022-01-03 02:28
Duplicate of #139 and #189

**Closed** 2023-01-05 11:14 UTC
Labels: feature-request
