### ISSUE TITLE
Monitor Hierarchy to share setup.

### ISSUE THREAD

**Issue by mcg1103** [louislam/uptime-kuma#5219] opened 2024-10-18 17:40 UTC
### 📑 I have found these related issues/pull requests

I searched for "extend existing monitors" and "base monitor" but did not find any other feature requests. 

### 🏷️ Feature Request Type

Maintenance

### 🔖 Feature description

Most of monitors on my system are the same except the URL and Friendly Name.  I have been tweaking other setting to reduce false positives yet get notified of an outage as quick as possible.   Would be cool to have a base monitor that you could change and the change would be applied to the other monitors that are based off that monitor.  

### ✔️ Solution

 Like the clone but the system maintains the connection between the two.  Each field can either get a new value or get the value from the base monitor.

**Comment by CommanderStorm** [comment] 2024-10-20 14:01
Sharing state as you are requesting is pretty error-prown and I don't think we should support this.

Something like the following seems much simpler in comparison  (no tangling of monitors to some different system as suggested here).:
- #1323 
- #455 

Duplicate of 
- #937

**Closed by CommanderStorm** 2024-10-20 14:01 UTC
Labels: feature-request
