### ISSUE TITLE
Pinned telegram message showing the overall status

### ISSUE THREAD

**Issue by imclint21** [louislam/uptime-kuma#3877] opened 2023-10-11 15:38 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Hi,

would be nive to have the possibilty to pin a telegram notification.

Cheers

### ✔️ Solution

N/a

**Comment by imclint21** [comment] 2023-10-11 18:15
Telegram propose the possiliby to pin a message, if you have a status channel with many notifications it could be nice to pin uptime kuma notifications.

<img width="626" alt="image" src="https://github.com/louislam/uptime-kuma/assets/5221349/fc8833f1-704a-44cf-bd1f-4ee300988d21">

**Comment by rezzorix** [comment] 2023-10-11 18:45
That cannot be an uptime-kuma feature as it is a feature on telegram side.  

It works only in group chats and you can pin messages when you are the admin or owner of the group. 

The only way it could work is if you get the bot to join one of the groups you own / are admin in and then you can pin a single message. 

This however will only pin this single message, not subsequent messages.

**Comment by imclint21** [comment] 2023-10-18 17:53
<img width="559" alt="image" src="https://github.com/louislam/uptime-kuma/assets/5221349/97f3ea60-d927-403a-89e7-a1570f1d3620">

I don't think its difficult to pin the last message sent to telegram.

**Comment by CommanderStorm** [comment] 2023-12-13 15:55
Closing as a duplicate of #576 as said PR has more 👍🏻

**Closed by CommanderStorm** 2023-12-13 15:55 UTC
Labels: feature-request, area:notifications
