### ISSUE TITLE
Receiving SSL certificate expiry notifications when root certificate expiry date is negative

### ISSUE THREAD

**Issue by RappyTV** [louislam/uptime-kuma#3982] opened 2023-11-06 00:15 UTC
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I receive emails everytime I create/edit a monitor or I start/restart my Uptime Kuma saying that the root CA certificate expires in negative days
![image](https://github.com/louislam/uptime-kuma/assets/72705182/6c7b813a-46f1-4c1d-881d-6683b6fbed1f)
This also applies for discord notifications:
![image](https://github.com/louislam/uptime-kuma/assets/72705182/3d642d26-c88b-492b-a9f3-2bd5ece04390)

### 👟 Reproduction steps

+ Create an `HTTP(s)` monitor with a url pointing to a website with a valid SSL certificate
+ Enable SSL expiry notifications
+ Save

### 👀 Expected behavior

Nothing

### 😓 Actual Behavior

I receive emails about my root CA certificate expiring

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 20.04 x64

### 🌐 Browser

Opera GX

### 🟩 NodeJS Version

17.9.1

**Comment by chakflying** [comment] 2023-11-06 07:03
Duplicate of #3323, fix will be released in `1.23.4`.

**Comment by RappyTV** [comment] 2023-11-06 10:16
thanks a lot!

**Closed** 2023-11-06 12:48 UTC
Labels: bug
