### ISSUE TITLE
Reports with Days instead of interval

### ISSUE THREAD

**Issue by chmichael** [louislam/uptime-kuma#5005] opened 2024-08-10 11:51 UTC
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

Please add Daily Reports like the screen shot and status icons with descriptions.

![εικόνα](https://github.com/user-attachments/assets/a0147504-c185-4b63-bb89-e9e65059d9ce)

### ✔️ Solution

Bars will show days instead of the current interval.

**Comment by CommanderStorm** [comment] 2024-08-10 19:23
Duplicate of https://github.com/louislam/uptime-kuma/issues/1888
=> Closing as such

**Closed by CommanderStorm** 2024-08-10 19:23 UTC
Labels: feature-request, area:status-page
