### ISSUE TITLE
Notification rules

### ISSUE THREAD

**Issue by JaJe92** [louislam/uptime-kuma#3634] opened 2023-08-23 08:15 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

If I have multiple networking devices such as switches or routers monitored, each of these have it's own devices that I also monitor, I want to setup a notification rules that whenever one of these switches or routers goes down, to notify me about these routers only and not get spammy notification that all devices behind that switch/router is not responding.

Why not, adding conditional notifications too, If x and y is true/false then notify, else ignore.

### ✔️ Solution

Select list of devices and add as 'child' to 'parent' device, so whenever the 'parent' device goes down, no notification needed to receive for 'child' devices too.

**Comment by CommanderStorm** [comment] 2023-08-23 11:42
An alternative is to use [Grafana Oncall](https://grafana.com/products/cloud/oncall/) for your escalation needs (see #2783 => this will probably be avaliable in `v2.0`)

Oncall includes fully customisable routing of allerts
![image](https://github.com/louislam/uptime-kuma/assets/26258709/0d6fdce9-f68e-4aff-a50e-39071dc84e74)


Related https://github.com/louislam/uptime-kuma/issues/1315

I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3585 / https://github.com/louislam/uptime-kuma/issues/1233 / https://github.com/louislam/uptime-kuma/issues/1562 and partially https://github.com/louislam/uptime-kuma/issues/1137
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by stepech** [comment] 2023-09-10 16:30
Why is this issue mentioned in v1.23.1 release notes? @louislam perhaps a typo?

**Comment by CommanderStorm** [comment] 2023-12-08 22:46
@JaJe92 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/508 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-08 22:46 UTC
Labels: feature-request, area:notifications
