### ISSUE TITLE
Group Alerts in folders and tags..

### ISSUE THREAD

**Issue by projx** [louislam/uptime-kuma#288] opened 2021-08-29 02:23 UTC
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to see 2 features added:
1) Allow Monitors to be sorted into Folders, with a TreeView, where nodes can be closed/opened
2) Add a Tag(s) attribute to each Monitor, so 1 or many tags can be added, that add a search box or tags-cloud to the main dashboard, which would filter the shown monitors. possibly allowing the filtering to be persistant.

**Describe alternatives you've considered**
None

**Additional context**
The intent is to provide means of organising monitorings, and how they are showin

**Comment by louislam** [comment] 2021-08-29 03:28
Possibly duplicate of #12 #278

**Closed by louislam** 2021-08-29 03:28 UTC
Labels: enhancement
