### ISSUE TITLE
DNS monitor check the response

### ISSUE THREAD

**Issue by Heshmatkhah** [louislam/uptime-kuma#4001] opened 2023-11-09 09:20 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, Other

### 🔖 Feature description

An attacker in my ISP hijacks DNS queries and returns `10.10.34.34` for some critical domains, such as banking systems.

I want to set my DNS monitor to check for the response of this query and if the response is equal to `10.10.34.34`, assume it as down.

### ✔️ Solution

If there be an `answere section` for DNS monitors, the combination of `upsideDown` will do the job
It also makes it possible to monitor for specific responses.

**Comment by CommanderStorm** [comment] 2023-11-09 09:37
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/432
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this
The DNS monitor is located here: https://github.com/louislam/uptime-kuma/blob/master/server/monitor-types/dns.js

**Closed** 2023-11-09 09:40 UTC
Labels: feature-request
