### ISSUE TITLE
Static/ manual Uptime Monitor with no Uptime Check

### ISSUE THREAD

**Issue by Realtox** [louislam/uptime-kuma#1359] opened 2022-03-06 14:38 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature

### 🔖 Feature description

I think i would be nice to have a function to disable the automatic uptime checks from UptimeKuma for example a site from a organisation and the admin can set the status manuelly.

Another thing is a incident log or multiple incidents on one site or a subsite for only incidents and planed incidents.

### ✔️ Solution

For the monitor without a uptime check you only must add on the dropdown action another field for "Disable Checks" and after this, a function to set the current state of the object manuelly.

**Comment by CommanderStorm** [comment] 2023-12-07 17:27
Closing as a duplicate of #475

> Another thing is a incident log or multiple incidents

This is tracked in #862

**Closed by CommanderStorm** 2023-12-07 17:27 UTC
Labels: feature-request, area:monitor
