### ISSUE TITLE
Manual Monitor

### ISSUE THREAD

**Issue by dabenzel** [louislam/uptime-kuma#2715] opened 2023-02-03 09:10 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

I want a Monitor that I can add, which status can be changed manually.

Sometimes you can't monitor several services by the currently available monitors in Uptime Kuma, but for having my users also notified that a service is down, I want to create a monitor which can be turned "offline" manually

### ✔️ Solution

Add a monitor type "manual"
When editing this monitor, there is a switch "online"/"offline". When the switch is offline and the monitor is saved, the service appears as offline for the time until the switch is turned back online again.

**Comment by rezzorix** [comment] 2023-02-04 03:33
Since you want it manual…..

Setup a Ping Monitor to IP 127.0.0.1 ….

Whenever you want it to switch to offline change the IP to 127.0.0.999 

As this IP does not (and cannot exist) the monitor will switch to “is down” right away after saving.

**Comment by cyril59310** [comment] 2023-02-05 00:54
or configure a Ping monitor on IP 127.0.0.1 and use this option in the monitor editor

![image](https://user-images.githubusercontent.com/70776486/216795791-7f98e473-1db9-4b48-ae4a-ac54f6f557e5.png)

**Comment by CommanderStorm** [comment] 2024-04-15 01:58
Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/475

I have integrated the relevant parts of the issue

**Closed** 2024-04-15 01:58 UTC
Labels: feature-request, area:monitor
