### ISSUE TITLE
Rest API or API for retrieving monitors and statusses

### ISSUE THREAD

**Issue by hypherionmc** [louislam/uptime-kuma#644] opened 2021-10-10 23:46 UTC
**Is it a duplicate question?**
Not really a duplicate, but #541 contains a similar request

**Is your feature request related to a problem? Please describe.**
I want to have a way to pull monitors and their status from some kind of API to integrate them with either a discord bot or some other place. Additionally such an API would make it possible to make mobile applications

**Describe the solution you'd like**
Preferably a REST api with a JSON format, or atleast the possibility to add your own API

**Comment by deefdragon** [comment] 2021-10-11 00:39
Basically a duplicate of #118, where, as mentioned, some of the API is already public but just lacking documentation, and the rest is missing a way to generate an API key.

`<host>/api/status-page/monitor-list`
`<host>/api/status-page/heartbeat`

The above two endpoints are public and provide the requested monitors and their statuses for the monitors displayed on the status page if that is all you need.

**Comment by louislam** [comment] 2021-10-11 05:06
Agree, focus in one post. Duplicate of #118.

**Closed by louislam** 2021-10-11 05:06 UTC
Labels: enhancement

**Comment by hypherionmc** [comment] 2021-10-11 09:28
My apologies. That one didn't show up in the search results. Thank you
