### ISSUE TITLE
Monitor docker container status

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#1587] opened 2022-04-29 06:16 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Add the ability to monitor the status of docker containers to ensure they are running/healthy or down/exited

### ✔️ Solution

Be able to use the docker API, accessing /var/run/docker.sock to determine and monitor container status

**Comment by gaby** [comment] 2022-04-29 13:18
This is done via #1183, sadly it hasnt been merged

**Comment by louislam** [comment] 2022-06-21 07:24
Duplicate of #1020

**Closed by louislam** 2022-06-21 07:24 UTC
Labels: feature-request
