### ISSUE TITLE
Read URLs from a configuration file 

### ISSUE THREAD

**Issue by NathanD14** [louislam/uptime-kuma#4733] opened 2024-05-02 14:58 UTC
### 📑 I have found these related issues/pull requests

There is a request for an API ([Issue #118](https://github.com/louislam/uptime-kuma/issues/118)) but apart from that did not find anything related to a file.

### 🏷️ Feature Request Type

API / automation options, Other

### 🔖 Feature description

When creating a monitor for a few URLs, the UI is easy. But when that has to be done for a lot it becomes a bit of a problem. I want to import a host of URLs that I want to monitor

### ✔️ Solution

Import or allow reading of a file (csv) with a list of URLs - 1 on each line, with it's configuration mentioned on the same line in a fixed format.
e.g:
```
URL1, monitor type, name, heartbeat, etc.
URL2, monitor type, name, heartbeat, etc.
```

Alternatively, use the UI to set the monitoring details and only import the list of URLs that follow that configuration.

**Comment by CommanderStorm** [comment] 2024-05-03 14:20
This is a duplicate of:
- https://github.com/louislam/uptime-kuma/issues/1354
- https://github.com/louislam/uptime-kuma/issues/1190

And related to:
- https://github.com/louislam/uptime-kuma/issues/956
- https://github.com/louislam/uptime-kuma/issues/1323

=> closing as a duplicate

**Closed by CommanderStorm** 2024-05-03 14:20 UTC
Labels: feature-request
