### ISSUE TITLE
create another account

### ISSUE THREAD

**Issue by W3T3R4NN** [louislam/uptime-kuma#1255] opened 2022-02-03 14:29 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

another users can create another acount in website. This user can see their own uptimes and can create dashboard

### ✔️ Solution

another users can create another acount in website. This user can see their own uptimes and can create dashboard

**Comment by Appoxo** [comment] 2022-02-03 19:00
+1

**Comment by darks00ul** [comment] 2022-02-13 06:09
+1

**Comment by thompol** [comment] 2022-03-05 17:51
Possible duplicate of #128

**Comment by adiastra** [comment] 2022-08-26 18:45
I am unclear if this has been implemented but I would really like this feature. Aven basic multi user functionality would be a great place to start

**Closed** 2023-12-03 15:15 UTC
Labels: feature-request
