### ISSUE TITLE
Allow custom Slack notification template

### ISSUE THREAD

**Issue by sauravkoli31** [louislam/uptime-kuma#4640] opened 2024-04-01 15:39 UTC
### 📑 I have found these related issues/pull requests

Cant find any related issue

### 🏷️ Feature Request Type

Change to existing notification-provider

### 🔖 Feature description

Allow to add custom notification template for Slack notifications.

### ✔️ Solution

A Textbox where a template for slack message can be added. A clear and concise doc to use the appropriate variables and a verification process to allow only verified templates that have proper variables used.

**Comment by CommanderStorm** [comment] 2024-04-01 21:59
Closing this as a duplicate of https://github.com/louislam/uptime-kuma/issues/646

**Closed by CommanderStorm** 2024-04-01 21:59 UTC
Labels: feature-request
