### ISSUE TITLE
BulkActions

### ISSUE THREAD

**Issue by ConradoP** [louislam/uptime-kuma#2934] opened 2023-03-15 15:27 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

 Bulk Actions

### ✔️ Solution

Good morning, please could you include BulkActions for url import/export and contact alert changes?

**Comment by magnusviri** [comment] 2023-05-10 21:36
I would love this feature as well. I was using the backup feature by modifying the backup and then restoring the modification, but with a lot of monitors, I haven't been able to get it to "restore".

**Comment by CommanderStorm** [comment] 2023-07-27 21:56
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/455
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-04 18:38
@ConradoP 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #455 or #1323 as there is no functional difference
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-04 18:38 UTC
Labels: feature-request
