### ISSUE TITLE
SNMP Support

### ISSUE THREAD

**Issue by irtaza9** [louislam/uptime-kuma#4427] opened 2024-01-27 10:37 UTC
### 📑 I have found these related issues/pull requests

⚠️ Please verify that this feature request has NOT been suggested before.
 I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New monitor

### 🔖 Feature description

To be able to check if a certain SNMP OID has a given String/Value and reached a certain Threshold

### ✔️ Solution

I have several SNMP Devices like Router / Printer / Switches and Servers and i want to Check Toner / Harddisk consumtion / CPU Utilisation via SNMP Host Ressources MIB oder Printer MIB

### ❓ Alternatives

Check the Values manual via SNMPWALK / SNMPGET Unix/Linux CLI

**Comment by chakflying** [comment] 2024-01-27 11:12
Duplicate of #1675

**Closed** 2024-01-27 11:12 UTC
Labels: feature-request
