### ISSUE TITLE
期望新增多用户功能

### ISSUE THREAD

**Issue by dockercore** [louislam/uptime-kuma#3911] opened 2023-10-18 07:42 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

期望新增多用户功能

### ✔️ Solution

期望新增多用户功能

### ❓ Alternatives

期望新增多用户功能

### 📝 Additional Context

# 期望新增多用户功能

**Comment by CommanderStorm** [comment] 2023-10-18 08:35
Translation According to deepl:
> Expect new multi-user functionality

@dockercore 
I think this is a duplicate of #181 
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Comment by dockercore** [comment] 2023-10-18 10:02
OK

**Closed** 2023-10-18 10:04 UTC
Labels: feature-request
