### ISSUE TITLE
Some monitors stuck on Pending state, work after manually restarting monitor

### ISSUE THREAD

**Issue by chris-ard** [louislam/uptime-kuma#736] opened 2021-10-17 23:18 UTC
**Is it a duplicate question?**
No, I don't think so.

**Describe the bug**
Firstly, thanks for all the hard work on this tool. It has been pretty great so far and hopefully will scale pretty well once we can work out some minor bugs.

One little issue we've had again recently is that some of our monitors get stuck in a Pending state overnight. Looks to be random, but I'd guess that maybe too many pings might try to run at once and something is causing some of them to get stuck and be forgotten. When stuck, it behaves pretty much as a paused monitor but in the Pending state, so nothing tracked on the timeline and no new checks. Server resources appear to be okay, so it doesn't seem to be an issue due to lack of CPU or memory.

The settings for all monitors at this stage are 1 min check intervals, 2 retries.

**To Reproduce**
This happens randomly and is likely to do with how scheduled checks are handled. I have ~40 monitors at the time of writing, both TCP and HTTPS checks. I would guess a potential resource bottleneck (or failed response) is not being handled properly, and instead of executing, it remains in either an error state or missed entirely. If paused and started manually, it continues to track as normal from the current time.

**Expected behavior**
If a monitor cannot run, misses it's schedule, or is non-responsive for a period of time, terminate / restart it and perhaps either 1) notify that a monitor failed to run and/or 2) have an option of whether or not to be notified if a monitor fails to run.

**Info**
Uptime Kuma Version: 1.8.0
Using Docker?: Yes
OS: Ubuntu LTS 20.04
Browser: Chrome latest

**Screenshots**
https://imgur.com/a/kLt2vDw

**Comment by louislam** [comment] 2021-11-04 10:10
Added `error.log` in /app/data/ and improved error handling in 1.10.0.

Open a new issue if the problem is still presented.

**Comment by louislam** [comment] 2021-11-07 12:32
Omg, the problem finally hit me.

Symptoms:
All HTTPS monitors that are using Cloudflare was stopped working.
All HTTP monitors that are HTTP or Let's encrypt are working fine.
TCP Ping or ping are working fine.

There is no error, I suspect that those monitors entered a strange state and never end.

**Comment by louislam** [comment] 2021-11-08 06:33
I think I found the issue, parseCertificateInfo could possibly be in dead loop for some edge cases. Trying to fix it.

https://github.com/louislam/uptime-kuma/blob/c92153c97ed151c9759ebe63ef22d2821e5d115e/server/util-server.js#L202-L225

**Comment by chakflying** [comment] 2021-11-08 09:20
I did think about the possibility of a loop with length > 2, but dismissed it as too unlikely. Turns out it's pretty important as it could cause DOS. Good catch.

**Comment by louislam** [comment] 2021-11-08 10:13
Released 1.10.1, mainly for this issue.

The issue is really hard to be reproduced. Instead, I created some unit tests to provide that it is no more dead loop.

More details:
https://github.com/louislam/uptime-kuma/commit/41a6d1b701e40c8aa2d3eae97dd56f7480c1109d

**Comment by MrT3acher** [comment] 2022-12-23 17:44
Hi,
I have a similar problem.
Some of my monitors was stuck for one month and I didn't realized that because the status is Up. But the last heartbeat is for one month ago.
this is the logs (there is a lot more like this):
SQLITE_BUSY
![image](https://user-images.githubusercontent.com/34602006/209378628-01ce6daf-ac99-4b57-af94-9ddd307ef63e.png)
and this:
![image](https://user-images.githubusercontent.com/34602006/209378833-66110fec-0e6b-4af7-a1b7-c95497016890.png)

**Comment by CommanderStorm** [comment] 2023-07-28 01:11
@chris-ard
The issue which caused this was either solved 
- in `v1.10.1` or
- somewhere on the way
- will be in `v1.23.0` as a lot of performance fixes like https://github.com/louislam/uptime-kuma/pull/3380 and https://github.com/louislam/uptime-kuma/pull/2800 have gone into recent versions.
  There are still some proposals out there to fix large-monitor counts ( https://github.com/louislam/uptime-kuma/issues/3286, https://github.com/louislam/uptime-kuma/pull/3463 and  https://github.com/louislam/uptime-kuma/pull/3443), but these mostly respond to newer (⇒ more relevant) feedback.

=> I think this issue can be safely closed.

**Comment by CommanderStorm** [comment] 2023-12-08 12:48
> @chris-ard The issue which caused this was either solved
> 
> * in `v1.10.1` or
> * somewhere on the way
> * will be in `v1.23.0` as a lot of performance fixes like [Feat: Run incremental_vacuum and optimize #3380](https://github.com/louislam/uptime-kuma/pull/3380) and [[Experiment] Use incremental vacuum to speed up delete? #2800](https://github.com/louislam/uptime-kuma/pull/2800) have gone into recent versions.
>   There are still some proposals out there to fix large-monitor counts ( [Improve sqlite handling #3286](https://github.com/louislam/uptime-kuma/issues/3286), [Perf: Fully batch sendImportantHeartbeatList #3463](https://github.com/louislam/uptime-kuma/pull/3463) and  [Fix: Prevent race condition in showing toast message #3443](https://github.com/louislam/uptime-kuma/pull/3443)), but these mostly respond to newer (⇒ more relevant) feedback.
> 
> => I think this issue can be safely closed.

Closing as resolved due to above rationale

**Closed by CommanderStorm** 2023-12-08 12:48 UTC
Labels: bug, High, area:monitor
