### ISSUE TITLE
Notification Trigger Options for Up or Down Status

### ISSUE THREAD

**Issue by zluckytraveler** [louislam/uptime-kuma#4010] opened 2023-11-11 08:47 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

An option to select notification triggers for when a monitor status is either Up, Down, or both. 

### ✔️ Solution

Currently as it is, you will receive notifications if a monitor status goes up and down. I'd like for there to be an option where you can choose the notification trigger to be either up, down, or both for the status.

This could possibly be implemented with a checkbox selector to choose the trigger choice of Up or Down, and selecting both checkboxes would allow for both. This could be either a global setting in notification settings or possibly set per monitor to give users more control over each monitor's notification individually.

If implemented, due to the already widely used default of both up and down being triggered, in an update it could be defaulted to this setting, so it does not interfere with everyone's already pre-defined settings.

### 📝 Additional Context

I personally only need to know when a monitor goes down, so I can address the issue fixing it. Obviously as I am the one who is fixing it, I do not need another subsequent notification telling me it's back up. I also utilize text notification which is charged per text sent, so this would also help reduce the fees I have to pay for non-essential notifications.

**Comment by CommanderStorm** [comment] 2023-11-11 13:56
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3585
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Closed** 2023-12-03 14:52 UTC
Labels: feature-request
