### ISSUE TITLE
Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by kfra71** [louislam/uptime-kuma#946] opened 2021-11-22 21:04 UTC
Hi, I am getting this error when testing a URL under CDN/WAF (imperva).

Can it be related to the following?

https://simonbarker.me/blog/2020-09-24:solve-node-header-error-parser-strictness

**Comment by louislam** [comment] 2021-11-23 04:09
Duplicate of https://github.com/louislam/uptime-kuma/issues/23

**Closed by louislam** 2021-11-23 04:09 UTC
Labels: help
