### ISSUE TITLE
Clickable QuickStats & filtering

### ISSUE THREAD

**Issue by wojcikm** [louislam/uptime-kuma#2187] opened 2022-10-06 17:36 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/19979741/194381307-7d30d0b3-2343-49ec-bd70-602275caee1d.png">

Please make clickable those numbers, or add filtering.

### ✔️ Solution

In above example with hundreds of domains, I have to scroll through entire list to find failing site. Clicking on red "1" and apply filter would be very useful.

**Comment by louislam** [comment] 2022-10-08 16:56
Duplicate of #1134

**Closed by louislam** 2022-10-08 16:56 UTC
Labels: feature-request
