### ISSUE TITLE
Status sorting on the status screen

### ISSUE THREAD

**Issue by tojeroman** [louislam/uptime-kuma#4257] opened 2023-12-19 18:21 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

On the status page, I would like the broken service to be at the top of the page and not at the bottom of the list. I would like to use the status page on surveillance monitors, so the header text could also be smaller to fit more information on the screen. I would also like the name of the outage service at the top of the screen and not the whole group.

### ✔️ Solution

see feature description

**Comment by CommanderStorm** [comment] 2023-12-20 16:20
Duplicate of #3743

**Closed by CommanderStorm** 2023-12-20 16:20 UTC
Labels: feature-request, area:status-page
