### ISSUE TITLE
[Feature request] custome graph times

### ISSUE THREAD

**Issue by 8fXvSYUcRD7u** [louislam/uptime-kuma#362] opened 2021-09-09 13:58 UTC
Hey, first of all
What an amazing project!
There is nothing better!
But, I would really like to be able to view other timeframes then just the last one and half hour in the graph.

For example: see a graph from 8:00 to 15:30 two weeks ago, or the hole last week at once. 
I am not really a programmer, so I probably won't be able to help 😥

_if this feature already exists, and I am just too dumb, I'm using
Ubuntu 20.04 with
docker 20.10.8 and
the latest stable - alpine kuma_

Thanks for this nice app!

**Comment by chakflying** [comment] 2021-09-09 14:05
Duplicate of #223

**Comment by 8fXvSYUcRD7u** [comment] 2021-09-09 14:29
Looks like there is no interest in doing so?
I think this would be a great feature, but maybe the idea with Grafana and Prometheus from #223 works.

Sorry for the duplicate, should I close it?

**Comment by louislam** [comment] 2021-09-09 14:41
> Looks like there is no interest in doing so?
> I think this would be a great feature, but maybe the idea with Grafana and Prometheus from #223 works.
> 
> Sorry for the duplicate, should I close it?

Upvote #223, I personally may choose popular suggestions to implement in next milestones.

**Closed by louislam** 2021-09-09 14:41 UTC
Labels: enhancement
