### ISSUE TITLE
Maintanance Notification

### ISSUE THREAD

**Issue by RandomLegend** [louislam/uptime-kuma#5007] opened 2024-08-11 19:53 UTC
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

Maintenance

### 🔖 Feature description

Be able to send a notification about a scheduled maintanance with the notification provider

### ✔️ Solution

It would be awesome if we were able to use an already setup notification to send out infos about upcoming or running maintanances.

For example i set up telegram to notify me. But some of my family members also use some of my services. And it would be easer to just let them get an info on the telegram chat that system maintanance for some services will be happening in like 15 Minutes and is scheduled to go for 30 minutes for example.

**Comment by CommanderStorm** [comment] 2024-08-12 01:06
Duplicate of https://github.com/louislam/uptime-kuma/issues/2462

**Closed by CommanderStorm** 2024-08-12 01:06 UTC
Labels: feature-request, area:maintenance
