### ISSUE TITLE
Notifications: Checkbox for displaying Host:Port/URLs

### ISSUE THREAD

**Issue by Roomiiaan** [louislam/uptime-kuma#3663] opened 2023-08-31 00:25 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

A possibility to set whether the Host/IP:Port/URL should be displayed when sending a notification

### ✔️ Solution

Add a checkbox to the settings of a notification, which is activated by default.

This setting is intended to enable/disable whether to display the service IP/URL when sending a notification

**Comment by CommanderStorm** [comment] 2023-08-31 09:20
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/975 (and the number of issues linked to it)
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-08-31 15:04 UTC
Labels: feature-request
