### ISSUE TITLE
disk space cpu usages

### ISSUE THREAD

**Issue by perfectwebtech** [louislam/uptime-kuma#2603] opened 2023-01-13 08:32 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, UI Feature

### 🔖 Feature description

hello 

is it not easy to implement disk space cpu ram and other  mdadm raid monitoring ? part ? 

### ✔️ Solution

may be some readymade library we can use or try ?  also ther eis 

whatsapp api i have i an integration sms and whatsapp api easy i think 

### ❓ Alternatives

may be some readymade library we can use or try ? 

### 📝 Additional Context

may be some readymade library we can use or try ?

**Comment by perfectwebtech** [comment] 2023-01-13 08:36
may be use this lib ? 

https://github.com/mscdex/ssh2

**Comment by Computroniks** [comment] 2023-01-13 13:21
I think this is out of scope for this project. Uptime Kuma is designed for if a service is up or down, not resource monitoring. For this, I would suggest node exporter and Prometheus or something like checkmk

**Comment by CommanderStorm** [comment] 2023-08-27 23:27
@perfectwebtech 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2231
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-03 23:19
Closing as duplicate of https://github.com/louislam/uptime-kuma/issues/2231

**Closed by CommanderStorm** 2023-12-03 23:19 UTC
Labels: feature-request
