### ISSUE TITLE
Add website and also email

### ISSUE THREAD

**Issue by Blisk** [louislam/uptime-kuma#1870] opened 2022-07-05 11:57 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

What I miss is under form to add website to monitor also to add email, so I can have for each website differend email.
If I don't put in email than it takes default email which is in settings.

### ✔️ Solution

Add form option beside website also email

**Comment by 401U** [comment] 2023-03-16 14:03
Excuse me but I can't get your meaning.

You mean different notification email for different monitor? Or everyone can add there email to receive notifications? Or something else?

**Comment by Blisk** [comment] 2023-03-16 14:26
To put under website also an email
so if I set monitoring for  website mywebsite.com and I put under mymail@gmail.com
I get notification on this mail also

**Comment by 401U** [comment] 2023-03-16 14:35
Still confused.
You mean receive mail notification? It's possible to add SMTP for notification.
![Y0316_214644](https://user-images.githubusercontent.com/52659312/225650830-03555571-25f3-49ca-9c2c-be4fd296135d.png)

**Comment by CommanderStorm** [comment] 2023-12-08 11:41
closing as same as @401U I am unsure what is being requested.
This may be a duplicate of #541

**Closed by CommanderStorm** 2023-12-08 11:41 UTC
Labels: feature-request, question, area:notifications
