### ISSUE TITLE
Move downed monitors to the top of the list automatically

### ISSUE THREAD

**Issue by RansomeBell** [louislam/uptime-kuma#5379] opened 2024-11-25 20:29 UTC
### 📑 I have found these related issues/pull requests

I haven;t found any.

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

The very left dashboard that shows all of the up and down monitors, could you make that to where if something goes down, it jumps up to the top of the list, and when it comes back up, it goes back to it's previous place in the list?

### ✔️ Solution

We have all green showing even if something goes down and would like for a downed monitor to go to the top of the list on the left side.

**Comment by CommanderStorm** [comment] 2024-11-26 00:20
Duplicate of https://github.com/louislam/uptime-kuma/issues/3034

**Closed by CommanderStorm** 2024-11-26 00:20 UTC
Labels: feature-request, area:dashboard
