### ISSUE TITLE
ssh monitor

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#1990] opened 2022-08-12 04:33 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Monitor, UI Feature

### 🔖 Feature description

ssh monitor for uptime kuma

### ✔️ Solution

NC

### ❓ Alternatives

NC

### 📝 Additional Context

NC

**Comment by pcgeek86** [comment] 2023-03-10 20:38
Using an SSH monitor would be awesome. The reason I came across this post is because I was thinking it would be neat to trigger an Ansible Playbook from Uptime Kuma. But using Ansible is a little too specific, so then I thought simply triggering **any** SSH command would be even better. That way you could run PowerShell scripts or anything else you want within SSH sessions, and return custom results.

Using a keyword search or JSON data validation would be a neat way to implement this.

**Comment by CommanderStorm** [comment] 2023-08-05 00:15
@mabed-fr 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/390
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-08-18 17:42 UTC
Labels: feature-request
