### ISSUE TITLE
Enable drilling down to specific monitor from the status page

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#5290] opened 2024-10-31 11:22 UTC
### 📑 I have found these related issues/pull requests

Not found.

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

On the status page, you have the ability to setup a link to click through to the URL being monitored. However, that is not always useful.
It would be great to also have the option to click through and drill into the monitor itself on the Dashboard.

### ✔️ Solution

Add an option for the click through link to go to either the monitored URL or to the URL of the monitor on the dashboard.

**Comment by CommanderStorm** [comment] 2024-10-31 22:19
Lets consolidate this in the previous issue.
If you have comments on how this should be implemented, lets continue the discussion there

Closing as duplicate of https://github.com/louislam/uptime-kuma/issues/2787

**Closed by CommanderStorm** 2024-10-31 22:19 UTC
Labels: feature-request, area:status-page
