### ISSUE TITLE
URL Tags to Prometheus metrics :)

### ISSUE THREAD

**Issue by Freezepop** [louislam/uptime-kuma#1945] opened 2022-07-26 18:24 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hellow guys! Can you add tags to Prometheus metrics as new lable? 

Now I am doing monitoring in zabbix for many teams in our company who are responsible for different sites.

Of course, zabbix allows you to create a lot of fake entities (hosts) and metrics on them can be filtered in discovery by regexp.

BUT I would still like to send notifications from one host based on item tags, and not to produce many fake hosts and rely on host group tags.

### ✔️ Solution

Adding tags to Prometheus metrics labels.

### ❓ Alternatives

Logical separation: one team responsible for the site - one host (in zabbix)

### 📝 Additional Context

**Tags**
![TAG](https://user-images.githubusercontent.com/28865504/181081010-2dc8a64a-2e88-43b8-a4a6-381fb9d8db49.png)
**to metrics**
![like this](https://user-images.githubusercontent.com/28865504/181081980-ebd36a08-7377-4dde-9e08-f4b4d53b06ad.png)

**Comment by spali** [comment] 2023-01-18 10:37
I think this is duplicate of #680 and would be solved by #898.

**Closed** 2023-01-18 10:38 UTC
Labels: feature-request
