### ISSUE TITLE
Multi column status pages

### ISSUE THREAD

**Issue by KRider92** [louislam/uptime-kuma#1844] opened 2022-06-27 17:42 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Having "vertical slices" in the status page would be very helpful in case of many monitors, i.e. on a multi-site deployment

### ✔️ Solution

Vertical slicing in status page, where different monitors could be added to different groups not only in a single column but also more than one:
![Example built using iFrames](https://user-images.githubusercontent.com/1257515/176002744-5b261492-34f1-461f-8ec5-bbc65c75df34.png)

### 📝 Additional Context

See also pull request #1831

**Comment by MrBlue90** [comment] 2022-11-24 19:53
Might not be 100% what you're looking for, but I got the multiple columns working by using Custom CSS. Just add this:

```
.mt-4 {
  column-count: 3; //Number of columns
}

**Comment by kami202** [comment] 2022-12-28 08:54
This is my custom css for removing unwanted spaces and multi column display. Not responsive, just for showing the status screen on a large tv.

body {
}
.mt-3{
  max-width: 1920px;
}
.mt-4 {
 column-count: 4; 
 margin-top: 0.5rem !important;
}
.mb-5{
margin-bottom: 0rem !important;
}
.p-4{
margin-bottom:0.2rem !important;
}

**Comment by KRider92** [comment] 2022-12-29 21:14
This is looking fine!

**Comment by MrBlue90** [comment] 2023-01-09 11:35
@kami202 That's a great addition!
I made a chance as well to make it more responsive and useful for mobile devices:

```
@media screen and (min-width: 1024px) {
	body { } 
	.mt-3{ max-width: 1920px; } 
	.mt-4 { column-count: 4; margin-top: 0.5rem !important; } 
	.mb-5{ margin-bottom: 0rem !important; } 
	.p-4{ margin-bottom: 0.2rem !important; }
}
```

@SebastianGwizdala I don't have the same issue with my code. For what it's worth, can you try again?

**Comment by CommanderStorm** [comment] 2023-12-14 00:23
Referencing #4236 which did include a better mock up using the custom css feature

**Comment by CommanderStorm** [comment] 2023-12-20 16:08
Closing as a duplicate of #592 as the FR is covered by said issue and said issue is more popular.

**Closed by CommanderStorm** 2023-12-20 16:08 UTC
Labels: feature-request, area:status-page
