### ISSUE TITLE
Add servers via API

### ISSUE THREAD

**Issue by manustu** [louislam/uptime-kuma#1276] opened 2022-02-08 17:05 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

It would be cool if there was an ability to add a new monitor via a REST API request

### ✔️ Solution

http://IP_ADDRESS:PORT?ip=192.168.0.1&type=ping&name=example_name&etc...etc

### ❓ Alternatives

Alternatively, allow to be able to define an external database in config

**Comment by mathiskir** [comment] 2022-02-08 17:51
I jus wanted to ask if its already possible but seems not.

**Comment by OmgImAlexis** [comment] 2022-02-22 22:54
Duplicate of https://github.com/louislam/uptime-kuma/issues/118?

**Comment by CommanderStorm** [comment] 2023-07-04 21:26
@manustu could you please recheck if this a duplacte of #118 ?
If yes, please close this issue, as duplicates only create immortal zombies (and are harder to issue-manage)
If no, what makes this issue distinct?

**Comment by kdambekalns** [comment] 2023-12-12 17:40
IMHO this is indeed a duplicate of #118

**Comment by CommanderStorm** [comment] 2024-02-09 00:44
@manustu 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #118 as this issue is included there
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2024-02-09 00:44 UTC
Labels: feature-request, area:api
