### ISSUE TITLE
Configure status page to display based on tags

### ISSUE THREAD

**Issue by CommanderRedYT** [louislam/uptime-kuma#3220] opened 2023-06-05 09:40 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

You could add a way of saying that a certain status page will display all the monitors from a specific tag. Maybe even in a way that you can assign the tags for each group on the status page. Also, maybe a blacklist for tags would be a good idea, so you can just add a "no-display" tag to exclude it.

### ✔️ Solution

I for example would use that to automatically display status of services at home and on servers, and then split them via status groups for things like "Ping", "HTTP(S)", ....

**Comment by chakflying** [comment] 2023-06-05 10:14
Duplicate of #2801 and #1609

**Comment by CommanderStorm** [comment] 2023-06-06 10:44
@CommanderRedYT Given that this is likely a duplicate: could you close this issue?
(only Louis and the you can do so. Duplicates just make things less manageable though)

**Closed** 2023-06-06 10:49 UTC
Labels: feature-request
