### ISSUE TITLE
Monitoring Disk Usage

### ISSUE THREAD

**Issue by Termex69** [louislam/uptime-kuma#2532] opened 2023-01-04 09:44 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

This feature will enable the monitoring of disk capacity and would alert nearing 100% utilization based on a user threshold.
Example: 
/ or C: is set to trigger an alert when the disk capacity reaches 90% Utilization. The user can set the threshold percentage between 70% to 95%.

### ✔️ Solution

I my mind this can be implemented using the df -h command for Linux & Mac by extracting the current percentage and comparing it to the set user thresshold.
In Windows we can probably look at using wmic but may need to manually calculate the usage as a percentage.

### ❓ Alternatives

Wmic may take some time for integration but I suspect the Linux and Mac integration may be easier to implement, at least for now as a work in progress.

**Comment by Computroniks** [comment] 2023-01-04 11:24
I think that this would be a bit out of scope for Uptime Kuma. The system is designed to measure only uptime, for resources monitoring, I would recommend something like node exporter with Prometheus or librenms

**Comment by Termex69** [comment] 2023-01-04 11:55
Hi Matthew,

Thanks for the feedback, but it would be nice to have it in the future of
this project.

**Comment by fionnb** [comment] 2023-01-20 12:04
I agree with @Computroniks. @Termex69, this is "Uptime" Kuma, not "Monitor-It-All" Kuma.
I would recommend to get Zabbix if you need a full-blown Server monitoring solution.

The fact that setting up Kuma only takes a few keystrokes and clicks is part of why it is so sexy.
If you pump it up to a do-it-all monitoring solution that appeal will get lost and it would become just another monitoring tool.

**Comment by Termex69** [comment] 2023-02-10 18:35
Agreed, and yes its one of a kind and sexy.

**Comment by tikeyknax** [comment] 2023-07-02 19:39
If you still want to monitor your disk usage with uptime kuma because a full-blown server monitoring solution might be too much and you have uptime kuma already set up, the following solution might work for you (for monitoring the disk usage on linux machines).

* Setup an uptime kuma check with monitor type "push"
* Write a script that checks the disk usage and calls the push url
* Call the script regularly via cron or similar

With this solution, you can monitor the disk usage of every linux machine in your network even if uptime-kuma is not set up on all of them.

Script that checks disk usage of `/dev/root` and makes the check "down" if more than 90% of the disk is used:
```
#!/bin/bash

if [ `df | grep -F "/dev/root" | awk '{print $5}' | tr -d %` -le 90 ]; then
  curl -fs -o /dev/null --retry 5 http://<your_push_url>?status=up
else
  curl -fs -o /dev/null --retry 5 http://<your_push_url>?status=down
fi
```

Crontab entry to call the script every 30 minutes and on reboot:
```
#healthcheck free space
05,35 * * * * root <path_to_script>
@reboot root <path_to_script>
```

**Comment by CommanderStorm** [comment] 2023-08-27 23:26
@Termex69 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2231
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-03 23:20
Closing as duplicate of https://github.com/louislam/uptime-kuma/issues/2231

**Closed by CommanderStorm** 2023-12-03 23:20 UTC
Labels: feature-request
