### ISSUE TITLE
Notification Webhook different on `up` and `down` cases

### ISSUE THREAD

**Issue by clement-igonet** [louislam/uptime-kuma#4203] opened 2023-12-10 14:58 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

Already covered in other notification types, but not for webhook type:
* https://github.com/louislam/uptime-kuma/issues/508
* https://github.com/louislam/uptime-kuma/issues/1233
* https://github.com/louislam/uptime-kuma/issues/4117
* https://github.com/louislam/uptime-kuma/issues/3585

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

When triggering a notification by webhook, I'd like the ability to send different POST request on `up` case and `down` case.

For instance:
* `up` case: Request `https://my_alerting_app/webhook/1/issues` with `{"issue_key":"NOTIF-1234"}` BODY
*  `down` case: Request `https://my_alerting_app/webhook/1/issues/NOTIF-1234/close` with empty BODY

How may I set it up ?

### ✔️ Solution

Ability to select if the defined webhook is just for `up` case, `down` case, or the both.

### ❓ Alternatives

Create a dedicated notification specific for DevLake application.

Specs to generate a downtime INCIDENT by webhook: https://devlake.apache.org/docs/v0.20/Plugins/webhook

**Comment by CommanderStorm** [comment] 2023-12-10 18:35
I don't see why this is not a duplicate of #508.
As far as I understand said issue, this covers all notification types.
=> closing as a duplicate

**Closed by CommanderStorm** 2023-12-10 18:35 UTC
Labels: feature-request, area:notifications
