### ISSUE TITLE
Show uptiom

### ISSUE THREAD

**Issue by fabry00** [louislam/uptime-kuma#4105] opened 2023-11-25 09:41 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I'd like to have up to 1 year uptime statistics in the status page
So far I can see only the last 24 hours.
Is it possible to add a drop-down to select the period in the status page?

### ✔️ Solution

I'd like to choose the period of the metrics shown in the status page.
We could have a dropdown that can be used to select the time period (24 hours, week, month, year)

**Comment by CommanderStorm** [comment] 2023-11-25 17:30
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2477
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Comment by chakflying** [comment] 2023-11-26 04:50
Duplicate of #1667

**Closed by chakflying** 2023-11-26 04:50 UTC
Labels: feature-request
