### ISSUE TITLE
Resource/Server monitoring

### ISSUE THREAD

**Issue by znillax34** [louislam/uptime-kuma#964] opened 2021-11-25 22:00 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be nice to have a Server Monitor etc. like HetrixTools has, where you can view how much resources the server uses.

I have linked to a status page that has this; [https://status.blare.host](https://status.blare.host)

### ✔️ Solution

^^

**Comment by chakflying** [comment] 2021-11-26 02:18
The resource monitor part is a Duplicate of #819

**Comment by znillax34** [comment] 2021-11-26 17:51
Oops, didn't notice that

**Closed** 2021-11-26 21:00 UTC
Labels: feature-request
