### ISSUE TITLE
[Feature]: <Multi-location checks>

### ISSUE THREAD

**Issue by stardevelop** [louislam/uptime-kuma#828] opened 2021-10-29 14:08 UTC
### 🏷️ Feature Request Type

Other

### 🔖 Feature description

We want to verify incidents from multiple locations (in different countries) to prevent false-positives.

### ✔️ Solution

Add additional servers in multiple locations for monitoring a website.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar feature request

**Comment by deefdragon** [comment] 2021-10-29 18:50
Agreed. Duplicate of #84 and some of the issues I cross referenced in #468 (#324 specifically)

**Closed as not planned** 2023-12-04 13:53 UTC
Labels: feature-request, A:monitor, type:new

**Comment by CommanderStorm** [comment] 2024-03-01 14:16
Actually, this is a duplicate of #4031 instead ^^
