### ISSUE TITLE
Monitor Group bulk add

### ISSUE THREAD

**Issue by VashStampedeTRI14** [louislam/uptime-kuma#3604] opened 2023-08-18 12:23 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Looking for a feature in the settings similar to "Tags" but for monitor groups. This way you can bulk add multiple into a group instead of one at a time upon creation. 

### ✔️ Solution

Be able to go in to settings and select Monitor Group. From here you can create a new monitor group and/or bulk add monitors to that group or an existing group.

**Comment by CommanderStorm** [comment] 2023-08-18 12:27
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1457 or https://github.com/louislam/uptime-kuma/issues/1323
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-08-18 12:35 UTC
Labels: feature-request
