### ISSUE TITLE
Allow discord webhooks to be sent on down/up instead of both

### ISSUE THREAD

**Issue by SeaswimmerTheFsh** [louislam/uptime-kuma#4117] opened 2023-11-29 02:19 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Allow discord webhooks to be sent on down OR up, instead of always being sent on both.

### ✔️ Solution

I'd like to be able to choose in the UI if the webhook is sent on Up or Down, or both.

### ❓ Alternatives

Another fix for my issue is allowing a different custom message prefix for up/down, but that seems a bit more restrictive?

**Comment by CommanderStorm** [comment] 2023-11-29 11:46
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3585 https://github.com/louislam/uptime-kuma/issues/1233 / https://github.com/louislam/uptime-kuma/issues/1562 and partially https://github.com/louislam/uptime-kuma/issues/1137
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Closed** 2023-11-29 12:04 UTC
Labels: feature-request
