### ISSUE TITLE
Monitor Dependancies

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [louislam/uptime-kuma#4956] opened 2024-07-22 22:23 UTC
### 📑 I have found these related issues/pull requests

https://github.com/louislam/uptime-kuma/pull/1236 (Closed, not merged)
https://github.com/louislam/uptime-kuma/issues/1717 (Closed, as duplicate of above closed PR)
https://github.com/louislam/uptime-kuma/issues/271 (Closed, duplicate of #216)
https://github.com/louislam/uptime-kuma/issues/216 (Closed, github cleaned up after only 7 days..)
https://github.com/louislam/uptime-kuma/issues/1089 (Opened in 2021)

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Ability to define monitor dependencies.

Aka, a drop down on a monitor, which allows you to select another monitor the current monitor is dependant on.

### ✔️ Solution

I have a lot of services monitored with uptime kuma. Its a fantastic solution. 

However, when there are broad networking issues, such as a particular router going offline, I end up getting literally hammered with thousands of notifications for each of the individual services.

It does not make sense to group together these services, as they are separate, independant services. 

What, I would really like, is the ability to mark those services as dependant, on a particular monitor.

That way, I can flag all of my say... IOT services, as dependant on the firewall which hosts/routes IOT.

If, the internet goes down, I don't need 20 notifications telling me this- I just need one notification saying, HEY, your internet is down. Being able to map internet-dependant services with a required dependency would allow this to get cleaned up.

Even nicer, would be the ability to map these dependencies using say, Tags. 

For, a visual example-

![image](https://github.com/user-attachments/assets/1b7effaa-7868-455d-8802-28d8ebfc29da)

Managing these dependencies via tags, would allow multiple different dependant monitors to be factored in, while giving a visual confirmation.

### ❓ Alternatives

About the only viable alternative right now, is to look at other solutions. This, is not a current feature, despite multiple tickets being opened for it. None- of the tickets were closed stating, not planned, or will not implement.

So- this is yet another attempt to revive this.

**Comment by CommanderStorm** [comment] 2024-07-22 22:58
Duplicate of https://github.com/louislam/uptime-kuma/issues/1089
Just because an issue is older does not mean adding a duplicate is better. If you have content to add, please contribute to #1089 instead.

Our contribution guide is here https://github.com/louislam/uptime-kuma/blob/2c31f3a2ff37d96331b0dc14d896eea37f76c47a/CONTRIBUTING.md

**Closed by CommanderStorm** 2024-07-22 22:58 UTC
Labels: feature-request
