### ISSUE TITLE
Are Kuma groups coercible to “or” logic?

### ISSUE THREAD

**Issue by brunialti** [louislam/uptime-kuma#3647] opened 2023-08-26 19:15 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

The Kuma monitoring groups are nice if you want be sure a set of services/devices are up having an “at glance” status overview. That is any member of a kuma group is "and"ed in order to have the group status.
What about "or"ing kuma groups? is it possible? I would like to use them for presence detection, grouping all ips (pc, mobile, …) used by family members: if at least one is active that member is at home.
Is it possible? How to do it?

### ✔️ Solution

The group status should have 2 options: or | and.
The and option is as groups are working now.
The or options let a group be up when at leat one of the member is up

**Comment by CommanderStorm** [comment] 2023-08-26 20:26
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3387
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-08-26 20:28
> The and option is as groups are working now

Not quite true.
Please see https://github.com/louislam/uptime-kuma/issues/3629#issuecomment-1689912853

**Comment by brunialti** [comment] 2023-08-26 21:47
Duplicate request

**Closed** 2023-08-26 21:46 UTC
Labels: feature-request
