### ISSUE TITLE
Mass edit monitors

### ISSUE THREAD

**Issue by streamthing** [louislam/uptime-kuma#967] opened 2021-11-26 12:47 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Select few monitors and change it in one click...
For now i need to click one monitor, edit, change value, save.
Click next, next next.

Just mass settings edit.
heartbeat, check times, notifications rules etc.

### ✔️ Solution

UI with checkbox on monitor and `Edit selected` button.

**Comment by edrock200** [comment] 2022-10-18 14:23
Another +1 for this feature.

**Comment by x86dev** [comment] 2023-07-10 19:08
+1 as well, would love this feature.

**Comment by CommanderStorm** [comment] 2023-07-10 19:12
@x86dev @edrock200 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

Related PR that implements part of this issue: https://github.com/louislam/uptime-kuma/pull/1886

**Comment by CommanderStorm** [comment] 2023-07-27 21:57
@streamthing 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/455
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-05 23:30
@streamthing 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #455 as there Mass editing and bulk editing are essentially the same thing
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-05 23:30 UTC
Labels: feature-request
