### ISSUE TITLE
Auto reload of status page

### ISSUE THREAD

**Issue by mathiskir** [louislam/uptime-kuma#1316] opened 2022-02-19 10:31 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Uptimerobot has a feature that the page gets refreshed every 60 seconds, I would love to have that in uptime kuma too.
Maybe as opt-in and with a custom amount of seconds.

### ✔️ Solution

I'd like to have a feature in uptime-kuma which would allow you to automatically refresh the status page.

**Comment by mqqtpower** [comment] 2022-03-23 06:48
I second that.
Would be great to see Status page interactive where you can specify refresh time

**Comment by mathiskir** [comment] 2022-03-27 10:52
Any update on this? I think this is pretty easy to do, and many people would like it.
@louislam what's your opinion on this?

**Comment by procheeseburger** [comment] 2022-03-27 10:55
Would like this as well. I like having the status page open but it's a bit useless if it's static and doesn't update.

**Comment by raduburla** [comment] 2022-04-18 12:07
The status page has auto refresh already set, at 5mins. Because there is no animation or a "Last updated" text it's hard to notice it.


The 5mins loop is set here
https://github.com/louislam/uptime-kuma/blob/9bf3b3a0f45e20b7c4207a447111af212b7676b9/src/pages/StatusPage.vue#L556-L560

**Comment by mathiskir** [comment] 2022-04-18 12:11
> The status page has auto refresh already set, at 5mins. Because there is no animation or a "Last updated" text it's hard to notice it.

Would love to be able to customize it and   visually see when the last update was or just that it updated

**Comment by mathiskir** [comment] 2022-04-21 16:32
@louislam what are your thoughts on this? Would you implement this in one of the next updates?

**Comment by louislam** [comment] 2022-12-22 06:58
Duplicate of #978

**Closed by louislam** 2022-12-22 06:58 UTC
Labels: feature-request
