### ISSUE TITLE
Quick Stats Colors

### ISSUE THREAD

**Issue by jonnymccullagh** [louislam/uptime-kuma#3068] opened 2023-04-14 10:55 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I think the default colour for 'Down' and 'Maintenance' should be grey unless they are greater than zero.

### ✔️ Solution

So could we have a conditional on the css class here have a ternary conditional for the color. 
https://github.com/louislam/uptime-kuma/blob/master/src/pages/DashboardHome.vue#L16
Changing:
```
<span class="num text-danger">{{ $root.stats.down }}</span>
```
to:
```
<span class="num text-{{ $root.stats.down > 0 ? "danger" : "secondary" }}">{{ $root.stats.down }}</span>
```
Or however this should be in Vue.

Plus similar for maintenance block.

**Comment by chakflying** [comment] 2023-04-14 14:46
Duplicate of #3037

**Closed** 2023-04-14 14:49 UTC
Labels: feature-request
