### ISSUE TITLE
Add devices dependency with another device for alerts

### ISSUE THREAD

**Issue by JaJe92** [louislam/uptime-kuma#3951] opened 2023-10-27 18:12 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Add specific devices dependent on a specific device if that device goes down.
Basically, Let's say I monitor a managed switch to be always UP and I have 4-5 devices behind that switch. If the switch goes down, I don't receive one alert but 5-6 alerts as all devices behind that switch also appear to be offline.

### ✔️ Solution

I suggest adding some sort of dependency tree for cases like this to be easy to monitor if the issue is on the node (switch/router) or not.

**Comment by CommanderStorm** [comment] 2023-10-28 21:51
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2487 https://github.com/louislam/uptime-kuma/issues/2348 https://github.com/louislam/uptime-kuma/issues/2335
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

Note that https://github.com/louislam/uptime-kuma/pull/1236 is stalled because it has not been updated to work with grouped monitors ⇒ discussing a reattempt via the paths in our contribution guide is possible

**Comment by CommanderStorm** [comment] 2023-12-01 21:09
@JaJe92  
We are consolidating duplicate issues a bit to make issue management eazier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/1089 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
=> I am going to close this as a duplicate

**Closed by CommanderStorm** 2023-12-01 21:09 UTC
Labels: feature-request
