### ISSUE TITLE
My sugestion... about domain watcher in uptime kuma

### ISSUE THREAD

**Issue by AnthraxBPLLC** [louislam/uptime-kuma#2511] opened 2022-12-31 16:04 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Notification, New Monitor, Other

### 🔖 Feature description

I wonder if uptime Kuma can add a feature to watch the domain expiration or a domain watcher for an expired domain; let's say the part is about expired. It gives us a notification, or it can detect how many days expire that would be perfect.

And an SMS notification. Maybe there's an option we can add our API, let's say, down and give us a warning via SMS using our API

And a notification if a CPU threshold has been reached at some point, let's say 90% of each CPU of the machine that we want to watch, and give us a notification someone is abused or something is wrong or something heavy going on with the machine.

maybe we can put some kind of command like an API that API is a command only root able to run it and watch over the system status of loads

### ✔️ Solution

Maybe we can combine it into some open-source domain watcher out there and put it in Kuma. There are a lot of domain tools open source

.We could

### ❓ Alternatives

An alternatives solution for this if its just to watch for uptime about the server. You can leave this idea of suggestions ofalternative

### 📝 Additional Context

its a sugesiontion that am was able to give some idea becos if we got this there's no need to pay a pay version of watchdog service out there.it'sideas

**Comment by MarcHagen** [comment] 2023-01-01 19:02
There is a draft PR for this: 
- https://github.com/louislam/uptime-kuma/pull/1775

**Comment by louislam** [comment] 2023-01-02 06:14
Duplicate of #944

**Closed by louislam** 2023-01-02 06:14 UTC
Labels: feature-request
