### ISSUE TITLE
add user account

### ISSUE THREAD

**Issue by XW-ui** [louislam/uptime-kuma#5140] opened 2024-09-29 17:14 UTC
### 📑 I have found these related issues/pull requests

?

### 🏷️ Feature Request Type

Dashboard, Settings, Other

### 🔖 Feature description

I'd like to add a user management system to the repository. This would allow multiple user accounts to be created, each with specific roles or permissions. These permissions could include the ability to modify specific parts of the system, create or manage probes, etc.

### ✔️ Solution

A user administration system integrated into the application, with an interface for creating users and assigning them specific permissions (read-only, modify, create probes, etc.). Ideally, this system could allow granular management of permissions, so that administrators can specify exactly what each user can do in the application.

### ❓ Alternatives

I considered using an external user management system, such as an external authentication service (OAuth, LDAP, etc.), but you would prefer a solution integrated into the project.

### 📝 Additional Context

The purpose of this function is to allow certain people to modify or create probes, while others only have read-only permissions. This would improve security and access control while facilitating collaboration.

**Comment by apio-sys** [comment] 2024-09-29 17:53
It is currently not possible to add an account.
Multiple users has already been requested in issue https://github.com/louislam/uptime-kuma/issues/128 https://github.com/louislam/uptime-kuma/issues/1039 https://github.com/louislam/uptime-kuma/issues/1255
Please post in english and check if your proposal and/or issue doesn't already have an open or closed ticket/conversation.

**Comment by CommanderStorm** [comment] 2024-09-29 23:01
Duplicate of https://github.com/louislam/uptime-kuma/issues/128

**Closed by CommanderStorm** 2024-09-29 23:01 UTC
Labels: feature-request
