### ISSUE TITLE
增加application/x-www-form-urlencoded请求类型

### ISSUE THREAD

**Issue by gaye746560359** [louislam/uptime-kuma#3488] opened 2023-07-27 01:58 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

application/x-www-form-urlencoded

### ✔️ Solution

application/x-www-form-urlencoded

**Comment by chakflying** [comment] 2023-07-27 05:50
Duplicate of #1332

**Closed** 2023-07-27 06:42 UTC
Labels: feature-request
