### ISSUE TITLE
Have the option to make the status page show all monitors in columns next to each other instead of scrolling.

### ISSUE THREAD

**Issue by JackBZA** [louislam/uptime-kuma#3934] opened 2023-10-24 09:51 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Would like to have the status page display the monitors in multiple columns in the browser instead of having to scroll up and down to view all the monitors. this would definably make uptimekuma a lot more usable for quick viewing/glancing.

### ✔️ Solution

Would like to have uptime kuma status page to give us an option to either disaply the status page in Lists or grid options with columns so all monitors can be displayed without having to scroll

### ❓ Alternatives

advise where i can edit the status page myself so I can rework the layout for my installation

**Comment by CommanderStorm** [comment] 2023-10-24 12:18
I think this is a duplicate of  https://github.com/louislam/uptime-kuma/issues/1844 (which has duplicates like https://github.com/louislam/uptime-kuma/issues/2376 or https://github.com/louislam/uptime-kuma/issues/3062)
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Comment by JackBZA** [comment] 2023-10-24 12:27
> I think this is a duplicate of #1844 (which has duplicates like #2376 or #3062) If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage? If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
> 
> Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

I do not agree. I think this is different I will upload a picture that I made using paint of what I am aiming for :( just give me a second

**Comment by JackBZA** [comment] 2023-10-27 08:58
![image](https://github.com/louislam/uptime-kuma/assets/148847929/4cbd02e9-a6fc-45bd-be48-9d2124d17144)
I would like it to look like this.

**Comment by CommanderStorm** [comment] 2023-10-27 11:25
As noted above (I don't see a functual difference, only design):

> If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?)

**Comment by JackBZA** [comment] 2023-11-07 07:30
> As noted above (I don't see a functual difference, only design):
> 
> > If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?)

I think that making it possible for people to select a grid layout like 2x2 or 4x4 or even have them manually adjust the layout by just adding the own grid options like 6x10 would be cool

**Comment by CommanderStorm** [comment] 2023-12-14 00:22
Referencing #4236 which did include a better mock up using the custom css feature

**Comment by CommanderStorm** [comment] 2023-12-20 16:06
> making it possible for people to select a grid layout like [...]

Closing as a duplicate of #592

**Closed by CommanderStorm** 2023-12-20 16:06 UTC
Labels: feature-request, area:status-page
