### ISSUE TITLE
Its not a feature but a update scripts 

### ISSUE THREAD

**Issue by Blacksquadman1** [louislam/uptime-kuma#4405] opened 2024-01-21 17:27 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

```sh
version=curl -s https:/api.github.com/repos/louislam/uptime-kuma/tags | jq -r 'first(.[].name | select(test("^v?[0-9]")))'

cd /home/status/uptime-kuma #change this to your direction

echo "Updating Uptime Kuma"

echo "Download from Github"

git fetch --all
git checkout $version --force

echo "Installing update"

npm install --production
npm run download-dist

echo "Restart service"

pm2 restart uptime-kuma

echo "Update finished"
```

### ✔️ Solution

its not a feature but a Update script

**Comment by CommanderStorm** [comment] 2024-01-21 18:05
I don't think that we are currently capable of maintianing an additional way of doing things.
We have dropped the installation script for this exact reson.

Here is our updating docs: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update
Is there something we are missing/unclear about?

**Comment by jult** [comment] 2024-01-22 21:46
```
~# npm install --production
npm WARN config production Use `--omit=dev` instead.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.5.0', npm: '10.2.5' }
npm WARN EBADENGINE }
[#########.........] - idealTree: timing idealTree Completed in 2409ms
```
and it hangs on this..

**Comment by CommanderStorm** [comment] 2024-01-22 22:07
@jult
You already reported this in this issue https://github.com/louislam/uptime-kuma/issues/4408 which was closed because you did not stick to our rules of providing the context we need.
We require this context as Bad issue reports => bad help

Please stick to our rules and report **WITH FULL CONTEXT** of what you tried, what happened and how your environment looks here: https://github.com/louislam/uptime-kuma/issues/new/choose
Your issue seems is likely caused by networking (IPV6) issues connected with your particular setup.
See https://www.reddit.com/r/node/comments/z9hsdw/npm_install_stuck_on_idealtree_builddeps/ why I come to this conclusion.

If in fact you don't have your networking setup configured correctly, that is nothing that we can fix.

**Comment by louislam** [comment] 2024-01-23 23:04
Thanks, did not know the api.github.com is not required an api key.

Maybe we can implement a smarter npm script (`npm run self-update`) to self update in the future.

But considering it is not actually a help, I close it now.

**Closed by louislam** 2024-01-23 23:04 UTC
Labels: question, help, area:deployment

**Comment by CommanderStorm** [comment] 2024-01-23 23:20
> did not know the api.github.com is not required an api key

It does not, but if you don't provide an api key, the limtis are severely lower (60 requests/h vs 5000 requests/h)
