### ISSUE TITLE
Customizable autoRefreshInterval on Status Page

### ISSUE THREAD

**Issue by rvsit** [louislam/uptime-kuma#3103] opened 2023-04-25 21:15 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

With the countdown now added in #2878 it would be great if we could customize the `autoRefreshInterval` (as seen on https://github.com/louislam/uptime-kuma/blob/master/src/pages/StatusPage.vue#L435).

For my usecase I would like the dashboard to refresh every 30 seconds e.g.

### ✔️ Solution

Add the ability to customize the `autoRefreshInterval` in the sidebar when editing a status page.

### ❓ Alternatives

A configuration variable would also be sufficient for my usecase

### 📝 Additional Context

I am willing to make a pull request if helpful, does not seem like it would be too difficult to implement

**Comment by chakflying** [comment] 2023-04-25 23:09
The response is still cached for 5 minutes server-side in `server\routers\status-page-router.js`, that needs to be handled somehow.

**Comment by asdf1nit** [comment] 2023-05-15 22:34
Vote for this.

**Comment by CommanderStorm** [comment] 2023-07-27 22:18
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/978#issuecomment-1362496508
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by chakflying** [comment] 2023-12-06 19:44
Reopening to track this issue specifically here.

**Comment by brooksvb** [comment] 2023-12-13 19:04
We just set up Uptime Kuma for our IT team and everyone loves the tool. I did come across this issue though because we would like to have a shorter refresh interval. I'm glad the issue is already here and there has been recent activity. I hope to see this feature.

**Closed** 2024-05-19 19:56 UTC
Labels: feature-request, area:status-page
