### ISSUE TITLE
Feature: Let HTTP monitoring type use custom IP

### ISSUE THREAD

**Issue by TomsProject** [louislam/uptime-kuma#3979] opened 2023-11-05 07:20 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, Other

### 🔖 Feature description

Uptime Kuma's HTTP monitoring type currently only supports inputting URLs for monitoring. However, some websites will configure multiple IPs for a single domain name. If you want to monitor only one of them, Uptime Kuma currently cannot achieve this.

For example: a.example.com points to 1.1.1.1 and 2.2.2.2
If I want to check whether https://a.example.com/blabla runs well on 1.1.1.1, Uptime Kuma currently cannot achieve this.

### ✔️ Solution

Add an option to specify an IP for the HTTP monitoring type.

**Comment by CommanderStorm** [comment] 2023-11-05 22:00
You can do that with the tools currently at your disposal:
- you enter the ip into the url field
- you enter the [`Host` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) as described in https://github.com/louislam/uptime-kuma/issues/2991

I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2991
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Comment by CommanderStorm** [comment] 2023-11-05 22:00
Related: Related: https://github.com/louislam/uptime-kuma/issues/1242

**Closed** 2023-11-06 15:26 UTC
Labels: feature-request
