### ISSUE TITLE
suggest llike Domain Admin, It can monitor domain and SSL

### ISSUE THREAD

**Issue by mouday** [louislam/uptime-kuma#3257] opened 2023-06-13 09:20 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

monitor domain and SSL

### ✔️ Solution

like Domain Admin

### ❓ Alternatives

see it: https://github.com/mouday/domain-admin/

### 📝 Additional Context

preview

![](https://raw.githubusercontent.com/mouday/domain-admin/master/image/screencapture.png)

**Comment by CommanderStorm** [comment] 2023-06-13 09:27
What do you mean by monitor domain and ssl?

Is this not already covered by 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/c541f732-9fa7-4990-b4ef-18d26c796d18)

Is this a duplicate of https://github.com/louislam/uptime-kuma/issues/944 ?

**Comment by CommanderStorm** [comment] 2023-12-13 16:00
Closing as a duplicate of #944 as no comment by @mouday

**Closed by CommanderStorm** 2023-12-13 16:00 UTC
Labels: feature-request, question, area:monitor
