### ISSUE TITLE
Email notification titles are confusing

### ISSUE THREAD

**Issue by rwjack** [louislam/uptime-kuma#3183] opened 2023-05-21 18:59 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

The notification email title shouldn't really contain the status of the check.

At the very least it should contain the ACTUAL status of the check, because the way it is right now is just confusing.

![ima_0df683b](https://github.com/louislam/uptime-kuma/assets/59068073/d9ab3761-adb5-4eb3-8779-ac72cc8d9301)

![ima_879f2f6](https://github.com/louislam/uptime-kuma/assets/59068073/71938307-9560-4da4-b187-b397dcc1a243)

### ✔️ Solution

Explained above.

**Comment by CommanderStorm** [comment] 2023-05-21 19:01
What do you mean by 

> The notification email title shouldn't really contain the status of the check.

I am confused by the email as well. What was the underlying event that triggered it?

**Comment by rwjack** [comment] 2023-05-21 19:12
> What was the underlying event that triggered it?

The service went up, after being down.

The down email is not confusing, but then I guess the service going up notification uses the same email subject, hence the confusion.

**Comment by CommanderStorm** [comment] 2023-05-21 19:18
This is a bug. You have reported this as a feature request and not a bug. (I can't change categories for permission reasons)
Please close this issue and reopen a bug report.

The reason behind this is, that there is some metadata which is supplied via the bug report template which may aid the person who will debug this issue 😉

**Closed** 2023-05-21 19:27 UTC
Labels: feature-request
