### ISSUE TITLE
Feature to add calendar to see past outages / incidents and upcoming maintenance

### ISSUE THREAD

**Issue by sachintandon-nexla** [louislam/uptime-kuma#3792] opened 2023-09-23 19:27 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, UI Feature

### 🔖 Feature description

Feature to add calendar to the statusPage see past outages and upcoming maintenance

### ✔️ Solution

Feature to add calendar to the statusPage see past outages / incidents and upcoming maintenance.

**Comment by CommanderStorm** [comment] 2023-09-23 19:58
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1984
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by sachintandon-nexla** [comment] 2023-09-26 16:39
yes it can be integrated to the issue #1984 as this feature request requests for adding the incident and upcoming maintenance on the statusPage for each service.

**Comment by CommanderStorm** [comment] 2023-09-27 00:08
@sachintandon-nexla
Could you please close this issue then?
Only you or Louis can do so..

**Comment by CommanderStorm** [comment] 2023-12-04 18:41
> yes it can be integrated to the issue https://github.com/louislam/uptime-kuma/issues/1984

Closing as a duplicate

**Closed by CommanderStorm** 2023-12-04 18:41 UTC
Labels: feature-request
