### ISSUE TITLE
Tile Dashboard like PRTG

### ISSUE THREAD

**Issue by christianhz01** [louislam/uptime-kuma#1367] opened 2022-03-11 22:25 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

In the monitoring software "PRTG" there is an overview of all hosts in a kind of tile overview. This is especially handy if you want to have everything in one view for e.g. a status monitor for the IT department without having to scroll. Below I have linked a screenshot, in which you can guess what I mean

### ✔️ Solution

-

### 📝 Additional Context

Screenshot: https://www.krakovic.de/wp-content/uploads/2015/05/Screenshot_2015.05.22_11h47m33s_006_.png

**Comment by CommanderStorm** [comment] 2023-09-22 00:30
@christianhz01 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/968
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-07 17:43
Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/968

**Closed by CommanderStorm** 2023-12-07 17:43 UTC
Labels: feature-request
