### ISSUE TITLE
Descriptions on the status page per monitor

### ISSUE THREAD

**Issue by MayhemBill** [louislam/uptime-kuma#5037] opened 2024-08-21 20:55 UTC
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

Small descriptions for each monitor, allows us to show additional notes for monitors

### ✔️ Solution

write a small description for each monitor that shows up under the monitor.

**Comment by CommanderStorm** [comment] 2024-08-21 21:17
Duplicate of https://github.com/louislam/uptime-kuma/issues/3008
Closing as a duplicate

**Closed by CommanderStorm** 2024-08-21 21:17 UTC
Labels: feature-request, area:status-page
