### ISSUE TITLE
Scheduled Maintenance Windows (Pauses notifications & banner displays on Status Page)

### ISSUE THREAD

**Issue by kristiandg** [louislam/uptime-kuma#1908] opened 2022-07-17 13:28 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

The ability to schedule a maintenance window, and indicate which monitors are impacted, so they don't alert during that time (selectable to not alert, alert maintenance start/end, and alert as normal).

### ✔️ Solution

When a maintenance schedule is created, at the start of the window, the impacted monitors (selected at the time of creation),  will go into a new mode that shows "Maintenance" (could even do this by displaying the monitor with a quaint "construction barber pole yellow/black banner over the monitor, or a set of emojis).

For alerts, if set to start/end, alerts would be send at the beginning/end of the maintenance window only. If alert as normal was set, then it would still send alerts, but an added line would indicate it's currently in maintenance so the alert should be treated accordingly.

### ❓ Alternatives

Right now, I see no provision to handle planned maintenance, short of pausing the impacted monitors manually.

### 📝 Additional Context

If accessible from the API, might even allow someone's existing ticketing system to auto build maintenance windows based on approved/scheduled change activity.

**Comment by HujinoKun** [comment] 2022-07-21 18:52
+1

**Comment by RangersMS** [comment] 2022-08-07 20:06
+1

**Comment by alexdetsch** [comment] 2022-08-08 09:59
This is a duplicate of #191
Someone opened a pull request https://github.com/louislam/uptime-kuma/pull/1213 which adds adds a maintenance planning system.

**Comment by kristiandg** [comment] 2022-08-08 11:49
Added these notes to that one.

**Closed** 2022-10-15 12:54 UTC
Labels: feature-request

**Comment by WeterPeter** [comment] 2024-02-02 07:01
Yes please!

**Comment by CommanderStorm** [comment] 2024-02-02 08:52
@WeterPeter ?

**Comment by WeterPeter** [comment] 2024-02-02 08:54
> @WeterPeter ?

I also vote for implementing a maintenance window feature .

**Comment by CommanderStorm** [comment] 2024-02-02 09:50
> a maintenance window feature

???
#1213 was merged and released in `1.19.0`.
