### ISSUE TITLE
Allow HTTP method selection when using webhook notifications

### ISSUE THREAD

**Issue by skjdghsdjgsdj** [louislam/uptime-kuma#4413] opened 2024-01-23 15:53 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Some web API endpoints like Hubitat don't allow HTTP POST invocations, only HTTP GET. I'm trying to invoke an HTTP endpoint in Hubitat as part of my Uptime Kuma notifications when a specific device goes down, but the request is rejected because it's HTTP POST and I have no way of selecting GET, which the API requires.

### ✔️ Solution

Allow the selection of the HTTP method to use, GET vs POST, when setting up a webhook notification. Alternatively, create a new "Webhook (GET)" notification that sends HTTP GET and doesn't send a POST body which, by definition, isn't applicable to GET.

### ❓ Alternatives

* I have no control over the endpoint to allow HTTP GET directly.
* I could proxy the request through nginx or something that would rewrite the request from POST to GET, but it's an additional level of complexity that shouldn't be necessary.
* Add direct support for Hubitat notifications into Uptime Kuma, but that's definitely the most complex option to build and probably has limited interest.

### 📝 Additional Context

Hubitat API in question: https://docs2.hubitat.com/apps/maker-api

This is not the same as #1734. That issue is for templating of the URL, not explicitly choosing the HTTP method.

Ultimately what I'm trying to do is detect when a specific device on my network goes down, and when it does, invoke the Hubitat API to push a virtual button. On the Hubitat side, that power cycles a smart outlet to reboot the device and bring it back up.

**Comment by CommanderStorm** [comment] 2024-01-23 15:56
Duplicate of #2413

=> closing as such
Note that our contribution guide is here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Closed by CommanderStorm** 2024-01-23 15:56 UTC
Labels: feature-request, area:notifications, type:enhance-existing
