### ISSUE TITLE
Grouping Monitors Without Triggering Parent Uptime Checks

### ISSUE THREAD

**Issue by Karman40** [louislam/uptime-kuma#4129] opened 2023-11-30 15:35 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature

### 🔖 Feature description

I hope this message finds you well. I'm writing to suggest a potential enhancement to your monitoring system that I believe could be highly beneficial for users like myself.

The idea is to implement a "Grouping of Monitors" feature. This would allow users to organize their monitors into a hierarchical folder structure without triggering uptime checks for the parent group. Essentially, it would enable us to categorize and manage monitors more efficiently, without the parent folder/group itself acting as a monitor.

### ✔️ Solution

**Benefits:**

- Enhanced Organization: Users can neatly categorize their monitors, making it easier to manage and navigate through large numbers of monitors.
- Reduced Noise: By preventing the parent group from triggering its own alerts, users would receive notifications strictly relevant to the individual monitors, avoiding unnecessary alerts from the group level.
- Improved Usability: Especially for users with a large set of monitors, this feature would simplify the monitoring dashboard, making it more user-friendly.

**Comment by CommanderStorm** [comment] 2023-11-30 15:38
Are you refering to `Monitor Group`s?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/1fae0ad4-dab6-4161-8eb0-c61fe407fc31)

**Comment by Karman40** [comment] 2023-11-30 15:43
@CommanderStorm thnaks for your reply!

Yes, I tried monitor groups. However, if one of the monitors stops, the group is also considered stopped.

I would like to monitor the 3 monitors separately, I don't need a 4th monitor that monitors the common value.

![image](https://github.com/louislam/uptime-kuma/assets/32225709/4883e107-e6ae-483e-bc5f-3297677d1dd3)

**Comment by CommanderStorm** [comment] 2023-11-30 15:48
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3387 https://github.com/louislam/uptime-kuma/issues/2487 https://github.com/louislam/uptime-kuma/issues/2348 https://github.com/louislam/uptime-kuma/issues/2335
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

Note that https://github.com/louislam/uptime-kuma/pull/1236 is stalled because it has not been updated to work with grouped monitors
⇒ a reattempt via the paths in our contribution guide is possible

**Closed** 2023-11-30 15:56 UTC
Labels: feature-request
