### ISSUE TITLE
Limit email rate and batch the accumulated notifications into one message

### ISSUE THREAD

**Issue by gitwildnow** [louislam/uptime-kuma#2500] opened 2022-12-29 13:27 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Add the option to batch notifications into one email message. Right now if my router goes down I get 33 emails about things being down and then 33 emails about them coming online again - uggh.

I'm looking for a simple batch-time setting. If I tell it to batch for five minutes then when a notification gets queued the timer starts. All the notifications that happen in my five minute window get queued. When the window is done, one email gets sent with all applicable notifications mentioned in the body of the message.

Naturally this delays notification, so set the batch time to something that makes sense for your purposes.

### ✔️ Solution

In the Settings->Notifications set the Batch Time to however many minutes you like. Default is zero, consistent with current behavior.

### 📝 Additional Context

Watching email for uptime kuma notifications.

**Comment by Robin-Sch** [comment] 2023-01-18 19:47
Or maybe have a way to "group" applications. If one goes down, immediately check the rest?? and then send the batch notification.

**Comment by CommanderStorm** [comment] 2023-08-16 23:08
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1137
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by Robin-Sch** [comment] 2023-08-20 11:52
This issue: sending the "service went down" notifications in a batch. Having a setting option which specific the time limit how notifications should be "batched" (for example, setting it to 5 minutes will "batch" together if 2 services go down in those 5 minutes).
#1137: sending a notification with all services which are down. This also requires a settings/timeout like this issue I guess... not sure
- additionally, this issue adds the ability to disable/enable both down and up notifications, so you can only get for example a notification when a service is down and not when a service is back up again.

Let's say yesterday service x went down (and has not come back up), and now service y and z went down.

This issue:
Notification yesterday: service x went down
Notification today: service y and z went down

#1137:
Notification yesterday: service x is down
Notification today: service x, y and z are down

**Comment by CommanderStorm** [comment] 2023-12-04 23:41
@gitwildnow 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #1137 as there is no functional difference (both issues target the ability to group multiple notifications)
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-04 23:41 UTC
Labels: feature-request, area:notifications
