### ISSUE TITLE
Run uptime-kuma behind a reverse proxy subpath

### ISSUE THREAD

**Issue by monsdar** [louislam/uptime-kuma#985] opened 2021-11-30 09:00 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I'd like to run uptime-kuma behind a traefik reverse proxy with a subpath like this: `https://www.mydomain.com/uptime`. It seems that this is not supported, as soon as I land on that page uptime-kuma tries to redirect to `https://www.mydomain.com/dashboard`, which should be `https://www.mydomain.com/uptime/dashboard` then.

Even when trying to connect to `https://www.mydomain.com/uptime/dashboard` I get numerous errors that resources cannot be loaded, all dropping the subpath like the following line: `Loading module from “https://www.mydomain.com/assets/index.3fc36d03.js” was blocked because of a disallowed MIME type (“text/plain”).`

### ✔️ Solution

Allow to set a custom base-url or subpath on startup. There already is `setting("primaryBaseURL")` but I did not find a way to set it without having uptime-kuma running once.

**Comment by louislam** [comment] 2021-11-30 09:23
Duplicate of #147

**Closed by louislam** 2021-11-30 09:23 UTC
Labels: feature-request
