### ISSUE TITLE
Allow change json of webhooks

### ISSUE THREAD

**Issue by Rayzggz** [louislam/uptime-kuma#604] opened 2021-10-08 06:53 UTC
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
Yes
I want to send the notification to DingTalk Bot. But the Webhook json is different between uptime-kuma and DingTalk Bot.

**Describe the solution you'd like**
In uptimerobot.com , I can add WebHook and set the POST Value.
uptimerobot.com will send the json by my format. 
And the json context will replaced by some variables such as *monitorID*  *alertDetails*

**Describe alternatives you've considered**
Now, I write a PHP to receive the webhook from uptime-kuma and change the format that is DingTalk Bot required.

**Additional context**
![image](https://user-images.githubusercontent.com/37480123/136511520-ff8cf5cc-d7e9-477c-be9e-26cba82eec5a.png)
![image](https://user-images.githubusercontent.com/37480123/136511433-87f14422-3ad4-43f6-90e7-ac2f65644803.png)

**Comment by CommanderStorm** [comment] 2023-07-17 23:40
@Rayzggz 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/975
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

This could also have been resolved by https://github.com/louislam/uptime-kuma/pull/3088 which was merged into the [`1.23` release](https://github.com/louislam/uptime-kuma/milestone/34)

**Closed** 2023-07-18 00:33 UTC
Labels: feature-request
