### ISSUE TITLE
Distributed Monitoring

### ISSUE THREAD

**Issue by elimelamed** [louislam/uptime-kuma#3124] opened 2023-05-04 11:47 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Separate the monitoring engine and the database / ui into different containers
providing central server (act as the main db + UI) to connect multiple monitor agents (a.k.a. Probs)  that perform the actual monitoring and send the data to the central application

this will allow scale and monitoring of isolated networks in different locations

### ✔️ Solution

the main server will have the configuration database and the status
Probes will connect via Web Sockets / HTTP 2.0 to the server (Client to server)
Probe will pull the configuration assigned to him and provide consolidated status every X Seconds

The server can use Redis to hold the data to improve performance alongside the Database or as a replacement

**Comment by discostur** [comment] 2023-06-02 09:59
Would be really nice to see this feature! Having separate probes on different locations all over the world would be a real benefit!

**Comment by CommanderStorm** [comment] 2023-06-02 10:09
@elimelamed is this a duplicate of #84
If no, could you make the difference between this proposal and #84 more clear?
If yes, could you close this issue (duplicate issues are not benefitial for project health 😉)

**Comment by CommanderStorm** [comment] 2023-06-02 10:10
@discostur 
> Having separate probes on different locations all over the world would be a real benefit!

Don't the current push-monitors solve this usecase already?

**Comment by pythonmandev** [comment] 2023-09-01 11:19
Can not find a HOWTO about push monitor :(

**Comment by CommanderStorm** [comment] 2023-09-01 12:09
@pythonmandev 
What are you stuck on? (Where do we need to improve the UI-Helptexts?)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/7f4e3f72-d272-4bc6-9e06-4390660bf18e)

**Closed** 2023-09-02 05:30 UTC
Labels: feature-request
