### ISSUE TITLE
Notification: Support for template and variables in telegram messages

### ISSUE THREAD

**Issue by bahamut657** [louislam/uptime-kuma#4961] opened 2024-07-25 15:39 UTC
### 📑 I have found these related issues/pull requests

- #3065

### 🏷️ Feature Request Type

Change to existing notification-provider

### 🔖 Feature description

It should be possible to have the ability to insert custom text and template variables in the Telegram message (now it is sending the notification name but this make the notification not re-usable)

### ✔️ Solution

Support Jinja2 templating like is already available for email

**Comment by CommanderStorm** [comment] 2024-07-26 03:36
Duplicate of #646

**Closed** 2024-07-26 03:36 UTC
Labels: feature-request, area:notifications, type:enhance-existing
