### ISSUE TITLE
SMTP Mail Monitor

### ISSUE THREAD

**Issue by czsquizer** [louislam/uptime-kuma#4936] opened 2024-07-12 11:34 UTC
### 📑 I have found these related issues/pull requests

Have not found

### 🏷️ Feature Request Type

New monitor

### 🔖 Feature description

Hello,
I would like to request SMTP Mail server monitoring, for example as HexTrix Tools has. It would be monitoring if the mail server can receive mails and is on & ready.

### ✔️ Solution

Described above

**Comment by CommanderStorm** [comment] 2024-07-14 23:40
duplicate of https://github.com/louislam/uptime-kuma/issues/3023

**Closed by CommanderStorm** 2024-07-14 23:40 UTC
Labels: feature-request
