### ISSUE TITLE
Send alert if ping is >X ms

### ISSUE THREAD

**Issue by mjalindahl** [louislam/uptime-kuma#2832] opened 2023-02-23 18:54 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Hi there, love UK.  I have quite a few Sonos devices that I monitor via UK.  But, anything over let's say 20ms, I consider that Sonos device to be "down."  Having a really high ping time makes the Sonos not play nicely with the others.

### ✔️ Solution

So, since UK is already my centralized ping monitor, it would be nice to have a notification that alerts me if a device has a ping time of >X ms for Y seconds.

Thanks!

**Comment by mtelgkamp** [comment] 2023-02-24 20:16
Sounds similar to https://github.com/louislam/uptime-kuma/issues/2754, maybe a duplicate?

**Comment by nmcc1212** [comment] 2023-03-24 11:10
also #1813 and the original seems to be #459

**Comment by Natgho** [comment] 2023-05-09 15:11
@louislam @Saibamen please take a look at this . It is important.

**Comment by nmcc1212** [comment] 2023-05-09 15:50
@Natgho dont use this issue. it is a duplicate. use one of the issues i linked above

**Comment by louislam** [comment] 2023-05-09 16:47
Duplicate of #1813

**Closed by louislam** 2023-05-09 16:47 UTC
Labels: feature-request
