### ISSUE TITLE
增加响应时长和异常信息

### ISSUE THREAD

**Issue by gaye746560359** [louislam/uptime-kuma#3440] opened 2023-07-18 01:59 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

1.增加接口响应时长断言并告警
2.增加接口响应内容展示

### ✔️ Solution

1.在接口响应慢的时候能收到告警
2.当接口异常时能看到具体错误信息

**Comment by chakflying** [comment] 2023-07-18 06:33
Duplicate of #877 (PR open in #2142), #2080

**Closed** 2023-07-18 10:33 UTC
Labels: feature-request
