### ISSUE TITLE
Only down if ALL monitors are down

### ISSUE THREAD

**Issue by 12SecondsOfLightning** [louislam/uptime-kuma#4855] opened 2024-06-14 14:31 UTC
### 📑 I have found these related issues/pull requests

None found

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

There is currently a way to group multiple monitors and consider the group to be down, if any of the monitors in the group go down. It would be nice if there was an option to change this between ANY and ALL. That way only if all of the monitors in the group go down a notification is sent that the group is down.

### ✔️ Solution

Lets take a docker container in my homelab for example. I currently run Uptime Kuma on a remote server. The two servers communicate through tailscale mostly. There have been some instances where tailscale goes down and notifications are sent that all my docker containers are down. If I was able to add the tailscale address, a remote push, an external IP address, and the DNS address of the monitored container, I would no longer have to chose which connection is the most reliable. If tailscale goes down, but the DNS still works, Uptime Kuma knows that the monitor is depreciated but still online.

### ❓ Alternatives

I have not found any alternate route of doing this.

**Comment by CommanderStorm** [comment] 2024-06-14 15:39
Duplicate of #3387

**Closed** 2024-06-14 15:39 UTC
Labels: feature-request, area:monitor, type:enhance-existing
