### ISSUE TITLE
[dns] query A fails

### ISSUE THREAD

**Issue by arch1v1st** [louislam/uptime-kuma#860] opened 2021-11-02 02:05 UTC
### 👟 Reproduction steps

Setup a DNS Monitor using the default CloudFlare Resolver Server of 1.1.1.1

### 👍 Expected behavior

Monitor shouldn't trigger as DOWN regularly when the actual domain's DNS is resolving just fine.

To better diagnose the underlying problem I setup a nearly identical UK DNS monitor using Google DNS (8.8.8.8/8.8.4.4), and no UK incidents have been experienced seen since!  The other added bonus - Google DNS seems to support 'ANY/ALL' DNS queries whereas CloudFlare does not, meaning we have a way to gather most of the DNS record types for the domain.

### 👎 Actual Behavior

UK frequently detects the domain's DNS A record as DOWN with the message:

`queryA ESERVFAIL domain.com`

We have many A Record DNS Monitors in place for multiple domain names; experienced this across all of them.

### 🐻 Uptime-Kuma version

1.9.1

### 💻 Operating System

Ubuntu 20.04

### 🌐 Browser

Any

### 🐋 Docker

N/A

### 🏷️ Docker Image Tag

N/A

### 🟩 NodeJS Version

14.8.1

### 📝 Relevant log output

```shell
Up	2021-10-31 01:16:24	Records: 123.123.123.123
Down	2021-10-31 01:15:01	queryA ESERVFAIL domain.com
Up	2021-10-30 19:24:56	Records: 123.123.123.123
Down	2021-10-30 19:23:32	queryA ESERVFAIL domain.com
Up	2021-10-30 15:42:27	Records: 123.123.123.123
Down	2021-10-30 15:41:04	queryA ESERVFAIL domain.com
Up	2021-10-30 12:49:59	Records: 123.123.123.123
Down	2021-10-30 12:48:35	queryA ESERVFAIL domain.com
```

### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by louislam** [comment] 2021-11-02 02:39
I cannot reproduce with 1.1.1.1 

> using Google DNS (8.8.8.8/8.8.4.4), and no UK incidents have been experienced seen since!

Sounds like it is your network issue between 1.1.1.1

**Comment by arch1v1st** [comment] 2021-11-02 02:58
@louislam - thanks your time at looking at this further.  I also found it strange that one of the worlds largest DNS providers (CloudFlare) had these sort of recurring issues (simple A name lookup!), and still scratching my head as to why the UK dns_resolver setting had such a positive impact after switching to Google DNS.  Had both going as their own UK monitors every minute for days, and was getting random daily DOWN notifications for CloudFlare.  Another finer detail here - I am running UK on an AWS medium sized instance - maybe the fact that its on Amazon plays a role with this.

ALL - if you have experienced similar issues, please chime in here!

**Comment by chakflying** [comment] 2021-11-02 03:23
If you are running a large number of DNS monitors, did you test what happens if you switch all of them to 8.8.8.8? In theory `dns.resolve()` should not be overloaded because it's async, but there might be something in the networking stack that's reusing the connection, or maybe it's cloudflare that's implementing a rate limit.

**Comment by arch1v1st** [comment] 2021-11-02 08:11
@chakflying - Running only a handful of DNS monitors overall, and all have been reconfigured to use 8.8.8.8  Started to notice the resolution problems with only 2 at the time against 1.1.1.1.

**Comment by SteveD70** [comment] 2022-04-19 14:05
same issue.  checked and all my DNS servers are live.

**Comment by christopherpickering** [comment] 2022-09-05 13:12
I started getting this after release 18. The only change in the monitor code was the dns cache. I'm using an internal DNS with a ton of monitors, but only three specific monitors for Apache solr are failing. Other sites monitored on the same server resolve properly.

Wonder if it is because of the port or something? The failing urls are like `http://server:8983/solr/` and passing urls are like `http://dns-on-same-server`.

I tried adding the server name to the host file but no luck.

Any other ideas? 

https://github.com/louislam/uptime-kuma/commit/2073f0c28476bb46fb953ecefb9622273e8819d9

**Comment by christopherpickering** [comment] 2022-09-05 13:52
@louislam for my special case, I changed from server name to ip address and it works. I supposed because my server name is not the a record on the dns. I wonder if something changed in node dns resolve function to make this happen because the changes in v18 do not seem to be related to how the dns is resolved.

**Comment by louislam** [comment] 2022-09-05 15:38
> @louislam for my special case, I changed from server name to ip address and it works. I supposed because my server name is not the `A` record on the dns. I wonder if something changed in node dns resolve function to make this happen because the changes in v18 do not seem to be related to how the dns is resolved.

You mean Node.js v18 or Uptime Kuma 1.18.0?

My custom dns with port is working fine. I may need more info.
![image](https://user-images.githubusercontent.com/1336778/188482892-2d3d87e2-f43d-4551-be12-61402e1b555b.png)

**Comment by christopherpickering** [comment] 2022-09-09 08:57
I had a few other monitors one like this that started failing w/ the `queryA ESERVFAIL` and left the server rebooted. I left them and after 1 day they went away. There must be some other cache/matching that happens elsewhere causing it for me... I did reset the server dns cache (which is also probably what happened when the server rebooted).

**Comment by ljurk** [comment] 2022-09-12 11:10
I have the same Issue, starting with kuma version 1.18, I got `queryA ESERVFAIL` for all hostnames, that aren't on public dns-servers, but only on our own Windows-DNS-server. I tried using the 1.17 image and in this version it's working, kuma can resolve all hostnames.
The problem started a week ago and never healed itself

**Comment by christopherpickering** [comment] 2022-09-12 11:35
Do you have a mix of public/not public sites? 
I wonder if it is because the cached lookup key is based on the options (`maxCachedSessions: 0`) and could maybe be based on something that is more unique to the monitor? From the new cache code, it looks like the agent is shared among all the monitors now whereas before it was unique to a monitor. Maybe monitor ID can be added to the cache key?

Here's the code that changed in the last release. Not much changed, but I'm wondering if it is because now the agent is shared whereas before it was not? I'm not a subject matter expert though. 
https://github.com/louislam/uptime-kuma/commit/2073f0c28476bb46fb953ecefb9622273e8819d9

What do you think @louislam ?

**Comment by christopherpickering** [comment] 2022-09-12 14:03
I'm just wondering if they problem w/ the short names is that the cached dns record is shared over every monitor using the same connection options? Should that key be more complex (include the ID of the monitor for example)?

![image](https://user-images.githubusercontent.com/17788706/189674326-ba471b5f-54d3-4fa2-be98-04e5bb8183f9.png)

**Comment by louislam** [comment] 2022-09-12 14:19
> I'm just wondering if they problem w/ the short names is that the cached dns record is shared over every monitor using the same connection options? Should that key be more complex (include the ID of the monitor for example)?
> 
> ![image](https://user-images.githubusercontent.com/17788706/189674326-ba471b5f-54d3-4fa2-be98-04e5bb8183f9.png)

I don't think so, because under same agent options, http agent is reusable. HTTP agent is not specified for only one domain.

You can see the example in https://github.com/szmarczak/cacheable-lookup#attaching-cacheablelookup-to-an-agent


And so far, I do not receive large amount of similar bug reports, so I assumed that it should be very specific issue like @ljurk said, he is using Windows DNS Server

**Comment by ljurk** [comment] 2022-09-12 14:55
@louislam Yeah, I'm inside a windows domain. The domain controller is used for DNS and is running Windows Server. My docker host is running Ubuntu, it gets the dns-ip via dhcp and I didn't change any dns related stuff.

**Comment by dnldpavlik** [comment] 2022-12-09 00:47
I have a similar issue, if not the same issue. My current setup has a PiHole operating as a DNS server where I have defined DNS entries; my Raspberry Pi has its DNS configured to go to the PI for all DNS inquiries. This works fine for all cases to resolve a locally defined address. 

I can ping the address in the uptime container, and it resolves fine, but when using the name in uptime, it gives me a "queryAaaa ESERVFAIL" error. But when I use the static IP address it works fine for the status monitoring of my HTTP site.

**Comment by k11sio** [comment] 2023-01-25 13:45
I'm seeing the same behavior.

Monitors resolving against public DNS (cloudflare) are working fine. Monitors resolving against a private zone in my local network are all failing. It's resolvable from inside the container via ping (using the same DNS server as configured in the monitor). Pihole is being used internally.

**Comment by dnldpavlik** [comment] 2023-01-25 13:48
I have noticed something, when I have internal names that are even numbered, i.e. aaa.bbb.ccc.ddd  or aaa.bbb, it does not resolve, but when it is an odd number of elements for the URI it tends to resolve. aaa.bbb.ccc.ddd.eee or aaa.bbb.ccc. This is not 100%, but it has helped me get some items registered by the DNS entry vs IP, which I prefer the DNS entry.

**Comment by louislam** [comment] 2023-01-25 15:34
Cacheable-lookup is not working properly in some cases.
With 1.19.x, DNS cache now could be disabled in Settings.

**Comment by jvcsw** [comment] 2023-09-28 12:37
> I'm seeing the same behavior.
> 
> Monitors resolving against public DNS (cloudflare) are working fine. Monitors resolving against a private zone in my local network are all failing. It's resolvable from inside the container via ping (using the same DNS server as configured in the monitor). Pihole is being used internally.

Hi, I see that my uptime kuma can't monitor my pihole. Both are containers in the same machine. I guess the same thing happens to me as you, but I don't understand what you say to solve it. Can you explain it to me? thank you

**Comment by louislam** [comment] 2023-09-28 13:18
> > I'm seeing the same behavior.
> > Monitors resolving against public DNS (cloudflare) are working fine. Monitors resolving against a private zone in my local network are all failing. It's resolvable from inside the container via ping (using the same DNS server as configured in the monitor). Pihole is being used internally.
> 
> Hi, I see that my uptime kuma can't monitor my pihole. Both are containers in the same machine. I guess the same thing happens to me as you, but I don't understand what you say to solve it. Can you explain it to me? thank you

Are they in the same docker network?

**Comment by dnldpavlik** [comment] 2023-09-28 13:23
For me they are on different machines, and I am.using pihole for DNS. In order to get it to resolve I originally had ui.app.domain.com, this didn't resolve for uptime, but when I changed the name to app.domain.com it worked,  and also logs.api.app.domain.com would work because it has five parts.["logs","api","app","domain","com"]

**Comment by jvcsw** [comment] 2023-09-28 13:37
> > > I'm seeing the same behavior.
> > > Monitors resolving against public DNS (cloudflare) are working fine. Monitors resolving against a private zone in my local network are all failing. It's resolvable from inside the container via ping (using the same DNS server as configured in the monitor). Pihole is being used internally.
> > 
> > 
> > Hi, I see that my uptime kuma can't monitor my pihole. Both are containers in the same machine. I guess the same thing happens to me as you, but I don't understand what you say to solve it. Can you explain it to me? thank you
> 
> Are they in the same docker network?

No, 
pihole: 172.18.0.7 (docker IP)
u. kuma: 172.16.0.4 (docker IP)

but I use the ip of the host (192.168.1.2) in the same way that other monitors of other containers have the same ip to monitor with ping, etc

**Comment by jvcsw** [comment] 2023-09-28 13:40
> For me they are on different machines, and I am.using pihole for DNS. In order to get it to resolve I originally had ui.app.domain.com, this didn't resolve for uptime, but when I changed the name to app.domain.com it worked, and also logs.api.app.domain.com would work because it has five parts.["logs","api","app","domain","com"]

I only use ip addresses.

**Comment by redfer13** [comment] 2023-09-29 12:57
i seem to have the same problem. they're also on the same docker network (also tried separating it and same problem)
this is my configuration.
![image](https://github.com/louislam/uptime-kuma/assets/62601155/73d36056-d57b-4227-98e1-8d2bc8ab696c)

**Comment by redfer13** [comment] 2023-09-29 12:58
> i seem to have the same problem. they're also on the same docker network (also tried separating it and same problem) this is my configuration. ![image](https://user-images.githubusercontent.com/62601155/271587073-73d36056-d57b-4227-98e1-8d2bc8ab696c.png)

i kept 20seconds for the sake of testing

**Comment by CommanderStorm** [comment] 2024-03-14 12:28
What we need is a CURRENT, publicly accessible and reproducible testcase.
The first part of this issue was resolved when we switchd from cachable lookup to NSCD `(Name Service Cache Daemon)`

![image](https://github.com/louislam/uptime-kuma/assets/26258709/a443a64f-f146-4790-a836-27c3e6ed81ea)

The other comments are likely unrelated to the first one.
I think continuing this issue in less messy smaller issues (=issues which allow reproduction) is more productive rather than piling onto a resolved issue
=> closing as resolved

**Closed by CommanderStorm** 2024-03-14 12:28 UTC
Labels: bug, question, area:monitor

**Comment by AJolly** [comment] 2025-01-25 01:20
So what's the best way to debug? I'm running into the same issue I'm getting look up failures via cloudflare
