### ISSUE TITLE
SNMP Interface Monitoring 

### ISSUE THREAD

**Issue by bsikder** [louislam/uptime-kuma#3366] opened 2023-07-05 19:39 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

SNMP Interface Monitoring 

### ✔️ Solution

SNMP Interface Monitoring 

### 📝 Additional Context

SNMP Interface Monitoring

**Comment by CommanderStorm** [comment] 2023-07-05 20:01
@bsikder 
Is this a duplicate of https://github.com/louislam/uptime-kuma/issues/1675 (which has these duplicates https://github.com/louislam/uptime-kuma/issues/1779, https://github.com/louislam/uptime-kuma/issues/420)?
If yes, please close this issue (duplicates are hard to isssue-manage and create immortal zombies)
If no, why is this a distict issue from the ones mentioned above that it requires a different issue?

**Comment by CommanderStorm** [comment] 2023-12-03 15:38
@bsikder 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #1675 as there is no difference
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-03 15:38 UTC
Labels: feature-request
