### ISSUE TITLE
[Feature]: Group Services

### ISSUE THREAD

**Issue by johnouk** [louislam/uptime-kuma#856] opened 2021-11-01 10:55 UTC
### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be amazing to be able to create groups, example for locations or service types eg cpanel servers, email servers, game servers, would be great to see this.

### ✔️ Solution

Create groups page then allow selection when adding monitors,

### ❓ Alternatives

N/a

### 📝 Additional Context

None

### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

**Comment by chakflying** [comment] 2021-11-01 14:29
Duplicate of #12, #639 and many others.

**Closed** 2021-11-01 14:43 UTC
Labels: enhancement
