### ISSUE TITLE
Geographic Map Integration

### ISSUE THREAD

**Issue by nckrwlmn** [louislam/uptime-kuma#4838] opened 2024-06-08 04:58 UTC
### 📑 I have found these related issues/pull requests

I have found no related issues. I have however found some other people online who are looking for this feature.

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

There should be a satellite map integrated into the dashboard where the user can click and drag a monitor onto the map and place it at the geographical location of the IP or service being monitored. Additionally there should be the option to drag lines between the "nodes", and those lines should change colors with the state of the downstream monitor. 

### ✔️ Solution

I am looking to monitor a huge amount of IPs spread out over thousands of acres, not unlike an ISP would do. This feature would help me to see at a glance where the problem lies geographically, if one should arise.

### ❓ Alternatives

SNMP monitoring services probably have this, but why mess with those when you have a simple UptimeKuma interface?

### 📝 Additional Context

I have no more context, but will probably add more ideas to this request as i think of them.

**Comment by CommanderStorm** [comment] 2024-06-08 11:53
Duplicate of https://github.com/louislam/uptime-kuma/issues/2410

I don't see how this can be done in a simple way while sticking to our simple UX.

I am going to classify this as out of scope/ https://github.com/louislam/uptime-kuma/labels/wontfix.
We are a simple uptime management software => You can model your relationships via groups, but I don't think that adding a network map is something that we can do while sticking to our core UX.
If you have concrete UX proposals, we can still talk about them and reconsider.

Understanding network topologies is not as simple as displaying lines on a map. That would need either:
- https://github.com/louislam/uptime-kuma/issues/4031
- https://github.com/louislam/uptime-kuma/issues/84
- https://github.com/louislam/uptime-kuma/issues/4795

Adding geo-services would add an entirely different level of bagage (how do you set where nodes are? GeoIP? Via which provider? Where do we get our tiles from? What software stack is used? ...)

**Closed** 2024-06-08 11:53 UTC
Labels: feature-request, wontfix, area:dashboard

**Comment by nckrwlmn** [comment] 2024-06-08 17:13
Its not about understanding network topologies. It's simply about giving a visual overview to the things being monitored rather than just a list. So scrap the goip locating. Just have nodes on a flat black map (or static image) that can be connected one to the other. The connections literally don't have to mean anything. The user will place them in a way that he knows that they are located in space and time, and connect them together. So if one radio link somewhere or a switch goes down, it would follow that everything downstream from there would also go down. They would have to take one look at this map and see where the problem stems from .The user will have to arrange them in a way that he knows they are in real life.

**Comment by gtsbahamas** [comment] 2026-08-04 17:06
Took a run at this. Monitors as lighthouses on a coastal chart: group is a cove, down is a storm cell, pending is haze, maintenance is a dry-dock pennant, 24h uptime is a tide mark on the base.

![Harbor Master demo](https://raw.githubusercontent.com/gtsbahamas/kuma-coastal-watch/master/harbor-master-demo.gif)

It reads the public status-page JSON for the view, and for the acting side it signs in with your own credentials and uses the same socket API the dashboard uses: add, pause, resume, group membership via `saveStatusPage`, maintenance, incidents. Nothing forked, nothing patched, no plugin hook needed. It runs beside an unmodified 1.23 instance behind a small proxy.

Not proposing this for core and not affiliated with the project. Putting it in the thread because people keep asking for a map and now there's one to try. Live chart: https://coast.algome.ai · MIT: https://github.com/gtsbahamas/kuma-coastal-watch

**Comment by nckrwlmn** [comment] 2026-08-05 19:15
Ahoy there, matey. I be not sure what's with the nautical dashboard, but what does this have anything to do with a geographical or a spatial representation of the monitors?
