### ISSUE TITLE
Webhooks with GET request

### ISSUE THREAD

**Issue by stoehrmark** [louislam/uptime-kuma#4328] opened 2024-01-05 16:06 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Use only the URL in webhooks to send monitor data

### ✔️ Solution

I want to send a notification with webhooks to a PHP server with a GET request directly in the URL. 
Something like http://www.url.com/xxxxxxx.php?thetitle=title&themessage=message. 
The Title or Body should include information about the Monitors status up/down, name, date, time, etc.
 xxxxxxx.php?thetitle=monitorFriendlyName&themessage=monitorStatus

**Comment by CommanderStorm** [comment] 2024-01-05 18:01
Duplicate of https://github.com/louislam/uptime-kuma/issues/1734

**Closed by CommanderStorm** 2024-01-05 18:01 UTC
Labels: feature-request, area:notifications
