### ISSUE TITLE
Multiple Status Screen's by Group

### ISSUE THREAD

**Issue by dmkjr** [louislam/uptime-kuma#1077] opened 2021-12-18 18:43 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

We have a desire to create a few different status pages specific to customers that may be utilizing the services.  For example, if their phone system is down, we can display a message where we are working on it and showing if the service should be up.  Is this currently possible or should we just create different instances if we cannot group the different 'clients' with a status?

Thanks in advance!

### ✔️ Solution

If we could create a status page for say /customer1 and then one for /customer2 or even /group1 or /group2 That sould help a lot.

**Comment by chakflying** [comment] 2021-12-18 19:43
Duplicate of #530

**Closed** 2021-12-19 22:49 UTC
Labels: feature-request
