### ISSUE TITLE
Auto order Left Panel 

### ISSUE THREAD

**Issue by Stuart-harper** [louislam/uptime-kuma#3162] opened 2023-05-15 10:39 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

On the main home page where the quick stats part is, the left hand colum which shows all the servers should be able to re order its self and if a server is down show the server at the top of that list, as a  quick way to see what is down  in a simple format

### ✔️ Solution

Make it so the left column on the home page puts down Devices to the top. 

### ❓ Alternatives

a drop down to select the feature to be enabled or disabled.

**Comment by CommanderStorm** [comment] 2023-05-19 10:29
This is a duplicate of #1585

**Closed** 2023-08-11 07:44 UTC
Labels: feature-request
