### ISSUE TITLE
Request to add support for Synology Chat service

### ISSUE THREAD

**Issue by onlyhooops** [louislam/uptime-kuma#4283] opened 2023-12-26 16:31 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Request to add support for [Synology Chat service](https://www.synology.com/zh-tw/dsm/feature/chat)：Synology Chat service is a convenient and free messaging service that allows for better integration and reception of various types of notification messages.

### ✔️ Solution

By utilizing the integrated message receiving interface in Synology Chat service, it is easy to set up and receive push notifications.

### 📝 Additional Context

Thank you very much for your contribution. I salute you！

**Comment by CommanderStorm** [comment] 2023-12-26 18:32
Duplicate of #1160

> [!NOTE]
> our [contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and notfications can be added like this #4219

**Closed by CommanderStorm** 2023-12-26 18:32 UTC
Labels: feature-request, area:notifications, type:new
