### ISSUE TITLE
show intervals in human readable form

### ISSUE THREAD

**Issue by tomaszduda23** [louislam/uptime-kuma#4299] opened 2023-12-29 16:13 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Display intervals in more clear form.

### ✔️ Solution

as-it: Heartbeat Interval (Check every 100800 seconds)
to-be: Heartbeat Interval (Check every 1 day, 4 hours)

**Comment by CommanderStorm** [comment] 2023-12-29 18:12
Duplicate of #3601

**Closed by CommanderStorm** 2023-12-29 18:12 UTC
Labels: feature-request, area:dashboard
