### ISSUE TITLE
[Feature] Display all down status [RED] on top of the page on Status page 

### ISSUE THREAD

**Issue by cs-michaelc** [louislam/uptime-kuma#866] opened 2021-11-02 23:15 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

[Feature] Display all down status [RED] on top of the page on the Status page

### ✔️ Solution

Disply failed services on top

**Comment by deefdragon** [comment] 2021-11-03 02:16
I think this is basically a duplicate of #654

**Closed** 2021-11-03 05:11 UTC
Labels: enhancement

**Comment by cs-michaelc** [comment] 2021-11-03 05:16
Oops. Cool thank you
