### ISSUE TITLE
Make E-mail message content configureable.

### ISSUE THREAD

**Issue by taavit21** [louislam/uptime-kuma#3495] opened 2023-07-28 05:40 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

For example there is a another software that i have been for monitoring and that is PHP Server Monitor.

I´l, add a screnshot to explain the context and what i´d like to see.

![image](https://github.com/louislam/uptime-kuma/assets/47745930/060599ff-11d4-474a-9491-b478bc49506e)

vs

![image](https://github.com/louislam/uptime-kuma/assets/47745930/822b019e-78f2-4ff9-9f7a-affab7ed6fa7)

Could we add a functionality where we can also add more informatsion to message body?

### ✔️ Solution

You need to change the code a bit inorder to do that.

**Comment by CommanderStorm** [comment] 2023-07-28 11:09
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3032 and duplicates like https://github.com/louislam/uptime-kuma/issues/3191, https://github.com/louislam/uptime-kuma/issues/2661
Also see Pull request doing work in this area which have encountered problems: https://github.com/louislam/uptime-kuma/pull/3414
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-07-28 11:27 UTC
Labels: feature-request
