### ISSUE TITLE
Create dashboard with all monitors with specific tag

### ISSUE THREAD

**Issue by acdoussan** [louislam/uptime-kuma#1726] opened 2022-06-05 20:37 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I'd like to be able to create a dashboard based off of a tag, or some set of tags, and have the dashboard automatically include all monitors with that tag. If a new monitor is created with a tag, that monitor should automatically be included in the dashboard.

### ✔️ Solution

Maybe a toggle on the UI that lets you switch between choosing monitors or tags? Or, allow the user to choose either tags for a group, or select individual monitors.

**Comment by QuentinDEME97** [comment] 2023-01-20 09:55
+1 for this.

Would be also nice to `sort` or `group by` monitors by label.

**Comment by mutasim** [comment] 2023-05-19 11:23
+1

**Comment by CommanderStorm** [comment] 2023-05-19 11:25
@QuentinDEME97 @mutasim please show your support by adding tumb-ups to the issue and not commenting `+1` or similar, as this makes issue management way harder.

**Comment by CommanderStorm** [comment] 2023-06-11 21:14
@acdoussan  a very similar feature has been implemented+merged.
Any version after [`1.22.0-beta.0`](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0-beta.0) supports this.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2b8673a3-214f-449f-a7fd-675c6dacc8db)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2a188e08-0774-402e-92e7-c18da04c0026)

Could you close this Issue, if this has been resolved?

**Comment by CommanderStorm** [comment] 2023-06-11 21:16
If not, is this a duplicate of https://github.com/louislam/uptime-kuma/issues/651?

**Comment by CommanderStorm** [comment] 2023-12-05 09:24
@acdoussan 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #651 as there is no functional difference
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-05 09:24 UTC
Labels: feature-request
