### ISSUE TITLE
Alert on ping and tcp connect time

### ISSUE THREAD

**Issue by d3xt3r01** [louislam/uptime-kuma#1082] opened 2021-12-20 11:43 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be very helpful to validate the ping and tcp connect time for the tcp checks to validate network load or machine load.

### ✔️ Solution

in the tcp and other checks that do pings I would like an option to specify some thresholds. If a tcp check / http check / ping is 5 seconds, it's already too much and there must be an issue somewhere

**Comment by CommanderStorm** [comment] 2023-12-08 12:44
Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/1813

**Closed by CommanderStorm** 2023-12-08 12:44 UTC
Labels: feature-request, area:monitor
