### ISSUE TITLE
Up/Down Monitor Count Summary Notification

### ISSUE THREAD

**Issue by rwjack** [louislam/uptime-kuma#4293] opened 2023-12-27 20:25 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Sometimes when I'm messing around with the infrastructure, I get a bunch of Up/Down notifications, but I lose track if I've actually fixed everything, and if everything is up and operational, unless I open the web UI and look at the stats:

![image](https://github.com/louislam/uptime-kuma/assets/59068073/20c40bed-f463-4660-a520-4725139701d5)

### ✔️ Solution

An occasional notification, or perhaps included with every Up/Down notification, that shows the complete stats

Instead of:

```
[UAP Hallway] [🔴 Down] PING [uap-hallway.home.arpa](http://uap-hallway.home.arpa/) ([REDACTED]) 56(84) bytes of data.

--- [uap-hallway.home.arpa](http://uap-hallway.home.arpa/) ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 218ms


... Bunch of other notifications here ...


[UAP Hallway] [✅ Up] 
```

Send something like:
```
[ 1 / 45 services Down ]
[UAP Hallway] [🔴 Down] PING [uap-hallway.home.arpa](http://uap-hallway.home.arpa/) ([REDACTED]) 56(84) bytes of data.

--- [uap-hallway.home.arpa](http://uap-hallway.home.arpa/) ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 218ms


... Bunch of other notifications here ...


[ Fully Operational ]
[UAP Hallway] [✅ Up] 
```

---

Or perhaps sending this info with every notification might be too much clutter. Another option would be to send this info every X changes. 

If X is 3:
2 services go down, 1 comes back up, send summary notification.

If X is 4:
3 services go down, 1 comes back up, send summary notification.

etc.

**Comment by CommanderStorm** [comment] 2023-12-27 21:08
Closing as a duplicate of:
- summary status in one notification: https://github.com/louislam/uptime-kuma/issues/2349
- summarising notifications intoone notification: https://github.com/louislam/uptime-kuma/issues/1534
- customising individual notifications: https://github.com/louislam/uptime-kuma/issues/646

**Closed by CommanderStorm** 2023-12-27 21:08 UTC
Labels: feature-request, area:monitor, area:notifications
