### ISSUE TITLE
[Feature] Combined Monitors

### ISSUE THREAD

**Issue by Horstexplorer** [louislam/uptime-kuma#874] opened 2021-11-03 23:53 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Id like to see a way in which we could not just organize monitors to named but also logical groups.

### ✔️ Solution

Currently, we can group the monitors on the status page, which unfortunately is only possible on a single level.
This does not allow us to adequately display clusters running in high availability configurations.
Example: Consider a set of web servers that provide redundancy for their application. Each of these web servers would have its own monitor. 
I would like to have a way to display the availability of this application as a sum of the individual monitors of these web servers, preferably with more detail than just up or down (like degraded or critical; depending on how many of the monitors are down).

**Comment by deefdragon** [comment] 2021-11-04 01:00
duplicate of #468 et. all.

**Comment by Horstexplorer** [comment] 2021-11-04 01:51
Not everything which involves groups is automatically a duplicate of something that involves groups.

**Comment by chakflying** [comment] 2021-11-04 02:42
Thanks for your suggestion, but grouping really has been discussed many times before, I think your use case is already covered by #639 and I don't think there is a reason to have another issue open about it.

**Comment by deefdragon** [comment] 2021-11-04 02:42
Grouping of notifications is one of THE most requested features. The reason that there are so many other issues referenced to, and referencing 468, is because of this.

Different people want different things in regards to grouping. It's MUCH easier for work to be done on it when all the potential aspects of that feature are all in one location. Then the trade-offs of different methods of implementation, what should be focused on, how to display it, what to work on first vs what to push to the future etc. can be discussed in one location.

While it looks like a bit of a mess as a result until someone takes on the task of sorting it all, its better than missing something in the feature request log. As such, this is better as a comment/addition to 468.

**Comment by louislam** [comment] 2021-11-04 03:21
> Thanks for your suggestion, but grouping really has been discussed many times before, I think your use case is already covered by #639 and I don't think there is a reason to have another issue open about it.

Duplicate of #639

**Closed by louislam** 2021-11-04 03:21 UTC
Labels: enhancement
