### ISSUE TITLE
Is it possible to configure the content of status page to be displayed by day?

### ISSUE THREAD

**Issue by uspd5** [louislam/uptime-kuma#4839] opened 2024-06-08 09:44 UTC
### 📑 I have found these related issues/pull requests

Currently, page status displays the status according to the refresh time. For example, if a monitoring item is refreshed every 60 seconds, it will be displayed at the same frequency on page status. But in some scenarios, such as displaying service status to customers, this refresh frequency is too fast. External users need a wider time span to confirm whether the service is available, such as displaying it by day. I referred to uptimerobot, which is Processed according to this logic.

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

The status page can display data in user-configured time units.

### ✔️ Solution

Is it possible to configure a display time unit for the status page? For example, if you select day, the status page will be displayed based on the day dimension; if you select hour, the status page will be displayed based on the hour.

**Comment by CommanderStorm** [comment] 2024-06-08 11:57
Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/1888

Please refer to https://github.com/louislam/uptime-kuma/issues/1888#issuecomment-2068191172 for the current status

**Closed by CommanderStorm** 2024-06-08 11:57 UTC
Labels: feature-request, area:status-page
