### ISSUE TITLE
need a sign up button

### ISSUE THREAD

**Issue by p6oy** [louislam/uptime-kuma#3518] opened 2023-08-03 01:30 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

i have friends who has websites, and i wanna use uptime with him, but i dont wanna give him my password

### ✔️ Solution

add a signup button

### ❓ Alternatives

they can signup by themselves from this button

**Comment by chakflying** [comment] 2023-08-03 02:02
Duplicate of #128

**Comment by CommanderStorm** [comment] 2023-08-03 12:43
@chakflying 

One thing that might be helpful for you (a GitHub feature I recently discovered) is this button:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/59f0a972-15e0-4191-913c-d595fa3a5ef2)

**Closed** 2023-08-11 16:28 UTC
Labels: feature-request
