### ISSUE TITLE
Statistics Database Option

### ISSUE THREAD

**Issue by tamimology** [louislam/uptime-kuma#1361] opened 2022-03-07 06:28 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

If there could be an option passed to have the statistics db recorded in an external platform, i.e. MariaDB / InfluxDB ...etc

### ✔️ Solution

-

### ❓ Alternatives

-

### 📝 Additional Context

-

**Comment by koen20** [comment] 2022-03-13 22:53
This is partially a duplicate of #953 #959 #1139

**Comment by almereyda** [comment] 2022-12-14 15:12
If you only need the metrics persisted into a database, then you may wish to look into TSDBs that support the Prometheus protocol, and leverage that to build a "statistics database", like you supposed with InfluxDB:

- https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration

**Comment by nodecentral** [comment] 2023-01-08 10:20
Just a thought, (as I use influxdb too) as data can be posted to Influxdb via their API, is that something that can be supported?

By the looks of it, it could be provided in very simular way to how websocket for notifications is set up, just with slightly different options and the ability for it to pass some value that can be placed into a structured URL

**Comment by CommanderStorm** [comment] 2023-12-03 19:07
`v2` will come with the ability to run mariadb/mysql as a database and includes perfomrance improvments like https://github.com/louislam/uptime-kuma/pull/2750

during the PR mettioned above we have evaluated some time series databases and have found them to not fit the direction in which we want the project to go in terms of resource consumption. We have instead gone with running aggregation as an optimisation for our statistics.

=> closing as resolved

**Closed by CommanderStorm** 2023-12-03 19:07 UTC
Labels: feature-request
