### ISSUE TITLE
Monthly .pdf Report via Email/Telegram

### ISSUE THREAD

**Issue by NEBELWAENDE** [louislam/uptime-kuma#3764] opened 2023-09-19 06:17 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Scheduled .pdf Report with Text and Graphs on a monthly basis

### ✔️ Solution

toe be able to schedule a .pdf Report that is sent via Email/Telegram on a Monthly Basis.

### ❓ Alternatives

Make Screenshots of the WebUI of uptime kuma

### 📝 Additional Context

.

**Comment by CommanderStorm** [comment] 2023-09-19 18:45
@NEBELWAENDE 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2028 and https://github.com/louislam/uptime-kuma/issues/1959
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by NEBELWAENDE** [comment] 2023-09-20 03:34
I apologize.

**Comment by NEBELWAENDE** [comment] 2023-09-20 03:35
Still needed

**Comment by NEBELWAENDE** [comment] 2023-09-20 03:35
Thank you for Response

**Closed** 2023-09-20 03:35 UTC
Labels: feature-request

**Comment by rondamstra** [comment] 2026-06-12 11:43
Hi folks — I’m exploring a small external add-on for this exact use case: scheduled PDF/CSV reports for Uptime Kuma, with Telegram/webhook delivery and optional client branding.

The goal is not to replace Uptime Kuma or ask maintainers to add more work. I’m trying to see whether an external report generator would be useful for people who currently take screenshots or manually export data.

Sample mock report: https://uptime-kuma-reportbot.mor-online.nl/sample-report
Landing/demo: https://uptime-kuma-reportbot.mor-online.nl/

Questions:

1. Would you use this for yourself, or mainly for client reporting?
2. Is PDF required, or would CSV/HTML report links be enough?
3. Would Telegram/webhook/Slack delivery be useful?
4. Would you prefer hosted SaaS, self-hosted, or both?

If this is unwanted/noisy here, I’m happy to remove the comment.
