### ISSUE TITLE
Improve resolution notification with some additional information

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#1970] opened 2022-08-04 08:03 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, Other

### 🔖 Feature description

Improve resolution notification with some additional information:
- DOWN DATE
- DATE OF UP(ALREADY PRESENT)
- TOTAL DOWN DURATION

### ✔️ Solution

Improve resolution notification with some additional information:
- DOWN DATE
- DATE OF UP(ALREADY PRESENT)
- TOTAL DOWN DURATION

### ❓ Alternatives

NC

### 📝 Additional Context

NC

**Comment by lazyjeffllc** [comment] 2023-01-06 22:12
Forgive my ignorance, how does this feature request get performed? We just wait for someone to work it or does louislam have to add this feature?

**Comment by EdyDeveloper** [comment] 2023-05-28 15:20
Bump
This would be awesome. It would allow me to stop using HetrixTools entirely. It's really handy to have all this info so that you don't have to do a bunch of math in your head, especially when you have lots of monitored services.

**Comment by CommanderStorm** [comment] 2023-05-28 15:49
@honestlai @EdyDeveloper 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by CommanderStorm** [comment] 2023-05-28 15:53
@mabed-fr 
What exactly is your feature request?
Is this a duplicate of Templating (#975) or #2362?
If it is not, please edit your issue to make it more clear ^^

**Comment by CommanderStorm** [comment] 2023-05-28 15:56
@lazyjeffllc 
> Forgive my ignorance, how does this feature request get performed? We just wait for someone to work it or does louislam have to add this feature?

The Contribution guide is at https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by mabed-fr** [comment] 2023-05-28 16:52
Yes these are the same features, but none are started. Unfortunately I don't have the required skills. I can only be useful for the system network and DevOps side

**Comment by CommanderStorm** [comment] 2023-05-28 20:17
> Yes these are the same features

Please close this PR then 😉
Duplicates just make managing issues harder 

> none are started.

My plan to improve upon this state is:
- reformat the monitors see PR #3182
- make sure that all notification providers code looks similar (see [zoho-cliq](https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/zoho-cliq.js) vs [telegram](https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/telegram.js) for what I mean)
- fix that some monitors handle down/up vs general notifications differently
- after upon improving on the code quality in this area, these features will be easier


>I can only be useful for the system network and DevOps side

As mentioned in #1349, this project was lacking in this department. In the past year, it got better a lot, but we are not quite in a place I would call happy.
Louis seems to like manual processes for release management (see https://github.com/louislam/uptime-kuma/pull/213), but all testing PRs have been accepting ⇒ A PR adding more (unit)tests would likely be accepted and improve future reviews.
Also note #2720

**Comment by CommanderStorm** [comment] 2023-08-31 09:17
> Yes these are the same features

@mabed-fr ?

**Comment by CommanderStorm** [comment] 2023-12-06 10:11
> Yes these are the same features

Closing as a duplicate as discussed above

**Closed by CommanderStorm** 2023-12-06 10:11 UTC
Labels: feature-request
