### ISSUE TITLE
Shorten or Expand catagory

### ISSUE THREAD

**Issue by oPqnda** [louislam/uptime-kuma#1121] opened 2022-01-03 23:32 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Possibly make it so you can shorten or expand groups on the main status page so you aren't endlessly scrolling

### ✔️ Solution

For example. If you have multiple statuses in one group and say if its a lot of statuses, you should be able to shorten that group so then you aren't endless scrolling to get other status groups.

**Comment by CommanderStorm** [comment] 2023-06-11 21:35
@oPqnda 
Is this a duplicate of #1968? 
If yes, could we close this issue as
- we use [👍🏻 ](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+) to guage user interest
- imo the other isue is written clearer

**Comment by CommanderStorm** [comment] 2024-02-12 16:31
Closing as a duplicate as https://github.com/louislam/uptime-kuma/issues/1968

**Closed by CommanderStorm** 2024-02-12 16:31 UTC
Labels: feature-request, area:status-page
