### ISSUE TITLE
Custom notification text  per entry

### ISSUE THREAD

**Issue by LazydaveZ** [louislam/uptime-kuma#4768] opened 2024-05-17 11:15 UTC
### 📑 I have found these related issues/pull requests

none

### 🏷️ Feature Request Type

Change to existing notification-provider, Settings

### 🔖 Feature description

I would like to request a feature that allows users to send custom messages within notifications. This feature would be beneficial for including specific information or directing recipients to relevant documentation URLs.

### ✔️ Solution

The ability to add custom messages to notifications would enhance the utility of Uptime Kuma by allowing users to:

Provide Context: Include specific details about the alert, reducing ambiguity and helping recipients understand the issue quickly.

Direct to Resources: Share URLs to relevant documentation or support resources, enabling recipients to troubleshoot or respond to issues more effectively.

Personalize Communication: Tailor messages based on the nature of the alert, improving communication and response times.
This feature would significantly improve the user experience by making notifications more informative and actionable.

**Comment by CommanderStorm** [comment] 2024-05-17 12:52
I think this is a duplicate of either of these two:
- https://github.com/louislam/uptime-kuma/issues/3065
- https://github.com/louislam/uptime-kuma/issues/646

=> I am going to close this as a duplicate

**Closed by CommanderStorm** 2024-05-17 12:52 UTC
Labels: feature-request, area:notifications
