### ISSUE TITLE
Limit returned metrics by filter

### ISSUE THREAD

**Issue by mikee2** [louislam/uptime-kuma#3731] opened 2023-09-11 20:53 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

When you request the metrics page you get metrics from ALL configured monitors. It would be nice if you could get the metrics of a given monitor or of a group of monitors.

I have written a python script to get metrics and convert them to influxdb format so that we can follow them with grafana but as the number of metrics handled by kuma increase I start wasting not only bandwith but CPU time to extract the info I want (I push different data into different influx databases for different customers).

My script filters on monitor names by regex expressions but it would be better if I could request only the monitors I am interested in in the first place.

Something like http://url/metrics?names=<group name or monitor name or monitor regular expression like abc*> would be great.

Anyway thanks for a very useful tool.

### ✔️ Solution

When filter is applied only the data from the selected monitors will be delivered in the reply.

**Comment by CommanderStorm** [comment] 2023-09-14 13:54
Filtering them on the server would not be more performant, given how incredibly efficient regexes are.
=> CPU time would not be less if this were filtered inside uptime-kuma
=> network bandwidth should also be minimal given the size of the file that is being transmitted.
Given that the metrics is just a text file, this can be well encoded using `deflae`/`gzip` or `br`, which it currently is not implemented. If you'd like to tackle this, here is our contribution guide https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

I think there is some context that I am missing, or your code has a bug making it slower than it needs to.
Could you share the code you wrote?

**Comment by CommanderStorm** [comment] 2023-09-14 15:01
First of all: Why do you need this to execute in less than 400ms?

So I profiled a bit agains the code you wrote here https://github.com/mikee2/kuma2influx/blob/main/kuma2influx.py:

Most of the time is spend actually downloading the request:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/a189174f-1166-4323-a48e-ee3ef4f9db20)

Said time is spent like this:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/b8dc4590-fec1-401e-ae20-bc3b0ec774fc)

Splitting this up into more requests would not make this more time-efficient, likely less time-efficient.

Said request takes ~14 kB/request. => The amount of bandwidth this takes is miniscule.
Compressibility (according to https://www.multiutil.com/text-to-brotli-compress/):
- gzip/deflate: ~2kb
- brotli: ~1kb

**Comment by CommanderStorm** [comment] 2023-09-14 15:04
Assuming you are refreshing influxdb every 5m: 14kB*5*24*30 = 50.4 MB/Month of bandwith

**Comment by mikee2** [comment] 2023-09-17 16:43
It is not a matter of how long it takes to process the full listing or how many bandwidth you use, it is more a matter of why you need to receive, say, 1000 entries if you need only the info about two of them.

Adding to this there is a very useful value that is not being sent that is the SLA value, the percentage of valid tries. This is even more useful when related to groups: getting the SLA of a group allows you to deploy very easy informative panels.

The code you are referring to is in github already in my repository kuma2influx

**Comment by mikee2** [comment] 2023-09-17 16:58
It is not a matter of how long it takes to process the full listing or how many bandwidth you use, it is more a matter of why you need to receive, say, 1000 entries if you need only the info about two of them.

Adding to this there is a very useful value that is not being sent at all, that is the SLA of the monitored entry , the percentage of valid tries that is shown in screen. This is even more useful when related to groups: getting the SLA of a group allows you to deploy very easy informative panels with minimum effort.

The code you are referring to is in github already in my repository kuma2influx

**Comment by CommanderStorm** [comment] 2023-09-17 17:04
> It is not a matter of how long it takes to process the full listing or how many bandwidth you use, it is more a matter of why you need to receive, say, 1000 entries if you need only the info about two of them.

Please make a real argument instead of "just-because" justifications.
The problem is not the CPU, nor bandwidth, nor time as I understand it.
I don't quite understand why you want this functionality.

**Comment by mikee2** [comment] 2023-09-17 17:30
Efifciency?

**Comment by CommanderStorm** [comment] 2023-09-17 22:29
Please elaborate (show benchmarks if possible):
In what way would this solution be more efficient? What is efficiency for you anyhow?

In your own words:

> It is not a matter of how long it takes to process the full listing or how many bandwidth you use

**Comment by mikee2** [comment] 2023-09-18 15:53
I do not need any benchmarks. If you do not understand that it is better, and a lot more efficient under all aspects, to filter as close as the source as possible then there is no point in trying to explain anything.

**Comment by CommanderStorm** [comment] 2024-01-18 17:41
> I do not need any benchmarks

I don't think adding the additional complexity of this feature does add value.
I am going to close this as not planned.
If you/somebody elses creates benchmarks that prove this beneficial enough to outweigh the additional maintence effort, we can reopen this issue.

**Closed by CommanderStorm** 2024-01-18 17:41 UTC
Labels: feature-request, question, wontfix, area:metrics
