### ISSUE TITLE
Alert for Maintenance Window

### ISSUE THREAD

**Issue by jpulley101** [louislam/uptime-kuma#3210] opened 2023-05-31 02:07 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Can we add where I can send notifications to Discord or email when I enable Maintenance Windows to let everyone know whats going on.

### ✔️ Solution

Would like to let people know when I enable a Maintenance Window.

### ❓ Alternatives

None really.

**Comment by CommanderStorm** [comment] 2023-05-31 12:25
Is this a duplicate of #2722?
If no, please edit your issue to make it more distinct.
If yes, please close this issue, as duplicate issues just make issue-management harder. ^^

Also maybe duplicates depending on meaning: #3022 or #3170

**Closed** 2023-05-31 13:37 UTC
Labels: feature-request
