### ISSUE TITLE
Add option to edit tags

### ISSUE THREAD

**Issue by SagnikSRHUSE** [louislam/uptime-kuma#981] opened 2021-11-29 02:40 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

At times, there's a need to replace tags or change colors on multiple monitors and being able to edit the tags directly would be perfect.

### ✔️ Solution

An option to edit (color/name) and delete tags would be nice to have,

**Comment by chakflying** [comment] 2021-11-29 04:14
Duplicate of #868, but thanks for more info on your use case.

Don't have time to work on this, but I think adding a tags section in the new settings page would make sense.

**Closed** 2021-11-29 06:31 UTC
Labels: feature-request
