### ISSUE TITLE
Limit access to different status pages (password restricted)

### ISSUE THREAD

**Issue by mathiskir** [louislam/uptime-kuma#1401] opened 2022-03-21 21:48 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I would like to be able to set a password for example for status page a and let status page b be public.
(Louislam just made it possible to create multiple pages)

### ✔️ Solution

It could be using a password or requiring login with the admin account etc.

### ❓ Alternatives

-

### 📝 Additional Context

-

**Comment by mathiskir** [comment] 2022-03-22 20:49
I just tested the beta (1.13.0-beta.2) it's great, ty so much!

**Comment by val123456** [comment] 2022-03-23 19:52
I protect various paths (URLs) by using a reverse proxy server in front with basic HTTP auth.  Get SSL that way too.  :-)

**Comment by mathiskir** [comment] 2022-03-24 18:59
> I protect various paths (URLs) by using a reverse proxy server in front with basic HTTP auth. Get SSL that way too. :-)
its a good way but i want it to be implemented into uptime kuma

**Comment by wrench12435678** [comment] 2022-05-25 09:44
This would be usefull or at least if you add a domain name, it only is acsessible if coming from that domain.

**Comment by SteffoSpieler** [comment] 2022-12-08 13:11
Would be great if it would be possible to set a custom password per status page.

**Comment by CommanderStorm** [comment] 2023-07-03 16:05
@mathiskir 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1050
If you agree please close this issue, as issue-management is harder with zombies hanging around.
If you disagree, what is the difference?

**Comment by CommanderStorm** [comment] 2023-12-03 23:27
@mathiskir 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #1050 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-03 23:27 UTC
Labels: feature-request
