### ISSUE TITLE
DNS Check with support for searching for (a part) value.

### ISSUE THREAD

**Issue by josefglatz** [louislam/uptime-kuma#1938] opened 2022-07-25 06:09 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

The DNS check is great! However it would be a real benefit if it is also possible to search (nonregex oder regex) for patterns in e.g. all or a specific TXT entry.

For example: Check SPF Record if the string "`include:foobar.com`" is included.

### ✔️ Solution

In my use-case this is something the HTTP(s) Checks also supports with Content.

### ❓ Alternatives

None found

### 📝 Additional Context

-

**Comment by jeifour** [comment] 2022-08-02 10:36
Not just TXT entry, this would be useful for pretty much every type of DNS entry. For example I want to monitor if A entry still points to a certain server or NS are still the same.

**Comment by ndizazzo** [comment] 2022-10-27 01:22
> For example I want to monitor if A entry still points to a certain server or NS are still the same.

Or the inverse (support `upside-down mode`), I want to see if my PiHole is returning anything except `0.0.0.0` for a specific domain to test if the FTL service has crashed or the AdList was modified.

**Comment by harveydov** [comment] 2023-01-09 15:02
I agree with @jeifour, being able to verify that a record equals something you expect and alerts you if it has been changed would be VERY valuable.

Thanks for all the hard work

**Comment by mgrn0** [comment] 2023-04-05 07:19
@josefglatz this is an extremely good proposal, would be really useful to see something like that supported.

**Comment by thcnunz** [comment] 2023-06-27 07:41
+1 for this feature.

**Comment by CommanderStorm** [comment] 2023-06-27 09:01
@thcnunz 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by CommanderStorm** [comment] 2023-07-26 23:56
@josefglatz 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/432
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2024-06-29 21:42
Checking the content of dns queries is tracked in https://github.com/louislam/uptime-kuma/issues/432 and the PR to resolve this will be https://github.com/louislam/uptime-kuma/pull/3919, but it will be a while before it gets implemented.

=> closing as a duplicate

**Closed by CommanderStorm** 2024-06-29 21:42 UTC
Labels: feature-request, area:monitor, type:enhance-existing
