### ISSUE TITLE
Option to switch to 12 hrs timezone!

### ISSUE THREAD

**Issue by imranext** [louislam/uptime-kuma#1983] opened 2022-08-09 16:15 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Please add a feature to change 24 hrs timezone to 12 hrs timezone. In my country we use 12 hrs timezone. 

### ✔️ Solution

It'd be great if you guys add 12 hrs timezone or option to switch to this 12 hrs timezone from current 24 hrs style.

### ❓ Alternatives

Option to select 12 hrs timezone.

**Comment by imranext** [comment] 2022-08-09 16:16
Thanks guys.

**Comment by QuikBolte** [comment] 2022-08-11 16:23
Yep, much needed.

**Comment by CommanderStorm** [comment] 2023-12-08 11:17
Related/partial duplicate #2654

@imranext are there other areas that need this?

**Comment by chakflying** [comment] 2023-12-10 12:19
Since #3838 has identified places where 12hr/24hr format is needed, I think we can close this as duplicate of #2654.

**Closed by chakflying** 2023-12-10 12:19 UTC
Labels: feature-request, question, area:core
