### ISSUE TITLE
Does adding MySQL database support?

### ISSUE THREAD

**Issue by aitixiong** [louislam/uptime-kuma#3637] opened 2023-08-24 04:49 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Does adding MySQL database support?

### ✔️ Solution

Does adding MySQL database support?

**Comment by CommanderStorm** [comment] 2023-08-24 08:33
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/953
Also think that this might be reoslved by the `v2.0` relase, as we are adding mariadb support: https://github.com/louislam/uptime-kuma/pull/2720

If you agree, could you please close this Issue, as **duplicates only create immortal zombies and are really hard to issue-manage**?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-05 00:17
resolved by the `v2.0 relase`, as we added mysql/mariadb support: https://github.com/louislam/uptime-kuma/pull/2720

=> closing as resolved

**Closed by CommanderStorm** 2023-12-05 00:17 UTC
Labels: feature-request
