### ISSUE TITLE
Auto-Refresh on status pages

### ISSUE THREAD

**Issue by JoeJePropeller** [louislam/uptime-kuma#2013] opened 2022-08-24 08:41 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Please can I request for status pages to automatically refresh every X seconds so they can be displayed on unmanned machines, such as a machine attached to a large screen.

### ✔️ Solution

An option to set status pages to refresh every X interval.

**Comment by thmarti** [comment] 2022-08-29 11:03
Related to #1910

**Comment by louislam** [comment] 2022-12-22 06:59
Duplicate of https://github.com/louislam/uptime-kuma/issues/978

**Closed by louislam** 2022-12-22 06:59 UTC
Labels: feature-request
