### ISSUE TITLE
Status Page > Description > Enable Markdown / HTML Support

### ISSUE THREAD

**Issue by grand-lotus-iroh** [louislam/uptime-kuma#755] opened 2021-10-20 14:02 UTC
If visiting the public /status page of Uptime Kuma, only plain text is supported in the **Description** field. It would be nice to have link support using either HTML or Markdown (or both).

**Comment by deefdragon** [comment] 2021-10-21 02:29
Markdown in description is duplicate of #635. 

and IMO user entered HTML is not a good idea. Too many potential problems for little gain over markdown.

**Closed** 2021-10-21 04:21 UTC
Labels: enhancement
