### ISSUE TITLE
Test FTP, VPN, UDP PORT, Socket and WEBSOCKET

### ISSUE THREAD

**Issue by RodrigoDornelles** [louislam/uptime-kuma#1073] opened 2021-12-17 12:40 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Some features that would be interesting to be able to monitor.

- [ ] FTP
- [ ] VPN
- [ ] UDP PORT
- [ ] SOCKET
- [ ] WEB SOCKET

### ✔️ Solution

You can use CURL to test FTP,

WebSockets and Sockets are easy to implement in javascript.

I have doubts about UDP and VPN.

**Comment by rezzorix** [comment] 2021-12-20 13:26
Wouldn't you monitor FTP with a TCP monitor on port 21 (or any other port you run the FTP)? 
Socket, Web Socket and VPN the same - except for VPN running on UDP like e.g. Wireguard.

For UDP... seems to be a difficult task to monitor this properly/reliably as it has been mentioned a couple of times already in similar requests.

**Comment by RodrigoDornelles** [comment] 2021-12-20 16:33
> Wouldn't you monitor FTP with a TCP monitor on port 21 (or any other port you run the FTP)?
It might even be possible to test the port, just not to be sure it works correctly.

> except for VPN running on UDP like e.g. Wireguard.
A connection test for openvpn (uses UDP only)

**Comment by rezzorix** [comment] 2021-12-20 16:56
> 

Not only "might be possible", it is. 
FTP is a TCP based service exclusively, standard port is 20/21.
The majority of commonly used services you can monitor with a TCP monitor in Uptime Kuma.

Further reading; [here](https://en.wikipedia.org/wiki/Port_(computer_networking)) & [here](https://www.cloudflare.com/learning/network-layer/what-is-a-computer-port/)

So except for the UDP monitoring, Uptime Kuma can most likely do all (and more) you asked for already 😉 

UDP monitoring, as mentioned before, is a different thing all together...

**Comment by stephen304** [comment] 2021-12-28 19:35
I'm trying to add a DHCP server monitor so this would be helpful to have. I think I have it working in statping, but my statping is so slugish. I could probably make some script to probe the dhcp server to check for liveliness but it would be nice to have that built in.

**Comment by McTwist** [comment] 2022-01-12 12:57
I found 3 issues that mentioned UDP, but only this one expanded on the subject. While UDP is "not reliable", I do not find it like a valid argument for not being able to use it. Support already exists for tcp ping, and also for retries, so it should be possible to increase the amount of retries. And as tcp ping is similar to udp ping, then it should not be that hard to integrate in the current workflow.

Currently, there is no library available like `tcp-ping` that you currently use, but it should not be that hard to implement datagram for node.

**Comment by rezzorix** [comment] 2022-01-12 13:36
Please read more about UDP protocol and why it is difficult to implement a monitor for it...

Here a quick summary:
- UDP is a connectionless protocol which doesn't send any acknowledgement on connecting to a UDP port unlike TCP.
- Lets say you try to monitor the UDP, when UDP port is not open system will send ICMP port unreachable message. The Issue is when the UDP port is blocked by a firewall, then the system will not send ICMP port unreachable message. Therefore it is not possible to use this method directly for checking port availability which will lead to an incorrect availability report.
- To overcome above issue it is required to send a command to the Service in question and expect a proper response back within a given timeout period with which then UDP port availability can be confirmed.

In short: to have a reliable UDP monitor, you would need to create a custom command for each specific service... 
This would come down to be individually different for almost every service on every different machine (e.g. different required credentials); and therefore impossible to implement on a general level..

There might be more details and better explanations to this, if I wrote something wrong and/or incomplete please feel free to add / correct.

**Comment by McTwist** [comment] 2022-01-12 21:16
The issue is not whether UDP is good to monitor at all. As you say, if a firewall is up then a response will not be sent. However, for the kind of systems that this will be used for, isn't it up for the person putting up the service and the monitoring to make sure that the firewall is open for people to connect? As an example, if I have a game server up and running and it accidentally goes down, doesn't the firewall tell you it's down because it cannot forward to the port of that service? If the maintainer of that service have set up things right, wont kuma just try that port, which should be open for the service to work at all?

And for communication of the UDP, I believe this should not be necessary. We are only checking to see if there is a connection. If it connects, we disconnect. If it does not connect, or does not reply at all, we disconnect. As you say, UDP does not handshake as TCP does, but it is possible to reply on the package you retrieved. Heck, HTTP3/QUIC is built upon UDP, so how are we supposed to support that in the not so distant future?

In conclusion: It's up to the administrator of the services and kuma to make sure that their system is set up correctly in order for UDP to be monitored properly without having to rely on actual communication. The only thing that should hold your claim of the firewall would be if it dynamically opens and closes ports if it knows the service is up or down. That is not a system I'm familiar with, so please do tell how that could be useful.

**Comment by McTwist** [comment] 2022-01-22 10:50
I've checked some of your competitors, and I found out that some of them support UDP, but how they did it was that they had two strings: the data sent to the server; the data received from the server to check against.

This is he solution to the problem you mentioned if UDP would be supported. And for certain verbose protocols like QUIC, that could be supported specifically, meaning the user wont have to input the string themselves. How does this sound?

**Comment by RodrigoDornelles** [comment] 2022-02-23 14:48
Interesting thing can be very interesting with the telnet command, that would be to have raw support and other pre-made things in future.

**Comment by bignay2000** [comment] 2022-12-10 18:38
Wireguard UDP monitor would be awesome!

**Comment by CommanderStorm** [comment] 2023-12-10 19:50
I am going to close this issue due to lacking enough specificity and braindump-issues (multiple issues being collected into one) not being managable for us.

More in-depth ratinale:
- FTP => tracked in https://github.com/louislam/uptime-kuma/issues/2877
- WEB SOCKET => tracked in https://github.com/louislam/uptime-kuma/issues/805
- SOCKET => resolved, see the TCP Port monitor
- UDP PORT => technically impossible. See https://github.com/louislam/uptime-kuma/issues/9
- VPN => there are more than one vpn implementation out there. Not enough context in this issue to just rewrite this issue to only include this monitor. Non-specific issues are not possible for us, given that they never will be able to get respolved.

**Closed by CommanderStorm** 2023-12-10 19:50 UTC
Labels: feature-request, area:monitor, type:new

**Comment by masx200** [comment] 2025-12-25 03:44
你说得对！Uptime Kuma 虽然非常强大，但在最新版本中，UI 界面确实**没有直接提供**通用的 UDP、QUIC 或 HTTP/3 监控类型（DNS 记录监控虽然底层使用 UDP，但它只能监控 DNS 解析，不能监控任意 UDP 端口）。

为了推动这个功能的开发，我们可以向官方 GitHub 仓库提交一个 **Feature Request（功能请求）**。

下面我为你草拟了一份专业的 GitHub Issue 内容（使用英文，因为该项目是国际项目，英文更容易被开发者理解和采纳），并附带了中文翻译供你参考。

---

### 📋 复制以下内容到 GitHub Issue

**Title (标题):**
`[Feature Request] Add native support for UDP, QUIC, and HTTP/3 monitoring types`

**Body (正文):**


### Is your feature request related to a problem? Please describe.
Uptime Kuma is an excellent monitoring tool, but I noticed it currently lacks native monitoring types for **UDP**, **QUIC**, and **HTTP/3**.

While the "DNS Record" monitor uses UDP, there is no option for a generic **UDP Port** check (e.g., to check if a Syslog service on port 514, or a custom game server on UDP 7777 is reachable and responding).

Additionally, as the web increasingly adopts **HTTP/3** (which runs over QUIC/UDP), standard HTTP(S) checks cannot verify if a server is successfully serving content via the h3 protocol. Monitoring modern infrastructure (gaming, streaming, logging) often requires these protocols.

### Describe the solution you'd like
I propose adding the following monitoring types to the "Add Monitor" dropdown:

1.  **UDP Monitor**:
    *   **Fields**: Hostname/IP, Port.
    *   **Advanced Options**:
        *   `Packet Payload` (Send String): Data to send in the UDP packet.
        *   `Expected Response`: String to match in the response packet (to verify service logic, not just port reachability).
    *   *Logic*: Send a UDP packet -> Wait for timeout or response -> Mark UP if response matches (or if port is reachable in "ping" mode) / DOWN on timeout.

2.  **HTTP/3 Monitor**:
    *   A new HTTP type specifically for HTTP/3.
    *   Should support standard fields: URL, Method, Headers, Body, Expected Status Codes, Keyword matching.
    *   *Implementation*: This could likely be implemented by utilizing `curl` with the `--http3` flag inside the container, or using a Node.js library that supports HTTP/3.

3.  **QUIC Monitor (Optional)**:
    *   A generic check to ensure a QUIC handshake can be established on a specific port (usually UDP/443).

### Describe alternatives you've considered
*   **Command Line / Docker Exec**: I can currently use workarounds like running `nc -u -z -v <ip> <port>` or `curl --http3` inside the container, but this doesn't integrate nicely into the dashboard (no response time charts, clean logs) as a native monitor type would.
*   **TCP Ping**: Not applicable for UDP services.

### Additional context
These protocols are becoming standard in modern networking stacks. Native support would make Uptime Kuma future-proof and incredibly useful for monitoring a wider range of services.

Thank you for developing this amazing tool!


---

### 📝 中文对照与说明

如果你需要根据实际情况修改，可以参考以下中文含义：

*   **标题**: [功能请求] 添加对 UDP、QUIC 和 HTTP/3 监控类型的原生支持。
*   **问题描述**:
    *   Uptime Kuma 很棒，但缺少 UDP、QUIC、HTTP/3 监控。
    *   虽然 DNS 监控用了 UDP，但它不能监控任意 UDP 端口（比如 Syslog 的 514 端口，或者游戏服的 UDP 端口）。
    *   随着 HTTP/3 的普及，普通的 HTTP(S) 检查无法验证服务器是否通过 h3 协议提供服务。
*   **建议方案**:
    1.  **UDP 监控**: 填写 IP/端口。高级选项里希望能设置“发送的数据包内容”和“期望的响应内容”（类似于 TCP 关键字检查，但是针对 UDP）。
    2.  **HTTP/3 监控**: 新增一种 HTTP 类型，专门检测 HTTP/3。底层可以用容器里的 `curl --http3` 来实现。
    3.  **QUIC 监控 (可选)**: 通用的 QUIC 握手检查。
*   **替代方案**: 目前只能用 `docker exec` 或者自定义脚本跑 `nc -uzv` 或 `curl`，但这没法集成到漂亮的仪表盘和图表里。
*   **补充背景**: 这些协议越来越主流，原生支持会让 Uptime Kuma 更强大。

---

### 🚀 如何提交

1.  访问 Uptime Kuma 的 GitHub Issues 页面：[https://github.com/louislam/uptime-kuma/issues](https://github.com/louislam/uptime-kuma/issues)
2.  点击右上角的 **"New Issue"** 按钮。
3.  选择 **"Feature request"** 模板（如果有）。
4.  将上面的英文内容复制进去，根据你的实际需求稍作修改。
5.  点击 **"Submit new issue"**。

提交后，你可以把 Issue 的链接分享出来，我和其他开发者也可以去给你点赞（👍），增加被官方实现的概率！

**Comment by jimmyjackpot** [comment] 2026-08-20 14:22
For anyone finding this request later, UDP and VPN monitoring need to be treated differently from normal port monitoring.

A generic UDP port check cannot reliably confirm that a service is working. UDP has no connection handshake, and many servers silently discard invalid packets. This can produce false-positive “UP” results.

VPN monitoring also needs to be protocol-specific. WireGuard requires a valid authenticated handshake, while OpenVPN requires its own control packet and response. Even a successful handshake does not always prove that traffic or DNS works through the tunnel.

A safer implementation would use separate protocol-aware monitors, followed by optional traffic and DNS checks, instead of one generic “VPN/UDP” monitor.
