### ISSUE TITLE
[Feature]: CLI for configuring and managing uptime kuma

### ISSUE THREAD

**Issue by digitalbricklayer** [louislam/uptime-kuma#855] opened 2021-11-01 10:52 UTC
### 🏷️ Feature Request Type

API, Other

### 🔖 Feature description

I am currently setting Uptime Kuma via an Ansible script. Whilst installing the software is easy enough even this node nube can do it, actually configuring Uptime Kuma is more problematic.

Add a command line program to do the following:
- [ ] import / export data
- [ ] add / edit / delete monitors
- [ ] add / edit / delete users
- [ ] backup of the entire system including user accounts

### ✔️ Solution

Write an API or command line program to implement the features suggested above.

### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

**Comment by arch1v1st** [comment] 2021-11-01 19:50
+1 for a REST API based approach here!

**Comment by gabrielefronze** [comment] 2021-11-02 14:54
+1 on my side as well!

**Comment by louislam** [comment] 2021-11-02 14:56
duplicate of #118

**Closed by louislam** 2021-11-02 14:56 UTC
Labels: enhancement
