### ISSUE TITLE
[Feature Request] Add configurable login-free dashboard-only view

### ISSUE THREAD

**Issue by itnok** [louislam/uptime-kuma#450] opened 2021-09-21 01:14 UTC
**Is it a duplicate question?**
Not that am aware of

**Is your feature request related to a problem? Please describe.**
It is not possible (or at least could not find it in the docs), how to allow just the public displaying of the dashboard without requiring the login

**Describe the solution you'd like**
It would be neat to allow regular users visiting the page to know the state of all the monitored systems without requiring them to login.

**Describe alternatives you've considered**
Have considered entirely disabling the authentication, but it is not a real solution as it gives everyone the right to change the configuration or add new monitored services.

**Additional context**

---

**Comment by chakflying** [comment] 2021-09-21 02:17
Duplicate of #124

**Closed** 2021-09-21 02:59 UTC
Labels: enhancement
