### ISSUE TITLE
Kuma On Site Agent

### ISSUE THREAD

**Issue by stodo94** [louislam/uptime-kuma#2766] opened 2023-02-13 10:13 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hi,

it would be great to have an agent functionality in Kuma.

### ✔️ Solution

For example that one instance can report ping and all the requests to a main instance.

Big advantage would be to not make all ips and ports available for the main instance.

**Comment by Computroniks** [comment] 2023-02-13 15:06
Is this something not handled by the push monitor type?

**Comment by stodo94** [comment] 2023-02-13 15:12
No I would like to have a agent module for example:
Kuma Uptime Master instance and a kuma slave instance on site which is probing ping, https, etc. for all the hosts

**Comment by Computroniks** [comment] 2023-02-13 17:07
Feels like a duplicate of #1259

**Comment by stodo94** [comment] 2023-02-13 17:11
Thanks, seems like a duplicate. Didn't found it with my search keywords

**Closed** 2023-02-13 17:26 UTC
Labels: feature-request
