### ISSUE TITLE
Virtual Groups for services

### ISSUE THREAD

**Issue by Tragen** [louislam/uptime-kuma#4676] opened 2024-04-14 21:48 UTC
### 📑 I have found these related issues/pull requests

I couldn't find any related issues

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I monitor multiple virtual machines and services.
When I reboot the host, all VMs are shutting down and restart when the host is up again.
I don't need a notification for every service if the host isn't accessible.
Just send the notification for the VM host and not for all guests.

### ✔️ Solution

If VM host is down, only send notification for VM host

**Comment by CommanderStorm** [comment] 2024-04-15 01:28
Depending what you mean this is a duplicate of these isssues:
- the already implemented (sheduled,manual) maintenance mode which you could activate/deactivate a group with a script via [unoffical api](https://pypi.org/project/uptime-kuma-api/).
- https://github.com/louislam/uptime-kuma/issues/1089
- https://github.com/louislam/uptime-kuma/issues/1534

**Closed by CommanderStorm** 2024-04-15 01:28 UTC
Labels: feature-request
