### ISSUE TITLE
Monitor a directory for new files

### ISSUE THREAD

**Issue by moduletz** [louislam/uptime-kuma#4082] opened 2023-11-22 07:56 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature

### 🔖 Feature description

Long story short: i want to be notified if my backups folder is unchanged for x days.

Long story: One of my servers automatically backs up to another destination (accesible by SSH/SFTP/SMB/NFS/WebDAV) every day. I want to be notified by Uptime Kuma if that folder does not have new files so i can know my backup is not working.

### ✔️ Solution

New monitor to watch for changes in SSH/SFTP/SMB/NFS/WebDAV (i suppose any would work fine for me)

**Comment by CommanderStorm** [comment] 2023-11-22 09:56
First of all: I think using the push-monitor is better suited for this usecase

I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2819 nhttps://github.com/louislam/uptime-kuma/issues/2000
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Closed** 2023-11-22 10:30 UTC
Labels: feature-request
