### ISSUE TITLE
Add Helm Chart

### ISSUE THREAD

**Issue by cdtzabra** [louislam/uptime-kuma#4113] opened 2023-11-28 10:59 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Just wondering if you plan to provide a Helm chart?

I tried to push in PR the one I wrote in my [repo](https://github.com/cdtzabra/helm-charts/tree/main/uptime-kuma)  but I don't have the rights. 

### ✔️ Solution

Example of charts: https://github.com/cdtzabra/helm-charts/tree/main/uptime-kuma

**Comment by CommanderStorm** [comment] 2023-11-28 11:01
See https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#%EF%B8%8F-openshift-4-and-kubernetes-helm-3-chart-unofficial

**Comment by CommanderStorm** [comment] 2023-11-28 11:42
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/763
If you agree, please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage.

**Closed as completed** 2023-11-28 12:22 UTC
Labels: feature-request, A:deployment
