### ISSUE TITLE
Is it possible to add a batch delete function? I monitor hundreds of IPs, but when I delete it's a headache!

### ISSUE THREAD

**Issue by water2022** [louislam/uptime-kuma#5304] opened 2024-11-04 06:11 UTC
### 📑 I have found these related issues/pull requests

Deleting multiple monitoring IPs is tedious

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Add the function of selecting multiple monitored IPs and then deleting them together, or deleting all monitored IPs in a tab.

### ✔️ Solution

Add the function of selecting multiple monitored IPs and then deleting them together, or deleting all monitored IPs in a tab.

### ❓ Alternatives

no

### 📝 Additional Context

Deleting information is tedious

**Comment by CommanderStorm** [comment] 2024-11-04 10:05
Duplicate of https://github.com/louislam/uptime-kuma/issues/455
PRs welcome 😁

**Closed by CommanderStorm** 2024-11-04 10:05 UTC
Labels: feature-request
