### ISSUE TITLE
Is it possible to add a batch delete function? I monitor hundreds of IPs, but when I delete it's a headache!

### ISSUE THREAD

**Issue by water2022** [louislam/uptime-kuma#5297] opened 2024-11-01 12:22 UTC
### 📑 I have found these related issues/pull requests

Is it possible to add a batch delete function? I monitor hundreds of IPs, but when I delete it's a headache!

### 🏷️ Feature Request Type

Settings, Other

### 🔖 Feature description

Is it possible to add a batch delete function? I monitor hundreds of IPs, but when I delete it's a headache!

### ✔️ Solution

Is it possible to add a batch delete function? I monitor hundreds of IPs, but when I delete it's a headache!

### ❓ Alternatives

Is it possible to add a batch delete function? I monitor hundreds of IPs, but when I delete it's a headache!

### 📝 Additional Context

Is it possible to add a batch delete function? I monitor hundreds of IPs, but when I delete it's a headache!

**Comment by CommanderStorm** [comment] 2024-11-01 14:25
Closing as repeatng two sentences 6x is not filing out the feature request form.
If you want to tell us something, please put in the effort you expect in return ^^

Also a duplicate of https://github.com/louislam/uptime-kuma/issues/455

**Closed by CommanderStorm** 2024-11-01 14:25 UTC
Labels: feature-request
