### ISSUE TITLE
Features 

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1502] opened 2022-04-16 21:41 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, Other

### 🔖 Feature description

In notifications features
Should add web notifications (for all devices if possible) like example
I am in web of YouTube and I received a new video uploaded while it web

Other features
Add sign up and restart up in login page
Able to change name
Able to create other accounts in the same device
Able to delete accounts.Before account getting deleted asks if want to backup and 
30 days recovery account (if is possible)

### ✔️ Solution

In notifications features
Should add web notifications 

Other features
Add sign up and restart up in login page
Able to change name
Able to create other accounts in same device
Able to delete accounts

**Comment by mathiskir** [comment] 2022-04-23 17:39
> Should add web notifications (for all devices if possible) like example
> I am in web of YouTube and I received a new video uploaded while it web

I don't really get what web notifications are. Do you mean browser notifications?
If yes, for now you could use Gotify. Its a self hosted notification server which you can also open in your browser and then you'll get a push notification from your browser.

**Comment by mathiskir** [comment] 2022-04-23 17:47
> Able to change name

Which name do you mean?
The page title? Could you maybe elaborate? You could also just provide a screenshot.

> Able to create other accounts in the same device
> Able to delete accounts.Before account getting deleted asks if want to backup and
> 30 days recovery account (if is possible)

Duplicate of #128

> Add sign up 

Belongs to #128 or won't be added because users should'nt be able to register on uptime kuma that wouldnt make any sense I think.

**Comment by ShadowGaming100** [comment] 2022-04-23 20:45
> > Able to change name
> 
> Which name do you mean? The page title? Could you maybe elaborate? You could also just provide a screenshot.
> 
> > Able to create other accounts in the same device
> > Able to delete accounts.Before account getting deleted asks if want to backup and
> > 30 days recovery account (if is possible)
> 
> Duplicate of #128
> 
> > Add sign up
> 
> Belongs to #128 or won't be added because users should'nt be able to register on uptime kuma that wouldnt make any sense I think.

Able to change account name

**Comment by mathiskir** [comment] 2022-04-24 06:59
You can basically closed this issue as everything is a duplicate of #128

**Closed** 2022-04-28 19:15 UTC
Labels: feature-request
