### ISSUE TITLE
Variable-Based Alert Messages

### ISSUE THREAD

**Issue by HStep20** [louislam/uptime-kuma#1629] opened 2022-05-10 15:46 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

This may tie under #21, but it would be great to create alerts using 'Monitor Variables'. 

If I have some non-critical systems, I don't want to create an alert for every single one saying: 'website x is down' - Instead It would be awesome if I could create an 'all-encompassing' alert message with something like: 

`{monitor_nickname} is unavailable on {monitor_group}. Check on it at {monitor_url}`

### ✔️ Solution

This would allow you to create generic alerts for groups of systems instead of individual alerts for single monitors. I could build a 'Mission Critical' alert with a different message sent to a text instead of an email, so I get it ASAP, and it would have all the relevant information for context when I receive the alert.

**Comment by thimplicity** [comment] 2022-07-03 17:47
@HStep20 I came here to look for exactly that feature, thanks

+1

**Comment by CommanderStorm** [comment] 2023-08-04 23:52
@HStep20 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/975
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-08-04 23:56 UTC
Labels: feature-request
