### ISSUE TITLE
Scheduled downtime

### ISSUE THREAD

**Issue by federicotravaini** [louislam/uptime-kuma#917] opened 2021-11-13 07:30 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

I have servers that have scheduled downtime for maintenance and it would help to set the scheduled downtime so it doesn't notify me for nothing. 

### ✔️ Solution

A server/service/device shuts down every night for 1 hour and I receive every night a notification that the device is down, and then back up. I suggest we set the expected uptime hours/minutes for every service (should me very detailed, like hours, days of the week, months, etc.)

**Comment by deefdragon** [comment] 2021-11-13 07:39
Duplicate of #900 (#233) for scheduled downtime for notifications, and #191 for periodic scheduled downtime

**Closed** 2021-11-13 07:42 UTC
Labels: feature-request
