### ISSUE TITLE
Being able to edit the notification that is being sent out

### ISSUE THREAD

**Issue by 4n0nh4x0r** [louislam/uptime-kuma#3048] opened 2023-04-08 22:42 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

As the title already says.
It would be nice to be able to specify what a notification sends.
Like for example, if i dont want to expose the ip address of the server where my backend service runs on, it would be nice to be able to at least disabled that the notification sends out the service url.
Even better would be being able to fully customize the notification but well, i can assume how much work that would be, so it would already be nice to just be able to toggle the visibility of certain parts of the message.

### ✔️ Solution

Having options in the notification setup that you can toggle to enable/disable this specific notification from showing a certain part of the information like for example the service url or the ping.
At least a toggle to disable the service url from being shown on the notification you are editing.

### ❓ Alternatives

Alternatively one could allow the user to create their own notification with maybe a specific json object template they have to edit themselves, or just some text boxes that fill the json object behind the scenes

**Comment by jonnymccullagh** [comment] 2023-04-14 10:39
I would like this too, with another (optional) textbox under 'Description' for 'Notification Message' that could include info on how to deal with the problem or a link to a Playbook.

**Comment by 4n0nh4x0r** [comment] 2023-04-14 19:37
> I would like this too, with another (optional) textbox under 'Description' for 'Notification Message' that could include info on how to deal with the problem or a link to a Playbook.

ooooo, it would be nice to be able to automate actions if something goes south
like for example making it so if a service goes down lets say in the middle of the night and you dont notice it being down for lets say 5 minutes, that the system automatically tries to restart the service or even the whole server
but it would also be nice to be able to set custom responses for certain error codes, for example if a nextcloud server gives out a 500 error, yknow that something is really going wrong, possibly a redis server or the db server down or something like that, and then the notification could tell you the error code and what problems could be causing this (tho this would be more of a manual thing to add as a custom message)

**Comment by CommanderStorm** [comment] 2023-06-04 23:49
@4n0nh4x0r is this a duplicate of #1529 #2661 https://github.com/louislam/uptime-kuma/issues/2617 https://github.com/louislam/uptime-kuma/issues/2387 and more (see #646 for a deeper discussion)

If yes, please close this issue. Duplicates just make issue management harder.
If no, please edit the title+description to make this more distinct (and comment to notify the other participants)

**Comment by jonnymccullagh** [comment] 2023-06-05 18:58
Yes duplicate of https://github.com/louislam/uptime-kuma/issues/646 - closing this issue

**Closed** 2023-12-03 23:12 UTC
Labels: feature-request, area:notifications
