### ISSUE TITLE
Notifications: identify Uptime Kuma that sent it and/or allow customization of sent message

### ISSUE THREAD

**Issue by peracchi** [louislam/uptime-kuma#2194] opened 2022-10-07 13:43 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

I have two instances of Uptime Kuma running: one inside my network and other outside.

Both monitoring the same few services. This helps to narrow down problems (problem it´s only accessing from inside, outside or both?).

The problem is that I can´t know wich server sent which notification.

### ✔️ Solution

I think the easiest/quickest solution is to add "From: <Uptime Kuma Hostname> - " in the beggining of each notification sent.

Ideally, some global and/or field to customize notifications, with some variables available to use.

**Comment by rezzorix** [comment] 2022-10-07 16:37
> I have two instances of Uptime Kuma running: one inside my network and other outside.
> 
> Both monitoring the same few services. This helps to narrow down problems (problem it´s only accessing from inside, outside or both?).
> 
> The problem is that I can´t know wich server sent which notification.
I have the same; several instances on different servers.

Simple Solution: give your monitors distinctive "Friendly Names" either prefixes or suffixes.

E.g.:

```
## Instance1 ##
Instance 1 | homeserver.lan:8888
Instance 1 | homerserver.lan:9999
```

```
## Instance2 ##
Instance 2 | homeserver.lan:8888
Instance 2 | homerserver.lan:9999
```

etc.

**Comment by peracchi** [comment] 2022-10-08 22:55
> Simple Solution: give your monitors distinctive "Friendly Names" either prefixes or suffixes.

Good idea, thanks!

I will use your contour solution but would be better do this at _"notification level"_ instead of _"monitor´s friendly names level"_.

**Comment by rezzorix** [comment] 2022-10-09 02:27
Yes customizing notifications would be nice; however fully customizing each message - dont know if that is possible or feasible.
Especially as one would need to look into each and every of the 90+ notification services to ensure there are no hiccups etc.

I am also a friend of simple solutions... one could argue that "at notification level" is already possible as you can set up as many notifications as you like (and therefore make them individual to your needs aka easier identifiable).

With some notifications (not all) you can already set e.g. a "title" or "subject".
Where this isnt possible you could use e.g. a different webhook or different channel as target to ensure knowing the source of notification.

What notification service are you mainly using?

**Comment by peracchi** [comment] 2022-10-09 20:25
> What notification service are you mainly using?

I'm only using Telegram.

I have several monitors, usually I configure everything in one Uptime Kuma instance, export and import they at the other.

If could be possible modify the fixed part of Telegram notification, would be necessary to do only one modification in one of the Uptime Kuma instances.

Better yet, if there was some variables to be used in a template message in Telegram notification, no modification would be necessary at all.

Something like: "%UPTIME_KUMA_HOSTNAME% - %MONITORING_FRIENDLY_NAME% - %MESSAGE%".

**Comment by rezzorix** [comment] 2022-10-10 04:25
> I'm only using Telegram.

Seems like we run a very similar setup 😎 

> Better yet, if there was some variables to be used in a template message in Telegram notification, no modification would be necessary at all.
> 
> Something like: "%UPTIME_KUMA_HOSTNAME% - %MONITORING_FRIENDLY_NAME% - %MESSAGE%".

I like the idea.
However wouldn't the issue with different notification services remain as there are e.g. limited characters or charset etc.?

**Comment by peracchi** [comment] 2022-10-10 11:14
> However wouldn't the issue with different notification services remain

Probably.

But maybe just provide some template variables and the possibility of edit the sent message of the notification service would be a great start point.

I supppose (without any real info) that Telegram and email are the most used notification services. Maybe start with implementing this idea with these ones...

**Comment by vedatkamer** [comment] 2022-11-07 12:58
+1

**Comment by ahmetsoguksu** [comment] 2022-11-07 13:10
+1
 
Here (https://github.com/louislam/uptime-kuma/pull/393), this feature has been added for Discord before. It would be good to add it for Telegram as well.

**Comment by PilaScat** [comment] 2022-11-12 14:59
+1

**Comment by ACiDGRiM** [comment] 2023-06-04 22:42
I just want to provide a link to the uptime kuma instance, so I can easily click an alert to check the status from either email or matrix (or other IM service)

**Comment by CommanderStorm** [comment] 2023-06-04 22:52
@PilaScat @ahmetsoguksu @vedatkamer

Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by CommanderStorm** [comment] 2023-06-04 22:56
@peracchi is this a duplicate of #975 and associated discussion in #646 ?
If no, could you please edit the inital message to make this more clear.
If yes, please close this issue.
Duplicates just make issue management harder for everybody and spawn more duplicates ^^

**Comment by peracchi** [comment] 2023-06-04 23:11
@CommanderStorm My suggestion is a little broad than #975, which deals only with customization of the notification.

In my idea, if you do not want customize the notification, at least you already got some identification from the Uptime Kuma server that sent it.

As #975 says, notifications are only "[>>NAME OF SERVICE <<] [🔴 Down]" or "[>> NAME OF SERVICE <<] [✅ Up]".

But which server sent the notification?

The Uptime Kuma code can be modified to add some server identification on the alert even if the user do not want customize notifications.

A template or some UI to customize the notification would be a plus.

**Comment by CommanderStorm** [comment] 2023-06-04 23:29
> if you do not want customize the notification

Oh, don't get me wrong, this will eventually be a thing.
Please read through the issue above why message templating has proven difficult until now.

> But which server sent the notification?

I don't fully get what you mean by "which server". Is https://github.com/louislam/uptime-kuma/tree/master/server/notification-providers what you are searching for?

**Comment by peracchi** [comment] 2023-06-04 23:38
@CommanderStorm , as I said before (probably I wasn't clear enough) I have some services running on my work. These services are used by people outside the internal network and by people inside the office.

Sometimes I see a "[>>NAME OF SERVICE <<] [🔴 Down]" on my Telegram group and do not know if guys at firewall messed up and people outside office cannot reach some service OR if guys at infra messed with internal routers because Uptime Kuma outside office and Uptime Kuma inside office will send the same "[>>NAME OF SERVICE <<] [🔴 Down]".

Better explained now?

**Comment by CommanderStorm** [comment] 2023-06-05 00:10
So basically #3191? (I know there is a better some other duplicate out there, but it's 2AM, and I am going to bed now)

**Comment by peracchi** [comment] 2023-06-05 00:13
> So basically #3191? (I know there is a better some other duplicate out there, but it's 2AM, and I am going to bed now)

Nope, that's for email only.

**Comment by chakflying** [comment] 2023-12-10 12:14
Duplicate of #646 

Note that for certain notification providers, you can do so manually by using a different Webhook url, and customize it's icon/bot name.

**Closed by chakflying** 2023-12-10 12:14 UTC
Labels: feature-request, area:notifications
