### ISSUE TITLE
[Bug]: Event log not updated on message change

### ISSUE THREAD

**Issue by fbartels** [louislam/uptime-kuma#838] opened 2021-10-30 12:55 UTC
### 👟 Reproduction steps

- configure a push type monitor
- curl the push url, e.g https://uptime.kuma/api/push/ABCDEfgh?msg=OK
-> there is a new line in the "events" section of the monitor and the monitor is "up"
- you curl the url again, but this time with https://uptime.kuma/api/push/ABCDEfgh?msg=HELLO
-> the event log still shows the previous message

### 👍 Expected behavior

the event log should have another entry with "HELLO" as the message

### 👎 Actual Behavior

the event log still shows the previous message

### 🐻 Uptime-Kuma version

1.9.2

### 💻 Operating System

Ubuntu 20.04 (running as a container on Cloudron)

### 🌐 Browser

Chrome

### 🐋 Docker

Docker version 20.10.7, build f0df350

### 🏷️ Docker Image Tag

custom

### 🟩 NodeJS Version

v14.15.4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by louislam** [comment] 2021-10-31 06:07
Cannot reproduce, more context or information is needed.

![image](https://user-images.githubusercontent.com/1336778/139570365-f9792933-e48b-4ed7-a3be-ff468180eb23.png)

**Comment by chakflying** [comment] 2021-10-31 06:14
This is a known issue similar to #169, where if the UP/DOWN status didn't change, any change in message will not be shown. We don't have a fix for this yet.

**Comment by louislam** [comment] 2021-10-31 06:14
Oh, I know what you mean.

Currently, event like `up to down`  or `down to up` will be shown in the event list.

Feel feel to convert to a feature request

**Closed by louislam** 2021-10-31 06:14 UTC
Labels: invalid

**Comment by fbartels** [comment] 2021-10-31 10:32
Hi @louislam,

thanks for your response. I was not aware that the information is still visible within the heartbeat.
