### ISSUE TITLE
muliti user suppport (read only) with SSO

### ISSUE THREAD

**Issue by Sumit0789** [louislam/uptime-kuma#3272] opened 2023-06-15 12:00 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

currently we have only single user (admin) support, need multiple user support who can view the the stats and configuration but can't edit, with SSO support.

### ✔️ Solution

google sso with read only user

**Comment by CommanderStorm** [comment] 2023-06-16 05:56
This is a duplicate of https://github.com/louislam/uptime-kuma/issues/128.
Please close this issue

**Comment by kokofixcomputers** [comment] 2023-06-16 18:47
Please close the issue

**Comment by CommanderStorm** [comment] 2023-12-03 15:12
@Sumit0789
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in the issues linked at https://github.com/louislam/uptime-kuma/issues/128#issuecomment-1676504440 as there is no functional difference and "SSO" is not a concrete auth provider.
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-03 15:12 UTC
Labels: feature-request
