### ISSUE TITLE
Group behavior change when deleting child monitor that has a "down" status

### ISSUE THREAD

**Issue by begunfx** [louislam/uptime-kuma#4853] opened 2024-06-13 21:38 UTC
### 📑 I have found these related issues/pull requests

Can't find a related request.

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

Current behavior:
When a child monitor is reporting down, the group its in will also report "down", but when you delete the child monitor from the group, the group status will remain in a "down" state until the next heartbeat.

### ✔️ Solution

I suggest that if you delete a child that has a "down" status, this should trigger a heartbeat check of the entire group and therefore if there are no other issues, the group status should immediately return to green (up) status.

### ❓ Alternatives

No

**Comment by CommanderStorm** [comment] 2024-06-13 23:22
Duplicate of https://github.com/louislam/uptime-kuma/issues/4572
=> closing as a duplicate

We know that the current behaviour is somewhat counterintutive, but resources..

**Closed by CommanderStorm** 2024-06-13 23:22 UTC
Labels: feature-request, area:monitor
