### ISSUE TITLE
Remote monitors

### ISSUE THREAD

**Issue by koehn** [louislam/uptime-kuma#3845] opened 2023-10-04 19:14 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

What I’m interested in is a monitor that runs from a remote location (in addition to where uptime-kuma is running). My challenge is I get a lot of false positives running uptime-kuma in my house monitoring my remote servers. I’d like to have monitors running remotely and only raise an alert if two or more monitors report a connectivity problem. 

### ✔️ Solution

1. Separate the monitoring app from the notification/UI app. 
2. Allow the monitoring app to be installed, and have it poll an API on the main instance of the app to get the list of services to monitor. When a service fails, call another API to report the failure. 
3. Have the backend confirm that _n_ monitors (configurable) must report the service as down before sending a notification. 

### ❓ Alternatives

Just installing it remotely and sending notifications from two spots, but that’s kind of nasty. 

I could also solve my problem by disabling notifications if the main app cannot ping a known available host (e.g. Google), as that would indicate my ISP was down, not my services. 

Still, multiple locations would be better. 

### 📝 Additional Context

This also helps prevent spurious errors I get when I lose internet connectivity at home where my monitor runs.

**Comment by CommanderStorm** [comment] 2023-10-04 20:40
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/84
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^


Pkease also note that this can be solved by using push monitors

**Closed** 2023-10-04 21:13 UTC
Labels: feature-request
