### ISSUE TITLE
Extend reporting duration separate from refresh frequency

### ISSUE THREAD

**Issue by mikeckennedy** [louislam/uptime-kuma#5127] opened 2024-09-24 16:28 UTC
### 📑 I have found these related issues/pull requests

None that I could find.

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

When looking at the status pages, both the bars and more importantly the % uptime is based solely on the refresh frequency. This means you only see 30m - 2h of uptime status on the status page. 

Can we please get a parameter to extend this? I'd love to have my refresh rate at 30s-60s, but my status page report the uptime for the last 30 days.

### ✔️ Solution

Add a setting to specify how large the time windows for the status pages are.

### ❓ Alternatives

Slow the refresh rate WAY down to a non-useful level. For example, I could set the refresh rate to ping the site every 11,160 sec, to get one month on the status page, but how representative of uptime will that be? Not very.

### 📝 Additional Context

Here is an example page:

https://uptimekuma.talkpython.fm/status/talk-python

See that it only shows between 30m-2h of uptime.

**Comment by CommanderStorm** [comment] 2024-09-25 08:29
Duplicate of #1888.
Please see https://github.com/louislam/uptime-kuma/issues/1888#issuecomment-2068191172 for further context what is needed to activate this feature in v2.
Closing as a duplicate

**Closed by CommanderStorm** 2024-09-25 08:29 UTC
Labels: feature-request, area:status-page

**Comment by mikeckennedy** [comment] 2024-09-25 17:06
Thanks @CommanderStorm I'm looking forward to v2 coming out.
