### ISSUE TITLE
Add user and status page to backup

### ISSUE THREAD

**Issue by mindlesstux** [louislam/uptime-kuma#710] opened 2021-10-15 02:43 UTC
**Is it a duplicate question?**
Not that I could find.

**Is your feature request related to a problem? Please describe.**
The backup is not as complete as it could be.

**Describe the solution you'd like**
Add the status page configuration and user configuration to the backup.

**Describe alternatives you've considered**
Considered stopping and pulling the SQLite and forcing that upon the other two instances.  I would rather export/import a JSON file.

**Additional context**
I have 3 instances running that I am attempting to keep in sync, minus which one is sending notifications in what manner, and the status page and the user is not imported (nor are they in the backup JSON).

**Comment by mindlesstux** [comment] 2021-10-15 02:58
Partial dupe, I missed #555 which is half of my feature request.

**Comment by louislam** [comment] 2021-10-15 07:14
Duplicate of #555

**Closed by louislam** 2021-10-15 07:14 UTC
Labels: enhancement
