### ISSUE TITLE
More Ping Information

### ISSUE THREAD

**Issue by Heshmatkhah** [louislam/uptime-kuma#4002] opened 2023-11-09 09:26 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I want to have more information from my `Ping Monitors`.
I want to know `Minimum`, `Maximum`, `Mean Deviation (mdev)` of my Monitor
As you ping the host, you already have all this information but I can't see them in the UI.
Also, it will be grate If you drow a graph for them (changes of time)

### ✔️ Solution

I want to know `Minimum`, `Maximum`, `Standard Deviation (mdev)` of my Ping Monitor

**Comment by CommanderStorm** [comment] 2023-11-09 09:49
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/818
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Closed** 2023-11-09 09:50 UTC
Labels: feature-request

**Comment by CommanderStorm** [comment] 2023-12-15 12:45
Correction: this should have been merged into #1724 instead
