### ISSUE TITLE
MTR Monitor Type

### ISSUE THREAD

**Issue by I-Fun** [louislam/uptime-kuma#1558] opened 2022-04-25 01:40 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Could you add MTR Monitor type for checking the packet loss?
it will be great if you can add that monitor type 

### ✔️ Solution

i'm using /usr/bin/mtr for checking the packet loss
![2641---25_08-36-17](https://user-images.githubusercontent.com/7077766/165007040-abc25eb6-1c33-4b95-8909-5356419cb96b.png)

**Comment by cescarsega** [comment] 2023-03-24 22:57
I would love if this could be a monitor type as well!

**Comment by Playlist9661** [comment] 2023-05-11 15:17
Completely agree, this could be used to assist with determining latency changes that affect overall service but with greater granularity than a ping response graph shows. Many products support something of this nature including WinMTR, Solarwinds Traceroute NG, Pathping, Multiping, Pingplotter, etc... The limitation with many of these tools is that they are either a local application that is run on demand or a hosted service with recurring fees.

**Comment by CommanderStorm** [comment] 2023-08-27 23:14
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/765 https://github.com/louislam/uptime-kuma/issues/2911 given the MTR does multiple traceroutes and aggegates the results.

If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage? (Could this be integrated into the issues linked above?) ^^

**Comment by CommanderStorm** [comment] 2024-02-16 14:41
@I-Fun 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/2911 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2024-02-16 14:41 UTC
Labels: feature-request, question, area:monitor, type:new
