### ISSUE TITLE
Custom Discord Notifications

### ISSUE THREAD

**Issue by rgilmorelmhost** [louislam/uptime-kuma#1021] opened 2021-12-08 16:32 UTC
Hello!

I have set up your Uptime Kuma 3 times now and have it running across all of the networks!

Would it be possible to change what is displayed in discord for Services going down and coming back up? 
if so where can we edit it etc

Thanks
Rory 
contact@lmhost.uk

**Comment by louislam** [comment] 2021-12-11 14:15
Duplicate of #646

**Closed by louislam** 2021-12-11 14:15 UTC
