### ISSUE TITLE
Password protected Status Page

### ISSUE THREAD

**Issue by uncappedshady** [louislam/uptime-kuma#1756] opened 2022-06-13 10:03 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Require the ability to password protect a status page.

### ✔️ Solution

When I visit a specific status page, it should prompt me to enter a username and a password and only display the status page once correct credentials has been entered.

**Comment by Computroniks** [comment] 2022-06-13 10:06
Status pages are inherintly public. If you want it so only you can access the information then you can just leave them on the dashboard and not create a status page. However, this won't work if you only want access from within your organization. In cases like this, you could look at using [Authelia](https://www.authelia.com/) to provide your authentication.

**Comment by madroots** [comment] 2022-06-17 07:52
you can just do it within nginx reverse proxy, if you have one. 

check [uptime kuma instructions](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx) for setting up nginx config, use "location" parameter to define your status page url and add this: 
        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;

You can find guide on this and on how to create user and pass - check here [official nginx docs](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/).

**Comment by shakalandy** [comment] 2022-10-14 14:54
Would be cool to have this one, use-case:

Having 10+ Status Pages with different "folders" per Customer/Team it would be cool to have an optional pw protection within uptime-kuma per Folder/Team.

Would this be possible with Authelia as well @Computroniks? thanks!

**Comment by cheesepaulo** [comment] 2022-11-01 15:31
I Found a way here, not the best but for my needs works fine.

I have a need to make all my status page private.
No need for alter database or other UI things just protect the pages with login.

[Here](https://github.com/louislam/uptime-kuma/blob/master/src/pages/StatusPage.vue#L572) is the code that renders the StatusPages.

Before that code add a simple modification for redirect to / when user is not logged_in.

if (!this.hasToken) this.$router.push("/");

Just fork the project, adjust, make the build and be happy.

**Comment by MateusFreitas-C** [comment] 2022-11-22 18:54
I'm having this same issue. Could anyone help me to resolve this? I didn't know how to use authelia, and I couldn't with the NGINX solution.

**Comment by tahaipek** [comment] 2023-03-20 18:33
@cheesepaulo Thanks for the advice. 👍👍👍

**Comment by CommanderStorm** [comment] 2023-06-29 13:21
@uncappedshady 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1401
If you agree please close this issue, as issue-management is harder with zombies hanging around.
If you disagree, what is the difference?

**Comment by CommanderStorm** [comment] 2023-12-03 23:24
Closing as duplicate of https://github.com/louislam/uptime-kuma/issues/1401

**Closed by CommanderStorm** 2023-12-03 23:24 UTC
Labels: feature-request
