### ISSUE TITLE
Programmable Page Update/Refresh for Status Pages

### ISSUE THREAD

**Issue by kristiandg** [louislam/uptime-kuma#1910] opened 2022-07-17 13:50 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

When building a Status Page, having the ability to set how often it refreshes/updates. I'd prefer it to update rather than refresh, so the page doesn't re-load, and only the updated data is sent.

If someone is viewing the page (or watches it on a status screen), and items are added/removed/paused/etc from the Status page, that data doesn't update automatically unless the person manually reloads the page (at least, from what I've seen).

If, when building the status page, the person could set it to update at a timed interval, this would ensure viewers have current data being displayed.

In my tests, I was adding additional monitors that never showed up on the viewed page until I refreshed. The same thing occurred with enabling/disabling the PoweredBy message, as well as when editing the custom footer message.

### ✔️ Solution

A field that allows the page to pull the latest data (not a re-load, per-se, but more of a dynamic update with the most current content).

### ❓ Alternatives

Manually reloading is the only option I've found.

### 📝 Additional Context

This would make the Status Pages more suitable to be viewed on a screen for larger area display.

**Comment by louislam** [comment] 2022-12-22 07:00
Duplicate of https://github.com/louislam/uptime-kuma/issues/978

**Closed by louislam** 2022-12-22 07:00 UTC
Labels: feature-request
