### ISSUE TITLE
CHANGE DETECTION

### ISSUE THREAD

**Issue by syberx** [louislam/uptime-kuma#3896] opened 2023-10-15 08:54 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Please add a Monitor for website CHANGE DETECTION like: www.CHANGEDETECTION.IO
I can check a robots.txt or other for change

### ✔️ Solution

Select a change detection Monitor

**Comment by CommanderStorm** [comment] 2023-10-16 00:00
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/584
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-10-16 01:40 UTC
Labels: feature-request
