### ISSUE TITLE
E-Mail Subscription by Status-Page 

### ISSUE THREAD

**Issue by pavl21** [louislam/uptime-kuma#3022] opened 2023-04-04 12:07 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, Other

### 🔖 Feature description

Provide an option on the status page to send an e-mail when the status changes. As well as a message to all subscribers when there is maintenance work. 

### ✔️ Solution

E-Mail Subscription via Status-Page and SMTP-Configuration

**Comment by CommanderStorm** [comment] 2023-06-12 11:04
@pavl21 is this a duplicate of https://github.com/louislam/uptime-kuma/issues/916?
If no, could you make this issue more distinct?
If yes, could you close this issue? (duplciates only hurt the project)

**Comment by CommanderStorm** [comment] 2023-12-03 23:15
@pavl21 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #916 as there is no functional difference and the other isuse has more support and a deeper discussion
⇒ I am going to close this as a duplicate

**Closed by CommanderStorm** 2023-12-03 23:15 UTC
Labels: feature-request, area:status-page
