### ISSUE TITLE
Force a "specific" dns record in order to check every node on a cluster (monitoring DNS RR)

### ISSUE THREAD

**Issue by meepmeep** [louislam/uptime-kuma#4931] opened 2024-07-11 14:21 UTC
### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

I use a round robin DNS to balance traffic between multiple haproxy instances.  
This mean that _gateway.mydomain.tld_ resolves to multiples IP address (ie 123.123.123.123 and 100.100.100.100, etc.), 

As it's handled by haproxy, I cannot simply request "tcp:port" on each haproxy  because without SNI I cannot check my specific backend (I need to ask haproxy for _gateway.mydomain.tld_ so the request is send to my gateway backend).

If I set  _gateway.mydomain.tld_ on kuma, it will request randomly between each "node/ip", meaning that if node 1 is down, it will be detected randomly (and potentially never if I ask for 1 retry before flipping the state of the monitor)

### ✔️ Solution

In https monitor, I would like to be able to specific to which is the dns entry must be resolves :

- Monitor 1 - https://gateway.mydomain.tld which resolves to 123.123.123.123
- Monitor 2 - https://gateway.mydomain.tld which resolves to 100.100.100.100

This way I can check every node specifically. 

### ❓ Alternatives

None.

**Comment by CommanderStorm** [comment] 2024-07-12 14:07
You are be able to get around this with the tools currently at your disposal:
- you enter the ip into the url field
- you enter the [`Host` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) as described in https://github.com/louislam/uptime-kuma/issues/2991

Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/1689

**Closed by CommanderStorm** 2024-07-12 14:07 UTC
Labels: feature-request
