### ISSUE TITLE
Reporting Feature for Uptime Kuma

### ISSUE THREAD

**Issue by anldrms** [louislam/uptime-kuma#5424] opened 2024-12-09 19:28 UTC
### 📑 I have found these related issues/pull requests

Hi,

I know that you guys have been mentioned in the past regarding your work on reporting features. Is there any information about upcoming releases that will cover this topic in the near future?

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Reporting feature for Uptime Kuma with data retention options such as 3 minutes, 6 minutes, 12 minutes, and 2 years.

### ✔️ Solution

It would also be great if PDF or CSV export options were available.

### ❓ Alternatives

NA

### 📝 Additional Context

NA

**Comment by CommanderStorm** [comment] 2024-12-10 14:11
Duplicate of https://github.com/louislam/uptime-kuma/issues/366

You can currently achieve this kind of export via the grafana export option.

**Closed** 2024-12-10 14:12 UTC
Labels: feature-request
