### ISSUE TITLE
timetable not to do checks

### ISSUE THREAD

**Issue by rubvaz** [louislam/uptime-kuma#928] opened 2021-11-16 17:46 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hello, you are doing a very good job but I think that a new feature that give the option to configure down times where the checks should not be done.

### ✔️ Solution

Have a time table where we can set the time where we do not want the monitor to notify a down.

**Comment by deefdragon** [comment] 2021-11-17 06:00
Duplicate of #900 (#233) for scheduled downtime for notifications, and #191 for periodic scheduled downtime

**Closed** 2023-12-04 13:57 UTC
Labels: feature-request
