### ISSUE TITLE
[Feature]: Additional information

### ISSUE THREAD

**Issue by jabdullah3579** [louislam/uptime-kuma#818] opened 2021-10-28 07:47 UTC
### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

You should add additional information when clicking on one of the configured monitors just like in HetrixTools.

### ✔️ Solution

Add Additional information as per uptime monitor type.

### ❓ Alternatives

HetrixTools

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar feature request

**Comment by Stage4000** [comment] 2021-11-04 00:34
+1

**Comment by shinebayar-g** [comment] 2021-12-08 04:22
Could you make Dashboard page information available on Status page too? Because dashboard is password protected and it's for only single user. It would awesome if Status page items are clickable like Dashboard page, and contains more information like latency history, graph etc..

**Comment by Heshmatkhah** [comment] 2023-11-09 09:51
I want to have more information from my Ping Monitors.
I want to know `Minimum`, `Maximum`, `Mean Deviation (mdev)` of my Monitor
As you ping the host, you already have all this information but I can't see them in the UI.
Also, it will be great If you draw a graph for them (changes of time)

**Comment by Stage4000** [comment] 2023-11-20 15:16
Keep holding your breath I'm sure that the post that has been dead for 2 years really cares about your additional features requests. If you want these things implemented, you're gonna have to figure out how to do it yourself.

**Comment by CommanderStorm** [comment] 2023-12-14 23:58
I think "additional information" this is refering to monitor descriptions
=> closing as a duplicate of #3008, as said issue is way more clear. If I misunderstood something, feel free to reopen ^^

**Closed by CommanderStorm** 2023-12-14 23:58 UTC
Labels: feature-request, question, area:status-page

**Comment by ShadowJonathan** [comment] 2023-12-15 10:59
@CommanderStorm ive seen another issue folded into this one because some of the "additional information" was ping times on public status pages (https://github.com/louislam/uptime-kuma/issues/4002), so please re-open this issue, or that one

**Comment by CommanderStorm** [comment] 2023-12-15 12:48
@ShadowJonathan @Heshmatkhah 
https://github.com/louislam/uptime-kuma/issues/4002 should not have benn folded into this issue, but into https://github.com/louislam/uptime-kuma/issues/1724 instead
=> further details for the ping-chart is tracked there
