### ISSUE TITLE
Custom (gotify) notification message

### ISSUE THREAD

**Issue by spinnaker1** [louislam/uptime-kuma#3482] opened 2023-07-26 00:10 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

You should add a custom notification message (for Gotify) with static and variable content.

**Example static content:**
Some user text to include in notification message.

**Example variable content:**
`<sensor-url>` ... use the direct link (https://mydomain.com/dashboard/4) to the sensors details page

### ✔️ Solution

I would add the direct link to the sensor, into the notification message. So, if you get notified via e.g. Gotify that service XY is down, you can easily click the direct link in the notification message that directly brings up the sensor's detail page (https://mydomain.com/dashboard/4).

**Comment by CommanderStorm** [comment] 2023-07-26 00:40
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/975 and https://github.com/louislam/uptime-kuma/issues/646
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-07-26 00:54 UTC
Labels: feature-request
