### ISSUE TITLE
webhook why once time ?Why cannot alarms be sent all the time in Down state

### ISSUE THREAD

**Issue by xhweng-yy** [louislam/uptime-kuma#368] opened 2021-09-10 06:23 UTC
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Info**
Uptime Kuma Version:
Using Docker?: Yes/No
OS:
Browser:
webhook why once time ?Why cannot alarms be sent all the time in Down state

**Comment by chakflying** [comment] 2021-09-10 07:16
Duplicate of #233

**Closed** 2021-09-10 09:24 UTC
Labels: help
