### ISSUE TITLE
Kiosk-Friendly Display Mode with Credential Passing and Auto-Hide Notifications

### ISSUE THREAD

**Issue by yguerdat** [louislam/uptime-kuma#4469] opened 2024-02-09 07:15 UTC
### 📑 I have found these related issues/pull requests

This feature request aims to enhance Uptime Kuma's usability in kiosk environments, commonly used for support and monitoring displays, by allowing credential passing through URLs and implementing auto-hiding notifications for resolved downtimes.

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

**Problem Statement:** In many support and monitoring scenarios, displays are set up in a kiosk mode, which limits their ability to interact with input devices and retain credentials across sessions. Currently, there's no straightforward way to maintain an authenticated session without manual re-login, making it less practical for kiosk use. Additionally, notifications for resolved downtimes persist on the screen until manually cleared or the device is restarted, which isn't feasible without direct interaction capabilities.

**Impact:** Enhancing Uptime Kuma for kiosk use would significantly benefit organizations that rely on real-time monitoring dashboards displayed across various locations without direct human interaction for each display. It would improve the visibility of system health and reduce the maintenance overhead for managing these displays.

Implementing these features would make Uptime Kuma more adaptable to a wider range of monitoring scenarios, especially in environments where displays are not directly managed but need to stay informative and current with minimal setup and maintenance.

### ✔️ Solution

**URL Credential Passing:** Introduce a secure method to pass credentials through URLs or a token-based authentication mechanism that can be embedded in the URL. This approach would allow kiosk screens to automatically authenticate and display the dashboard without manual login, respecting security and privacy standards.

**Auto-Hiding Notifications:** Implement a feature where notifications, especially those indicating resolved downtimes, automatically disappear after a configurable duration. This ensures that the display remains clean and relevant, focusing on active issues without manual intervention.

### 📝 Additional Context

**Security Considerations:** Highlight the importance of implementing the URL credential passing feature in a way that does not compromise security, such as expiring tokens or encrypted parameters.
**User Experience:** Emphasize the importance of a seamless experience for displays running in kiosk mode, where manual intervention is minimal to none.
**Configuration Flexibility:** Suggest the ability for users to configure the auto-hide duration for notifications, catering to different preferences and needs.

**Comment by CommanderStorm** [comment] 2024-02-09 08:34
> usability in kiosk environments

Why not use a status page for this?

> Auto-Hiding Notifications

This is configurable in the upcoming `v2.0` release.
See #3441

> URL Credential Passing

From a security perspective, I don't think this is a good idea.
You likely would leak credentials to users.
Counsider disabling auth instead.

**Comment by CommanderStorm** [comment] 2024-02-09 08:46
I am going to close this as resolved, as 
- the auth part of the issue is covered by disabling auth and status pages
- Auto-Hiding Notifications is covered by https://github.com/louislam/uptime-kuma/pull/3441

We can reopen if an argument is made why this is not resolved ^^

**Closed by CommanderStorm** 2024-02-09 08:46 UTC
Labels: feature-request, question, area:dashboard
