### ISSUE TITLE
Option to send only one notification if entire host goes down (Conditional/Dependent Notifications)

### ISSUE THREAD

**Issue by zwimer** [louislam/uptime-kuma#5452] opened 2024-12-19 12:52 UTC
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/1089
- https://github.com/louislam/uptime-kuma/issues/774
- https://github.com/louislam/uptime-kuma/issues/1137

### 🏷️ Feature Request Type

Settings, Other

### 🔖 Feature description

If I have monitors set up like this:
```
Host1
    Host1_Ping
    Host1_Service1
    Host1_Service2
    ...
    Host1_Service48
```

If `Host1` looses internet or is shutdown or something, it's very likely that none of those services will be up. If each has notifications enabled, then this will result in a flood of like 50 notifications all at once.

### ✔️ Solution

It would be nice if uptime kuma could detect that every single child went down and just send a single notifcation stating 'Host1 and dependent services are down'.

### ❓ Alternatives

Group notifications so that instead of 50 individual simultaneous notifications, I get one large notification.

### 📝 Additional Context

Notification grouping is likely the more-preferred solution here (if we can only have one), but there already exists an issue for that: https://github.com/louislam/uptime-kuma/issues/1137

**Comment by CommanderStorm** [comment] 2024-12-20 09:01
Duplicate of the issues you linked => closing as a duplicate

**Closed by CommanderStorm** 2024-12-20 09:01 UTC
Labels: feature-request
