### ISSUE TITLE
Heartbeat Monitor Animation for Status Page

### ISSUE THREAD

**Issue by avancebt** [louislam/uptime-kuma#737] opened 2021-10-18 04:30 UTC
I noticed a potential problem with the status page that showed up for me when the uptime-kuma docker service stopped working.
The status page remained responsive, and showed everything as okay and green - but it was not actually checking.
Once all the hearbeat pills have been filled, there is no visual way of determining that the status monitor is actually doing anything, you just see every pill filled in as green.
If there was an animation for each heartbeat pill as it was been checked (maybe it spins) - and some way of showing the results 'shfting' to the the left (maybe a time period on the X axis or something) then I would have more confidence that uptime-kuma is working and hasn't frozen up.

**Comment by markdesilva** [comment] 2021-10-18 05:16
ow does the UK docker stop working but you can still view the status page?

**Comment by CommanderStorm** [comment] 2023-07-26 23:04
@avancebt 

I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/546 which [was resolved in `1.9.1`](https://github.com/louislam/uptime-kuma/issues/546#issuecomment-947285722). => I think this is also resolved.
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-03 18:55
Closing as resolved in `1.9.1`

**Closed by CommanderStorm** 2023-12-03 18:55 UTC
Labels: feature-request
