### ISSUE TITLE
DNS  keyword check

### ISSUE THREAD

**Issue by 5UFKEFU** [louislam/uptime-kuma#3214] opened 2023-06-02 06:57 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

The current DNS detection only detects if there is a resolution result, but this is not practical, and in practice DNS pollution is more important to detect.

### ✔️ Solution

Add the keyword check of DNS.

**Comment by CommanderStorm** [comment] 2023-06-02 10:16
If you are using a normal, reputable DNS vendor (supporting DNSSEC), this attack vector is basically negligible from what I have read
⇒ I don't see how this would be an advantage.

Please go into more detail

**Comment by 5UFKEFU** [comment] 2023-06-02 12:35
If you live in China, you will feel that this is just very important, China has an Internet firewall, specifically to pollute this, so it is necessary to say.

**Comment by CommanderStorm** [comment] 2023-07-26 23:55
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/432
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment] 2023-12-03 15:33
@5UFKEFU 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #432 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.

**Closed by CommanderStorm** 2023-12-03 15:33 UTC
Labels: feature-request
