### ISSUE TITLE
Continous Internet speed test

### ISSUE THREAD

**Issue by vignesh-mohankumar** [louislam/uptime-kuma#3097] opened 2023-04-23 05:13 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Please add a custom feature to continuously checks the internet connectivity speed test

### ✔️ Solution

-

**Comment by rezzorix** [comment] 2023-04-29 05:35
A speed test is working by connecting to a test server and up-/downloading test data. 

By doing this continuously you would basically max out your connection all the time, slowing your connection for non-test data. That doesn't make sense….

**Comment by sindastra** [comment] 2023-07-11 11:27
It does make perfect sense. The person probably means "run speed test every 15 minutes" or something like that, continuously. They probably don't mean "keep downloading forever". There are even commercial routers who offer automatic/regular speed tests. It's a desired feature in companies sometimes.

**Comment by rezzorix** [comment] 2023-07-11 12:14
It doesnt make sense based on “continuously”.
The word you are probably looking for based on what you wrote is “periodically”. 

That would indeed make sense as a request; however would be probably out of scope for this specific project here - or what do you think @louislam ?

**Comment by francismiles1** [comment] 2023-07-31 11:25
I suspect this has been looked into, and put on the back burner. I checked a couple of solutions out, admittedly Linux based, and all of them reported nonsense results, notably;
* https://github.com/sivel/speedtest-cli
* https://github.com/taganaka/SpeedTest
Didnt fiddle too much, but others reporting protocol problems... out of my pay grade!

**Comment by louislam** [comment] 2023-07-31 12:10
> It doesnt make sense based on “continuously”. The word you are probably looking for based on what you wrote is “periodically”.
> 
> That would indeed make sense as a request; however would be probably out of scope for this specific project here - or what do you think @louislam ?

Theoretically it may be a valid feature-request. In reality, without the infra like fast.com or speedtest.net, I don't think it is possible to keep checking the internet speed. Also max out the internet bandwidth may cause issues to other monitors.

> https://github.com/sivel/speedtest-cli
https://github.com/taganaka/SpeedTest

Those libraries depends on Speedtest.net, I believe it has a rate limit.

**Comment by CommanderStorm** [comment] 2023-09-17 16:14
@vignesh-mohankumar 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/744
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-12-03 16:53 UTC
Labels: feature-request
