### ISSUE TITLE
AND/OR on Monitor Groups

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#5291] opened 2024-10-31 12:18 UTC
### 📑 I have found these related issues/pull requests

Can't find anything existing

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

At present, Monitor Groups react when any of their component Monitors are changed - e.g. if one component monitor is down, then the group is down.

There are situations where you may have multiple monitors and only want to be notified if they are all down. An example would be my DNS provider where I have multiple, but it is only a problem if they are all down.

### ✔️ Solution

Add a switch to Monitor Groups to say if the group reacts to ANY monitors ('OR') or to ALL monitors ('AND').

In this way, the OpenDNS example above could be addressed by having an ALL/AND group, requiring that all monitors be affected before the group status is changed.

Then, in effect, it creates virtual monitors (groups) that can be made up of other monitors.

**Comment by CommanderStorm** [comment] 2024-10-31 21:58
Duplicate of https://github.com/louislam/uptime-kuma/issues/3387

**Closed by CommanderStorm** 2024-10-31 21:58 UTC
Labels: feature-request
