### ISSUE TITLE
Ability to sort list or filter list by Status

### ISSUE THREAD

**Issue by dotspecialists** [louislam/uptime-kuma#1585] opened 2022-04-28 21:48 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I have more than two thousand websites I monitor using this easy-to-use awesome tool. When I do see a few sites down, it's difficult to find the sites being impacted as there seems to be no way to filter the list by up, down or paused status. It would nice that under Quick Stats, each stat number is a hyperlink to a filtered list showing all sites that have a matching status. Please see image: https://i.imgur.com/uP9VJgH.png

### ✔️ Solution

Add sort of list or filter by status

**Comment by teoxrr** [comment] 2022-05-04 12:16
I think its duplicate of: https://github.com/louislam/uptime-kuma/issues/1165

**Comment by zolotarev** [comment] 2022-08-04 13:39
Hi all!
I added simple filtering ability to the monitors list.
Please let's discuss.
@louislam

**Comment by dotspecialists** [comment] 2022-08-04 16:57
@zolotarev, that is awesome.  Do you need us to download some preview version and try it and provide feedback?

**Comment by teoxrr** [comment] 2022-08-05 08:56
Very helpful feature, lets merge it!

**Comment by zolotarev** [comment] 2022-08-10 21:36
> @zolotarev, that is awesome. Do you need us to download some preview version and try it and provide feedback?

You can checkout my changes and try locally. I believe that any feedbacks make merging nearer.

**Comment by EdgeCCTV-Austen** [comment] 2022-08-29 17:12
Any word on this getting merged? Is it in a recent update yet?

**Comment by javaindian** [comment] 2022-11-10 08:07
> > @zolotarev, that is awesome. Do you need us to download some preview version and try it and provide feedback?
> 
> Thanks for reply! You can checkout my changes and try locally. I believe that any feedbacks make merging nearer.

Hi @zolotarev 

I tried it in v 1.19.0-beta.0. Copied all the three file contents and pasted in respective files. Restarted the Kuma server.

Its not showing any sorting. Am i missing something?

Thanks

![image](https://user-images.githubusercontent.com/61616901/201035369-0216a24e-c765-4f5c-b4b9-096c4bff3795.png)

**Comment by teoxrr** [comment] 2022-11-10 08:14
> > > @zolotarev, that is awesome. Do you need us to download some preview version and try it and provide feedback?
> > 
> > 
> > Thanks for reply! You can checkout my changes and try locally. I believe that any feedbacks make merging nearer.
> 
> Hi @zolotarev
> 
> I tried it in v 1.19.0-beta.0. Copied all the three file contents and pasted in respective files. Restarted the Kuma server.
> 
> Its not showing any sorting. Am i missing something?
> 
> Thanks
> 
> ![image](https://user-images.githubusercontent.com/61616901/201035369-0216a24e-c765-4f5c-b4b9-096c4bff3795.png)

I think it has never been merged, so you cannot find it on 1.19.0

**Comment by javaindian** [comment] 2022-11-12 05:29
@zolotarev Any help pls

**Comment by EdgeCCTV-Austen** [comment] 2022-12-29 15:53
Just bumping this again, such a vital feature for a server monitoring system... I dont understand what's holding this up.

**Comment by lsanders** [comment] 2023-01-23 14:57
+1 for adding this feature

**Comment by jeremyrnelson** [comment] 2023-03-14 20:58
#1308 can be satisfied as well if we add the ability to sort by name, and sort by tag

**Comment by nielsstoltze** [comment] 2023-06-16 12:49
Hi, any news on this feature?

**Comment by CommanderStorm** [comment] 2023-06-17 09:19
@nielsstoltze 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

You can subscribe to the Pull Request to get updates. Currently that PR needs some polishing before being able to be merged.

**Closed** 2023-07-16 13:27 UTC
Labels: feature-request
