### ISSUE TITLE
Proxy setup for Google Chat notifications

### ISSUE THREAD

**Issue by beavis6511** [louislam/uptime-kuma#1867] opened 2022-07-05 08:00 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hello,
I would like to use the Google Chat notifications system but I have a Timeout error:

```
Error: Error: Error: connect ETIMEDOUT 172.217.18.202:443
    at GoogleChat.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
    at GoogleChat.send (/app/server/notification-providers/google-chat.js:41:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/app/server/server.js:1124:27)
```

### ✔️ Solution

To join the Google Chat server, I need to go through a web proxy.
It's possible to create and use proxy for monitors but not for notifications.
Solution: for notifications who use http(s) protocol, add a dropdown list to chose an existing proxy.

**Comment by dineshbabu179** [comment] 2022-09-30 02:55
I have a similar issue with sending webhook requests to Microsoft Teams.  my uptime-Kuma setup in the internal environment, any HTTP request to the internet should go through the proxy. The proxy setup for minoring works perfectly, but the notification setup is not using the proxy setup.

Here is my log. 

> Error: Error: Error: connect ETIMEDOUT 52.96.36.130:443 
    at Teams.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
    at Teams.send (/app/server/notification-providers/teams.js:149:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by dineshbabu179** [comment] 2022-10-01 03:33
@beavis6511  I have found the solution. 

in your compose file set the environment variable something like this 

    environment:
      HTTP_PROXY: 'http://proxy.example.com:3128'
      HTTPS_PROXY: 'http://proxy.example.com:3128' 

After setting up this the proxy through env variable, my Teams notification started working.

**Comment by canis54** [comment] 2023-01-11 09:32
@dineshbabu179 Even after the environment variables HTTP_PROXY and HTTPS_PROXY have been stored in the package.json continues to run the teams notification in the error 'ETIMEDOUT'.  The proxy variables set in Linux are also not used. What other option do I have to send a notification via a proxy?

**Comment by canis54** [comment] 2023-01-11 09:47
my log:
Error: Error: Error: connect ETIMEDOUT 52.98.171.226:443
at Teams.throwGeneralAxiosError (/opt/uptime-kuma/server/notification-providers/notification-provider.js:38:15)
at Teams.send (/opt/uptime-kuma/server/notification-providers/teams.js:153:18)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Socket.<anonymous> (/opt/uptime-kuma/server/server.js:1189:27)

**Comment by CommanderStorm** [comment] 2023-12-10 18:16
Duplicate of #616

**Closed by CommanderStorm** 2023-12-10 18:16 UTC
Labels: feature-request, area:notifications
