### ISSUE TITLE
SNMP v1 / 2   for  Cisco , Mikrotik

### ISSUE THREAD

**Issue by tontheonelove** [louislam/uptime-kuma#1779] opened 2022-06-16 01:57 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Please add SNMP V1/2/     for monitor interface Cisco , Mikrotik and more ....  for a more detailed monitor  when interface up - down

### ✔️ Solution

Add SNMP V1 / 2   For receive  interface value and monitor all interface for example  , Cisco and Mikrotik Router + Switch

**Comment by CommanderStorm** [comment] 2023-07-05 20:03
@tontheonelove 
Is this a duplicate of https://github.com/louislam/uptime-kuma/issues/1675 (which has these duplicates https://github.com/louislam/uptime-kuma/issues/3366, https://github.com/louislam/uptime-kuma/issues/420)?
If yes, please close this issue (duplicates are hard to isssue-manage and create immortal zombies)
If no, why is this a distinct issue from the ones mentioned above that it requires a different issue? ^^

**Closed** 2023-07-07 06:32 UTC
Labels: feature-request
