### ISSUE TITLE
Second or Third Inciedent Field

### ISSUE THREAD

**Issue by V1P-J0K3R** [louislam/uptime-kuma#1069] opened 2021-12-16 11:02 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

It would be Great if you can add a Second Incident or Notification Field on the Status Site.

### ✔️ Solution

Second or Third Info Field in Top of Uptime Kuma

**Comment by koen20** [comment] 2021-12-16 15:35
Duplicate of #579

**Closed** 2021-12-16 15:54 UTC
Labels: feature-request
