### ISSUE TITLE
Feature Request: Display heartbeat for the Last 90 Days on Status Page

### ISSUE THREAD

**Issue by leeryst55** [louislam/uptime-kuma#5168] opened 2024-10-08 11:18 UTC
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/1888

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

Hello,

I would like to request a feature that allows the status page to display incidents for the last 90 days. Currently, it seems that the status page shows incidents only for the last 24 hours.

Use Case:
Being able to view the status history over the last 90 days would be extremely helpful for both administrators and users to track service reliability and incidents over a longer period. This would aid in understanding trends and making informed decisions regarding service improvements.

Thank you for considering this request. I believe this feature would greatly enhance the usability of Uptime Kuma.

Best regards, Igor.

### ✔️ Solution

Suggested Implementation:
1. Modify the backend to allow fetching incidents for a specified period (e.g., 90 days).
2. Update the frontend to provide an option to view incidents for the selected time frame.
3. Ensure that the historical data is easily accessible and properly formatted on the status page.

**Comment by CommanderStorm** [comment] 2024-10-08 11:43
Duplicate of https://github.com/louislam/uptime-kuma/issues/1888

**Closed by CommanderStorm** 2024-10-08 11:43 UTC
Labels: feature-request
