### ISSUE TITLE
Generate Report to pdf or csv

### ISSUE THREAD

**Issue by albaboryza18** [louislam/uptime-kuma#2028] opened 2022-08-31 04:42 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

a tools from ui that can generate report uptime to pdf or csv

### ✔️ Solution

to make easy when we need report

**Comment by satyamsettyeswara** [comment] 2022-09-04 07:29
Hey! I want to do this. Before that I would like to know how to update the docker image with our changes in local. Could you help me how to do that?

**Comment by CommanderStorm** [comment] 2023-07-26 21:45
I think this is a duplicate of #366
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Closed** 2023-12-01 17:47 UTC
Labels: feature-request
