### ISSUE TITLE
Down Monitor is Automatically order up in list

### ISSUE THREAD

**Issue by vslknsgr** [louislam/uptime-kuma#1313] opened 2022-02-17 16:34 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

Hello Team,

Down Monitor is Automatically order up in list 

otherwise , You just give the new link only show down monitor 

### ✔️ Solution

-

**Comment by teoxrr** [comment] 2022-03-03 15:23
duplicate of #1165

**Comment by jeremyrnelson** [comment] 2022-11-29 20:58
@vslknsgr - it seems like we've got a lot of tickets open referencing the same features.  Is there anything in this ticket that's not covered in #1585 where there's already a pull request?  If not, can you close this?

**Comment by CommanderStorm** [comment] 2023-12-04 18:51
#3312 was merged and is available since `1.23.0`.
This likely covers this issue.
Selecting these parameters via query parameters is tracked in #3672
Filtering/sorting on the status page is tracked in #1512

**Closed by CommanderStorm** 2023-12-04 18:51 UTC
Labels: feature-request
