### ISSUE TITLE
Improve multi-probe edit

### ISSUE THREAD

**Issue by lucasarnulphy** [louislam/uptime-kuma#1055] opened 2021-12-13 22:50 UTC
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It'd be great if the edit menu of the probes could stay when switching to other probes.
That way, it'd be easy to check the config for all probes / change a value on many probes without the need to click the edit button each time.

### ✔️ Solution

Keep the "edit" menu displayed when switching probes.
Create a "close" button to close the menu.

**Comment by CommanderStorm** [comment] 2023-12-07 13:55
Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/455 (and maybe https://github.com/louislam/uptime-kuma/issues/1323)

**Closed by CommanderStorm** 2023-12-07 13:55 UTC
Labels: feature-request
